rails-sqlserver/activerecord-sqlserver-adapter

- activerecord-sqlserver-adapter.gemspec
- bin/console
- lib/active_record/connection_adapters/sqlserver/database_statements.rb
- lib/active_record/connection_adapters/sqlserver/schema_statements.rb
- lib/active_record/connection_adapters/sqlserver_column.rb
- lib/console.rb
Case specific queries does not take in to account database column collation, therefore, the generated queries force an index scan. I noticed the problem while using uniqueness validator which specifically either does a case sensitive or case insensitive comparison (I didn't find a way to make it use default database casing). 
For a column with case insensitive collation, `SQL_Latin1_General_CP1_CI_AS`, uniqueness validator generates the following queries.
`validates :title, uniqueness: true` generates `SELECT  1 AS one FROM [articles] WHERE [articles].[title] = N''t1'' COLLATE Latin1_General_CS_AS_WS   ORDER BY [articles].[id] ASC OFFSET 0 ROWS FETCH NEXT 1 ROWS ONLY`
while `validates :title, uniqueness: {:case_sensitive => false}` generates `SELECT  1 AS one FROM [articles] WHERE …
> improve case comparision performace

- lib/active_record/connection_adapters/sqlserver/database_statements.rb
- lib/active_record/connection_adapters/sqlserver/schema_statements.rb
- lib/active_record/connection_adapters/sqlserver/utils.rb
- lib/active_record/connection_adapters/sqlserver_adapter.rb
- lib/arel/visitors/sqlserver.rb
- test/cases/adapter_test_sqlserver.rb
- test/cases/fully_qualified_identifier_test_sqlserver.rb
- test/cases/utils_test_sqlserver.rb
Building on #426, this pull request fixes SELECT queries on linked servers. In addition, it is not necessary (and probably not desirable) to explicitly set the Arel table_alias for a model (causing other statements to break).
So, this should actually work:
```
class LinkedServerTest < ActiveRecord::Base
self.table_name = "[server].table.dbo.linked_server_test"
end
```
> Add linked server support to queries/commands

- lib/active_record/connection_adapters/sqlserver/type/char.rb
@metaskills with the latest introduction of SQLServer::Type::Char::Data object one of the active record serializers that my app is using stopped working.
I chased the issue down to https://github.com/rails/rails/blob/4-2-stable/activerecord/lib/active_record/type/string.rb#L35 where active record calls `value.to_s`.
Since `value` is of type `ActiveRecord::ConnectionAdapters::SQLServer::Type::Char::Data` it was not doing what is expected. 
Since the object doesn't have the `to_s` implementation it was returning a flat `"#<ActiveRecord::ConnectionAdapters::SQLServer::Type::Char::Data:0x000000044a0fe8>"` string, instead of returning the actual value from the database, breaking the serializer.
This PR adds just that, `to_s` implementation. Thoughts?
> Add to_s method to SQLServer::Type::Char::Data object

- lib/active_record/connection_adapters/sqlserver/quoting.rb
- lib/active_record/connection_adapters/sqlserver/type/date.rb
- lib/active_record/connection_adapters/sqlserver/type/datetime.rb
- lib/active_record/connection_adapters/sqlserver/type/datetimeoffset.rb
- lib/active_record/connection_adapters/sqlserver/type/smalldatetime.rb
- lib/active_record/connection_adapters/sqlserver/type/time.rb
- lib/active_record/connection_adapters/sqlserver/type/time_value_fractional.rb
Creating or updating records resets the attributes by mapping the hash using ActiveRecord's `Attribute#forgetting_assignment` method. This method essentiall mimics the reload by setting the attributes to FromDatabase using the FromUser value "for the database".
https://github.com/rails/rails/commit/07723c23
This is a problem for us because the `value_for_database` for date time objects are strings that can not be re-parsed due to SQL Server's time formats. For example, a date of August 18th 2016 would be formatted as '08-19-2016' and fail deserialize:
``` ruby
ActiveModel::Type::Date.new.deserialize('08-19-2016') # => nil
```
Both ActiveModel's date and time types rescue `Date.parse` methods of `new_date` and `new_time` with nil. It was suggested that we use Data classes for our time …
> [Rails5] Ensure date/time columns are not nil on create/update. Take 2.

- lib/active_record/connection_adapters/sqlserver/quoting.rb
- lib/active_record/connection_adapters/sqlserver/type.rb
- lib/active_record/connection_adapters/sqlserver/type/char.rb
- lib/active_record/connection_adapters/sqlserver/type/data.rb
- lib/active_record/connection_adapters/sqlserver/type/date.rb
- lib/active_record/connection_adapters/sqlserver/type/datetime.rb
- lib/active_record/connection_adapters/sqlserver/type/datetimeoffset.rb
- lib/active_record/connection_adapters/sqlserver/type/time.rb
- lib/active_record/connection_adapters/sqlserver/type/uuid.rb
- test/cases/specific_schema_test_sqlserver.rb
This moves all date/time types to use the data wrapper method. This work also creates a generic Data wrapper that simply delegates to a #quoted method on each type. This way our existing logic of parsing and casting our types is completely visible in each type class.
This work also removes some duplication we had done in `_quote` form `_type_cast`. 
cc @sgrif
> All date/times use Data type cast wrapper.

- lib/active_record/connection_adapters/sqlserver/database_statements.rb
- lib/active_record/connection_adapters/sqlserver/quoting.rb
- lib/active_record/connection_adapters/sqlserver/type/data.rb
- lib/active_record/connection_adapters/sqlserver/type/date.rb
- lib/active_record/connection_adapters/sqlserver/type/datetime.rb
- lib/active_record/connection_adapters/sqlserver/type/datetimeoffset.rb
- lib/active_record/connection_adapters/sqlserver/type/smalldatetime.rb
- lib/active_record/connection_adapters/sqlserver/type/time.rb
- test/cases/column_test_sqlserver.rb
I made a mistake and made `_type_cast` do quoting too. This is now fixed and we have greatly simplified it along with `_quote` and we now use these two to cast and quote as needed in our sp_executesql helpers.
Changed `sp_executesql_sql_type` to have a default `String` case to `nvarchar(max)` not ideal and there are places where we prefer the bind contain the proper SQLServer type. For example, uniquness validations yielding a `ActiveRecord::Relation::QueryAttribute` with a [basic cast type](https://github.com/rails/rails/blob/5-0-stable/activerecord/lib/active_record/validations/uniqueness.rb#L80) vs the in scope `cast_type` further up.
Added `sp_executesql_sql_param` which looks out for all `SQLServer::Data` and quotes it accordingly. For example, date & time objects need single quote …
> Refactor `_type_cast` & `_quote`.

- CHANGELOG.md
- lib/active_record/connection_adapters/sqlserver/database_statements.rb
- lib/active_record/connection_adapters/sqlserver/schema_statements.rb
- test/cases/adapter_test_sqlserver.rb
These changes make the full ActiveRecord test suite run about 100s faster from ~580s to ~480s.
* Use the `schema_cache.columns` for the `#primary_keys` method.
* Ensure that `exec_query` uses the proper arity/arg names. Namely `:prepare` opt.
* Ensure all view checks/methods used in `#columns` only.
* Removed view table name detection in `with_identity_insert_enabled` method for fixtures.
* Removed `#select` abstract adapter override since it was the same.
cc @sgrif
> [Rails5] Performance optimizations.

- CHANGELOG.md
- lib/active_record/connection_adapters/sqlserver/schema_statements.rb
- lib/active_record/connection_adapters/sqlserver/table_definition.rb
- lib/active_record/connection_adapters/sqlserver/type/datetime.rb
- lib/active_record/connection_adapters/sqlserver/type/money.rb
- lib/active_record/connection_adapters/sqlserver/type/small_money.rb
- lib/active_record/connection_adapters/sqlserver/type/time_value_fractional.rb
- lib/active_record/connection_adapters/sqlserver/type/unicode_varchar.rb
- lib/active_record/connection_adapters/sqlserver/type/unicode_varchar_max.rb
- lib/active_record/connection_adapters/sqlserver/type/varbinary.rb
- lib/active_record/connection_adapters/sqlserver/type/varbinary_max.rb
- lib/active_record/connection_adapters/sqlserver/type/varchar.rb
- lib/active_record/connection_adapters/sqlserver/type/varchar_max.rb
- lib/active_record/connection_adapters/sqlserver_adapter.rb
- test/cases/coerced_tests.rb
- test/cases/column_test_sqlserver.rb
* Automatically use datetime2 when precision is used.
* Integration of datetime2 with `type_to_sql` so schema types are right.
* New subclasses for Table and TableDefinition with overhauled column methods.
* Fix our time fractional helpers to make datetime/datetime2 under full tests pass.
* New coerced tests.
> Rails5 supports datetime with precision

- lib/active_record/connection_adapters/sqlserver/schema_statements.rb
- lib/active_record/connection_adapters/sqlserver_adapter.rb
- test/cases/coerced_tests.rb
> [Rails5] Support `unprepared_statement` blocks & ValueTooLong excp.

- lib/active_record/connection_adapters/sqlserver/type/datetime.rb
Another chapter in an epic series of getting our custom date time types passing all tests. I feel like we are in a constant battle that has gone downhill since we have to have specific quoting for each datetime type/precision that typically follows `%m-%d-%Y` format. This has been complicated by the fact that as part of forgetting assignment we could not rely on ActiveModel/Record to pare these strings for us which does not support a) our formats and b) time zones. I am willing to admit that all this work could somehow be easier but I can not see it. Other PRs include:
* https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/pull/528
* https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/pull/534
* https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/pu …
> [Rails5] Pass more attribute tests for date/time/zones.

- RAILS5-FAILS.txt
- circle.yml
- test/cases/coerced_tests.rb
Another case where `sp_executesql` both auto truncates and hence swallows a good error.
> Coerce a few ValueTooLong Tests

- lib/active_record/connection_adapters/sqlserver/schema_statements.rb
- test/cases/specific_schema_test_sqlserver.rb
- test/schema/sqlserver_specific_schema.rb
The following fix will correctly load column definitions across multiple schemas with similar table structures.  It is also significantly faster to load if using lots of schemas with similar structures/constraints.
> Filter table constraints with matching table schema to column.

- lib/active_record/connection_adapters/sqlserver/transaction.rb
- test/cases/transaction_test_sqlserver.rb
I found on a set up when:
```
SET ALLOW_SNAPSHOT_ISOLATION ON
SET READ_COMMITTED_SNAPSHOT ON
```
That you'd get the error: `TinyTds::Error: Incorrect syntax near 'SNAPSHOT'.: SET TRANSACTION ISOLATION LEVEL READ COMMITTED SNAPSHOT`.  This occurs because after running the transaction, the adapter is attempting to set the isolation level to `connection.user_options_isolation_level` which is actually `read committed snapshot` which is not valid.
I wasn't able to run the entire test suite on my setup but was able to get a fail, fix, pass for this specific issue.
> Handle using transactions and resetting isolation level correctly when `READ_COMMITTED_SNAPSHOT` is set to `ON`

- CHANGELOG.md
- lib/active_record/connection_adapters/sqlserver/schema_statements.rb
- lib/active_record/connection_adapters/sqlserver/table_definition.rb
- lib/active_record/connection_adapters/sqlserver_adapter.rb
- test/cases/adapter_test_sqlserver.rb
- test/cases/coerced_tests.rb
- test/cases/helper_sqlserver.rb
- test/models/sqlserver/sst_memory.rb
- test/schema/enable-in-memory-oltp.sql
- test/schema/sqlserver_specific_schema.rb
- test/support/test_in_memory_oltp.rb
In support of this work I created a simple `primary_key_nonclustered` helper since you can created clustered indexes on In-Memory tables. Also included is a simple example script created by Microsoft that helps ensure you Database has been configured to use In-Memory OLTP. This setup is run with an environment variable `IN_MEMORY_OLTP` for our tests only. This is because if the whole ActiveRecord test DB were set to `SET MEMORY_OPTIMIZED_ELEVATE_TO_SNAPSHOT = ON` it would cause a few other Rails test to fail.
Example table creation, assuming In-Memory OLTP setup:
```ruby
create_table :in_memory_table, id: false,
options: 'WITH (MEMORY_OPTIMIZED = ON, DURABILITY = SCHEMA_AND_DATA)' do |t|
t.primary_key_nonclustered :id
t.string :name
t.timestamps
end
```
More about In-Memory OLTP at …
> Example In-Memory DB Setup & Table(s)

- CHANGELOG.md
- RAILS5-TODO.md
- lib/active_record/connection_adapters/sqlserver/schema_statements.rb
- lib/active_record/connection_adapters/sqlserver/table_definition.rb
- lib/active_record/connection_adapters/sqlserver/type.rb
- lib/active_record/connection_adapters/sqlserver/type/json.rb
- lib/active_record/connection_adapters/sqlserver_adapter.rb
- test/cases/json_test_sqlserver.rb
- test/cases/schema_dumper_test_sqlserver.rb
- test/models/sqlserver/datatype_migration.rb
- test/schema/sqlserver_specific_schema.rb
Adds a simple JSON type for creating an underlying `nvarchar(max)` column to add JSON too. Since SQL Server does not have a true JSON type. This means supporting JSON from a Rails perspective is a simple as adding the proper SQL Server type to your model's column which has some form of underlying string type.
```ruby
create_table :users do |t|
t.string :name, :email
t.json :data # Creates a nvarchar(max) column.
end
class Users < ActiveRecord::Base
attribute :data, ActiveRecord::Type::SQLServer::Json.new
end
```
This allows you to save and return JSON data and query it as needed.
```ruby
User.create! name: 'DJ Ruby Rhod', data: nil
User.create! name: 'Ken Collins', data: { 'admin' => true, 'foo' => 'bar' }
admin = User.where("JSON_VALUE(data, '$.admin') = CAST(1 AS BIT)").first …
```
> Enable supports_json? for 2016 and up with a little bit of sugar.

- lib/active_record/connection_adapters/sqlserver/core_ext/active_record.rb
- lib/active_record/connection_adapters/sqlserver/core_ext/attribute_methods.rb
- lib/active_record/connection_adapters/sqlserver/core_ext/explain.rb
- lib/active_record/connection_adapters/sqlserver/core_ext/explain_subscriber.rb
See #588 
Use `ActiveSupport.on_load` to hook into ActiveRecord to respect the loading order. Otherwise configuration parameters might not be picked up in time.
> Bugfix: Use `ActiveSupport.on_load` to hook into ActiveRecord

- lib/active_record/connection_adapters/sqlserver/type/datetime.rb
- test/cases/coerced_tests.rb
Time attributes are being mangled in the Active Record after filter `changes_internally_applied` because the new attribute is being based of the serialized version of the time, which is a string. The new column value comes from parsing this string, but the old parsing method does not  account for the `default_timezone` setting causing the the time to be mis-interpreted.
> Fix mangled times after save when default_timezone is set to local

- CHANGELOG.md
- README.md
- lib/active_record/connection_adapters/sqlserver/database_statements.rb
- lib/active_record/connection_adapters/sqlserver_adapter.rb
- test/cases/adapter_test_sqlserver.rb
- test/cases/trigger_test_sqlserver.rb
- test/models/sqlserver/trigger.rb
- test/models/sqlserver/trigger_history.rb
- test/schema/sqlserver_specific_schema.rb
The adapter uses `OUTPUT INSERTED` so that we can select any data type key, for example UUID tables. However, this poses a problem with tables that use triggers. The solution requires that we use a more complex insert statement which uses a temporary table to select the inserted identity. To use this format you must declare your table exempt from the simple output inserted style with the table name into a concurrent hash. Optionally, you can set the data type of the table's primary key to return.
```ruby
adapter = ActiveRecord::ConnectionAdapters::SQLServerAdapter
adapter.exclude_output_inserted_table_names['my_table_name'] = true
adapter.exclude_output_inserted_table_names['my_uuid_table_name'] = 'uniqueidentifier'
```
Fixes #595 #593
> Identity Inserts with Triggers

- lib/active_record/connection_adapters/sqlserver/database_statements.rb
Right now, the adapter will use the default `case_insensitive_comparison` from ActiveRecord which performs a conversion to lower case no matter what ([see here](https://github.com/rails/rails/blob/f10a6467c5252afa73cbdecb7400667fdda27ada/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb#L428)). This gets called e.g. using the uniqueness validator with `case_sensitive: false`.
This conversion is unneeded and can be a performance issue if the collation in use is case insensitive anyway.
This PR is intended to avoid this when possible.
> Add case insensitive comparison for better performance with CI collations

- CHANGELOG.md
- lib/arel/visitors/sqlserver.rb
- test/cases/pessimistic_locking_test_sqlserver.rb
When you perform a query using locking and a left-join, the lock is used in both the FROM and LEFT OUTER JOIN portions of the query:
**ActiveRecord:** `Person.lock(true).left_joins(:readers).load`
**SQL:** `SELECT [people].* FROM [people] WITH(UPDLOCK) LEFT OUTER JOIN [readers] WITH(UPDLOCK) ON [readers].[person_id] = [people].[id]`
However, when you use the same query with a inner-join, the lock is not used in the INNER JOIN portion of the query:
**ActiveRecord:** `Person.lock(true).joins(:readers).load`
**SQL:** `SELECT [people].* FROM [people] WITH(UPDLOCK) INNER JOIN [readers] ON [readers].[person_id] = [people].[id]`
This change will apply the lock hint to the inner-joins. 
I came across this issue as we are trying to use NOLOCK hints on queries containing joins. 
**ActiveRecord:** …
> Use the query lock hint when joining tables

- test/bin/install-freetds.sh
Pointing the file download to http will fix the problems with Job #40.3 in travis ci. FTP download is unstable.
> Fix build problems for testing.

- lib/active_record/connection_adapters/sqlserver/type/time_value_fractional.rb
- test/cases/coerced_tests.rb
From [MS SQL docs](https://docs.microsoft.com/en-us/sql/t-sql/data-types/datetime-transact-sql?view=sql-server-2017), the datetime type has a millisecond precision of 1/300th of a second, or more specifically:
> Rounded to increments of .000, .003, or .007 seconds
The current implementation tries to round values passed as `datetime` to this standard, however the implementation is giving wrong values that do not end in either 0, 3 or 7. For example, if we pass a date ending in, say, `.8666667` seconds, it will incorrectly round to `.865` instead of `.867`, which would be the correct rounding for SQL Server, and also the correct rounding anywhere.
What I did was to eliminate a couple of inversions that were being done without any good reason (in fact they only made the result stray further …
> Fix Time value precision calculation

- .gitignore
- .travis.yml
- Dockerfile
- docker-compose.ci.yml
- docker-compose.yml
It's no uncommon to see tests failing because FreeTDS could not be installed due to ftp issues. In order to mitigate this issue, I created a Docker image with all dependencies installed so we can use to run tests.
Dockerfile can be found [here](https://github.com/wpolicarpo/activerecord-sqlserver-adapter-docker-image).
I'm happy to move Dockerfile source code to https://github.com/rails-sqlserver/docker-images if necessary.
> Configure tests to run inside a Docker container

- lib/active_record/connection_adapters/sqlserver/type/string.rb
- test/cases/column_test_sqlserver.rb
This is to fix #645.
String values in the `@value_before_type_cast` variables of the `attributes` set might be of type `ActiveRecord::ConnectionAdapters::SQLServer::Type::Data` after `serialize` has been called on them (e.g. on `save`) instead of being plain strings (which is the case for freshly created objects).
These values would get compared to the current values of attributes (these would be plain Ruby strings) when Rails figures out which fields to update.
However, this check would fail currently, marking the object as `changed` and so it would result in an extra unnecessary update query the next time it's saved.
This PR is intended to resolve this by enabling comparisons between `Type::Data` and plain string objects for `Type::String` attributes.
> Make String equality check work for Type::Data values

- lib/active_record/connection_adapters/sqlserver/schema_statements.rb
- test/cases/adapter_test_sqlserver.rb
Dumped `tinyint` columns should be imported back as `tinyint`, not `smallint`.
Fix #670.
> Fix tinyint columns schema migration

- lib/active_record/connection_adapters/sqlserver/schema_statements.rb
- test/cases/change_column_null_test_sqlserver.rb
- test/migrations/create_clients_and_change_column_null.rb
When using `change_column_null` in the following migration, the column's limit, precision and scale were being cleared.
https://github.com/lairtonlelis/sqlserver_adapter_issue/blob/master/db/migrate/20190222183019_create_clients.rb
Seems to be the same issue as #582.
> change_column_null should not clear other column attributes

- lib/active_record/connection_adapters/sqlserver/database_statements.rb
For now `table_name` is nil in case when pk is not nil
> #sql_for_insert set table name in case when pk is not nil

- lib/active_record/connection_adapters/sqlserver/database_tasks.rb
SQLServer sometimes (actually very often in my experience) fails to drop database with
`Cannot drop database [DATABASE_NAME] because it is currently in use.` error in some environments.
https://stackoverflow.com/questions/12702524/unable-to-drop-and-create-database-in-sql-server/12702579#12702579
https://dba.stackexchange.com/questions/2387/sql-server-cannot-drop-database-dbname-because-it-is-currently-in-use-but-n/2391#2391
https://www.mytechmantra.com/LearnSQLServer/Drop-Database-in-SQL-Server-by-Killing-Existing-Connections.html
https://serverfault.com/questions/440034/how-to-force-a-drop-of-mssql-server-database
This patch addresses this FAQ pitfall by changing the target DB to be SINGLE_USER mode before dropping, to make sure no other connections are alive.
> SET SINGLE_USER before dropping the database

- lib/active_record/connection_adapters/sqlserver/schema_statements.rb
- test/cases/migration_test_sqlserver.rb
```
activerecord-sqlserver-adapter (5.2.0)
tiny_tds (2.1.2-x64-mingw32)
rails (5.2.2)
```
rails migration
```
change_column :projects, :description, :text, :null => true, :default => nil
```
raises an error TinyTds::Error: The object 'DF_projects_description' is dependent on column 'description'.
there's a bug in activerecord-sqlserver-adapter that executes commands in wrong order
before
```
ALTER TABLE table REMOVE CONSTRAINT
ALTER TABLE table ADD CONSTRAINT
ALTER TABLE table ALTER COLUMN
```
after
```
ALTER TABLE table REMOVE CONSTRAINT
ALTER TABLE table ALTER COLUMN
ALTER TABLE table ADD CONSTRAINT
```
> fix constrains bug

- lib/arel/visitors/sqlserver.rb
These constants have been removed in 6.0.0.rc1 since it's a micro-optimisation that Ruby no longer needs. I have replaced them with string literals.
>  Fix constants missing in 6.0.0.rc1 

- test/cases/adapter_test_sqlserver.rb
- test/cases/change_column_null_test_sqlserver.rb
- test/cases/column_test_sqlserver.rb
- test/cases/connection_test_sqlserver.rb
- test/cases/fetch_test_sqlserver.rb
- test/cases/helper_sqlserver.rb
- test/cases/json_test_sqlserver.rb
- test/cases/migration_test_sqlserver.rb
- test/cases/pessimistic_locking_test_sqlserver.rb
- test/cases/rake_test_sqlserver.rb
- test/cases/schema_dumper_test_sqlserver.rb
- test/cases/schema_test_sqlserver.rb
- test/cases/showplan_test_sqlserver.rb
- test/cases/specific_schema_test_sqlserver.rb
- test/cases/transaction_test_sqlserver.rb
- test/cases/trigger_test_sqlserver.rb
- test/cases/utils_test_sqlserver.rb
- test/cases/uuid_test_sqlserver.rb
Hi. @wpolicarpo
Now, this gem's test is broken.
It occurs a lot of `NoMethodError: undefined method split' for nil:NilClass` , because of Rails backtrace cleaner silences all backtrace.
https://github.com/seattlerb/minitest/blob/15ed8e4ce504c8313058a1d6fc4918299be34328/lib/minitest/spec.rb#L12
So, I use Rails backtrace in first commit.
And next commit supresses minitest warning.
But test fails with some `TinyTds::Error` yet.
I will try to success the test in next pull request.
> NoMethodError: undefined method `split' for nil:NilClass in tests

- lib/arel/visitors/sqlserver.rb
This fixes concat to generate `a + b`, previously it generated the standard SQL `a || b` which SQL Server does not support.
> Fix concatenate syntax

- test/cases/coerced_tests.rb
Fix the minitest expectation deprecation warnings from the coerced tests.
Example from https://travis-ci.org/rails-sqlserver/activerecord-sqlserver-adapter/jobs/654830621?utm_medium=notification&utm_source=github_status
```
DEPRECATED: global use of must_equal from activerecord-sqlserver-adapter/test/cases/coerced_tests.rb:618. Use _(obj).must_equal instead. This will fail in Minitest 6.
DEPRECATED: global use of must_equal from activerecord-sqlserver-adapter/test/cases/coerced_tests.rb:619. Use _(obj).must_equal instead. This will fail in Minitest 6.
...
```
This is a follow-on from PR https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/pull/718
> Fix minitest expectation deprecation warnings 

- lib/active_record/connection_adapters/sqlserver/core_ext/calculations.rb
Fixes the following failing calculation tests:
- CalculationsTest#test_group_by_with_offset
- CalculationsTest#test_group_by_with_limit_and_offset
- CalculationsTest#test_group_by_with_limit
The tests were failing because of a change made in Rails 5.2.3 (https://github.com/rails/rails/pull/35850/files#diff-e0e70620d0897d6819a6bcc2b5ee7a73R137) that removed ordering in calculations. The change works for PostgreSQL/SQLite/MySQL but causes invalid SQL to be generated for MSSQL.
**Rails** 5.2.3
SQL generated for this test was:
```
EXEC sp_executesql N'SELECT COUNT(DISTINCT comments.id) AS count_comments_id, [posts].[type] AS posts_type FROM [posts] LEFT OUTER JOIN [comments] ON [comments].[post_id] = [posts].[id] GROUP BY [posts].[type]  ORDER BY [posts].[type] ASC OFFSET @0 ROWS', N'@0 int', …
```
> Calculate should not remove ordering for MSSQL

- lib/active_record/connection_adapters/sqlserver/type/time.rb
- test/cases/column_test_sqlserver.rb
- test/cases/schema_dumper_test_sqlserver.rb
- test/schema/datatypes/2012.sql
Fixes the failing ActiveRecord "SchemaDumperDefaultsTest#test_schema_dump_with_float_column_infinity_default" test, which was throwing an error during the setup stage.
See failing test at https://travis-ci.org/rails-sqlserver/activerecord-sqlserver-adapter/jobs/655397653?utm_medium=notification&utm_source=github_status
The test was failing because the precision was being extracted from the column type. The precision for `time(2)` is correctly returned as 2. The precision for `time` was incorrectly being returned as `nil`. The actual default precision for `time` in MSSQL is 7 (https://docs.microsoft.com/en-us/sql/t-sql/data-types/time-transact-sql?view=sql-server-ver15). So updated the adapter to return default precision if column type is `time`.
The …
> Use default precision for 'time' column type

- test/cases/coerced_tests.rb
On PostgreSQL/MySQL/SQLite to reuse a query plan you need to first prepare the query as a prepared statement, cache the prepared statement in a statement pool and then call that prepared statement with your bindings. If same query is called again on that connection then the prepared statement can be retrieved from the statement pool and reused.
SQL Server using `EXEC sp_executesq` works differently. Query plans are reused based on the SQL that is passed. So there is no need to prepare the query into a prepared statement first. This removes the need for the statement cache in the SQL Server adapter. So the binding tests that assume a statement pool can be coerced.
The PR also includes a substitute test for a previously coerced test.
> Adapter does not use prepared statement cache

- lib/active_record/connection_adapters/sqlserver/type/time.rb
- lib/active_record/connection_adapters/sqlserver_adapter.rb
Should set the default precision of the time type when registering it rather than defaulting it within the `ActiveRecord::ConnectionAdapters::SQLServer::Type::Time` class.
This is a refactoring of https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/pull/737
> Set default time precision when registering time type

- lib/active_record/connection_adapters/sqlserver/core_ext/query_methods.rb
- lib/active_record/connection_adapters/sqlserver_adapter.rb
Fixes the `translate_exception` method signature to match https://github.com/rails/rails/pull/34468
Solution taken from https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/pull/731/commits/8d2b737d36c34435fdf5b47c5cf8a33b8f83c1cd#diff-04856c2487c5333749a6ebcd6637213cR324
**Before**
https://travis-ci.org/github/rails-sqlserver/activerecord-sqlserver-adapter/jobs/667214433?utm_medium=notification&utm_source=github_status
```
6728 runs, 18598 assertions, 72 failures, 48 errors, 25 skips
```
**After**
https://travis-ci.org/github/rails-sqlserver/activerecord-sqlserver-adapter/jobs/667328226?utm_medium=notification&utm_source=github_status
```
6728 runs, 18643 assertions, 53 failures, 44 errors, 25 skips
```
> Rails 6: Fix for translate_exception method signature

- lib/arel/visitors/sqlserver.rb
Fix to correctly retrieve the Arel::Table when using a join query. 
Solution taken from https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/pull/704
**Before**
https://travis-ci.org/github/rails-sqlserver/activerecord-sqlserver-adapter/jobs/668693683?utm_medium=notification&utm_source=github_status
```
6728 runs, 18637 assertions, 53 failures, 43 errors, 25 skips
```
**After**
https://travis-ci.org/github/rails-sqlserver/activerecord-sqlserver-adapter/jobs/668832573?utm_medium=notification&utm_source=github_status
```
6728 runs, 18642 assertions, 53 failures, 39 errors, 25 skips
```
> Rails 6: Correctly retrieve Arel::Table in join queries

- lib/active_record/connection_adapters/sqlserver/core_ext/finder_methods.rb
Updated our monkey-patched `construct_relation_for_exists` method with change to sanitize forbidden attributes. Original Rails change in https://github.com/rails/rails/pull/35193
This fixes ActiveRecord test `FinderTest#test_exists_with_strong_parameters`.
**Before**
https://travis-ci.org/github/rails-sqlserver/activerecord-sqlserver-adapter/jobs/669152512?utm_medium=notification&utm_source=github_status
```
6728 runs, 18645 assertions, 53 failures, 39 errors, 25 skips
```
**After**
https://travis-ci.org/github/rails-sqlserver/activerecord-sqlserver-adapter/jobs/669281834?utm_medium=notification&utm_source=github_status
```
6728 runs, 18646 assertions, 53 failures, 38 errors, 25 skips
```
> Rails 6: Sanitize forbidden attributes for exists relation

- lib/active_record/connection_adapters/sqlserver_adapter.rb
Added method `ActiveRecord::ConnectionAdapters::SQLServerAdapter#get_database_version` to support https://github.com/rails/rails/pull/35795
This fixes the `ActiveRecord::ConnectionAdapters::SchemaCacheTest` failing tests.
**Before**
https://travis-ci.org/github/rails-sqlserver/activerecord-sqlserver-adapter/jobs/669298290?utm_medium=notification&utm_source=github_status
```
6728 runs, 18648 assertions, 53 failures, 38 errors, 25 skips
```
**After**
```
6728 runs, 18636 assertions, 53 failures, 36 errors, 25 skips
```
> Rails 6: Cache database version in schema cache

- lib/active_record/connection_adapters/sqlserver/database_statements.rb
Removed the adapter specific version of `combine_multi_statements`. 
This fixes the following tests:
- ActiveRecord::AdapterTestWithoutTransaction#test_truncate
- ActiveRecord::AdapterTestWithoutTransaction#test_truncate_with_query_cache
**Before**
https://travis-ci.org/github/rails-sqlserver/activerecord-sqlserver-adapter/jobs/669696511?utm_medium=notification&utm_source=github_status
```
6728 runs, 18643 assertions, 53 failures, 36 errors, 25 skips
```
**After**
https://travis-ci.org/github/rails-sqlserver/activerecord-sqlserver-adapter/jobs/669731725?utm_medium=notification&utm_source=github_status
```
6728 runs, 18642 assertions, 53 failures, 34 errors, 25 skips
```
> Rails 6: Use default combine multi statements method

- Gemfile
Use the `https` protocol to connect to Github rather than `git`. This will remove the following warning message.
```
$  bundle install
The git source `git://github.com/rails/rails.git` uses the `git` protocol, which transmits data without encryption. Disable this warning with `bundle config git.allow_insecure true`, or switch to the `https` protocol to keep your data secure.
Fetching git://github.com/rails/rails.git
...
```
I copied the code from the Rails Gemfile https://github.com/rails/rails/blob/master/Gemfile
> Use https protocol for Github

- lib/arel/visitors/sqlserver.rb
- test/cases/in_clause_test_sqlserver.rb
In MSSQL subqueries cannot have ordering unless they include `TOP` or `OFFSET`, otherwise a `The ORDER BY clause is invalid in views, inline functions, derived tables, subqueries, and common table expressions, unless TOP, OFFSET or FOR XML is also specified.` error is returned.
_Note that ordering in subqueries is valid if it includes `FOR XML` but this use-case is not supported in the adapter._
**Before**
https://travis-ci.org/github/rails-sqlserver/activerecord-sqlserver-adapter/jobs/670183329?utm_medium=notification&utm_source=github_status
```
6728 runs, 18634 assertions, 53 failures, 34 errors, 25 skips
```
**After**
https://travis-ci.org/github/rails-sqlserver/activerecord-sqlserver-adapter/jobs/671990453?utm_medium=notification&utm_source=github_status
```
6731 runs, 18699 …
```
> Rails 6: Subqueries cannot include ordering unless TOP/LIMIT also specified

- test/cases/coerced_tests.rb
MSSQL does not allow tables to be truncated if they have foreign key constraints. This is the cause of the `ActiveRecord::StatementInvalid: TinyTds::Error: Cannot truncate table 'author_addresses' because it is being referenced by a FOREIGN KEY constraint.` errors in the tests.
For the tests that involve truncating just one table I have removed the foreign key, performed the test and then restored the foreign key at the end.
I have coerced the test that truncates all tables as I would need to remove all foreign keys in all tables and then later restore them and I don't know an easy way of doing that.
References:
- https://stackoverflow.com/questions/253849/cannot-truncate-table-because-it-is-being-referenced-by-a-foreign-key-constraint
- …
> Rails 6: Add/remove foreign keys when truncating during tests

- lib/active_record/connection_adapters/sqlserver/schema_statements.rb
- lib/active_record/connection_adapters/sqlserver_column.rb
Rails no longer stores table names on columns since https://github.com/rails/rails/pull/35890 However, for the MSSQL adapter we need to continue to store the table name so that identity values can be calculated. See https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/blob/8b48e5ff5bdb3e95d38437d0433735d0cf6f6b98/lib/active_record/connection_adapters/sqlserver/database_statements.rb#L115
**Before**
https://travis-ci.org/github/rails-sqlserver/activerecord-sqlserver-adapter/jobs/672064166
```
6728 runs, 18676 assertions, 53 failures, 16 errors, 25 skips
```
**After**
https://travis-ci.org/github/rails-sqlserver/activerecord-sqlserver-adapter/jobs/672458067
```
6728 runs, 18680 assertions, 53 failures, 13 errors, 25 skips
```
> Rails 6: Store table names on columns to generate identities

- test/cases/migration_test_sqlserver.rb
Fixes the failing test `FullyQualifiedIdentifierTestSQLServer::remote server#test_0005_should use fully qualified table name in insert statement`.
**Before**
https://travis-ci.org/github/rails-sqlserver/activerecord-sqlserver-adapter/jobs/672479581
```
6728 runs, 18679 assertions, 53 failures, 14 errors, 25 skips
```
**After**
https://travis-ci.org/github/rails-sqlserver/activerecord-sqlserver-adapter/jobs/672538462
```
6728 runs, 18688 assertions, 52 failures, 13 errors, 25 skips
```
> Rails 6: Fixed migration test

- Gemfile
- test/cases/coerced_tests.rb
- test/cases/schema_dumper_test_sqlserver.rb
I took a shot at correcting the tests.  Here are the current results, I didn't finish the Active Record tests as I'm not knowledgable enough to see what next steps should be taken place there.
*Results from `bundle exec rake test ONLY_SQLSERVER=1`*
Finished in 15.071858s, 15.5920 runs/s, 95.6750 assertions/s.
235 runs, 1442 assertions, 0 failures, 0 errors, 1 skips
*Results from `bundle exec rake test ONLY_ACTIVERECORD=1`*
Finished in 160.342181s, 32.8236 runs/s, 93.5562 assertions/s.
5263 runs, 15001 assertions, 0 failures, 16 errors, 3 skips
> Correcting tests

- lib/active_record/connection_adapters/sqlserver/schema_statements.rb
- test/support/core_ext/query_cache.rb
- test/support/sql_counter_sqlserver.rb
I work on a large Rails application with multiple databases and several tables each. We identified that one particular type of query was taking too much CPU and time to compile and sometimes it was giving us bad query plans. The query in question is the one the adapter uses to read table information to pass onto `ActiveRecord` underlying `Column` object.
After some refactoring we came up with a better query that reduced CPU by 75% and compilation time by 50% on average.
We used 2 main statistics to analyse the performance (apart from our monitoring tools, which give us a better overview that I can't share publicly, unfortunately). We've been running a monkey patched version of the adapter with this query with no problems and I thought it would be good to send it upstream.
Running the old …
> Refactor columns introspection query to make it faster

- test/cases/coerced_tests.rb
Fix coerced tests file so that you can run:
```
bundle exec rake test TEST_FILES="test/cases/coerced_tests.rb"
```
> Rails 6: Fix coerced tests

- lib/active_record/connection_adapters/sqlserver/quoting.rb
- test/cases/coerced_tests.rb
Updated the `UnsafeRawSqlTest` tests to match the tests in Rails 6. Tests were coerced as the originals were using `LENGTH` to get string length. MSSQL does not support `LENGTH` and you need to use `LEN` instead. Some of the original tests were changed to no longer use `LENGTH` and so they no longer have to be coerced. Many of the Rails tests were changed in https://github.com/rails/rails/pull/36448
Added MSSQL specific sanitization matchers to handle square brackets in table names (eg: [posts].[title]). This follows the same method that the other database adapters use (https://github.com/rails/rails/blob/8544c9c23687964ab754c06a7745215a5369a4e0/activerecord/lib/active_record/connection_adapters/mysql/quoting.rb#L43).
These changes fix all of the failing `UnsafeRawSqlTest` tests. …
> Rails 6: Updated unsafe raw sql tests to match tests in Rails 6

- lib/arel/visitors/sqlserver.rb
- test/cases/coerced_tests.rb
The MSSQL adapter is different from other adapters in that it adds an ORDER BY clause even to simple `find` queries to make them deterministic. 
SQL generated by `Task.find(1)`:
```
SELECT [tasks].* FROM [tasks] WHERE [tasks].[id] = @0  ORDER BY [tasks].[id] ASC OFFSET 0 ROWS FETCH NEXT @1 ROWS ONLY
```
The ordering requirement causes the Rails `QueryCacheTest#test_query_cached_even_when_types_are_reset` to fail. The test resets the column information (which includes the table's primary key) and then tests that no queries were performed to confirm that the result came from the query cache rather than the database. However, for the MSSQL adapter to generate the SQL that is used as the query cache key it needs to query the database to find the primary key to use in the ORDER BY clause.
This …
> Rails 6: Allow primary key query in query cache test

- lib/active_record/connection_adapters/sqlserver/database_limits.rb
Depreciate the SQL Server adapter's database limit methods that were deprecated in 
https://github.com/rails/rails/blob/v6.0.0/activerecord/lib/active_record/connection_adapters/abstract/database_limits.rb
**Before**
https://travis-ci.org/github/rails-sqlserver/activerecord-sqlserver-adapter/jobs/674787276
```
6728 runs, 18686 assertions, 46 failures, 11 errors, 25 skips
```
**After**
https://travis-ci.org/github/rails-sqlserver/activerecord-sqlserver-adapter/jobs/674844320
```
6728 runs, 18687 assertions, 39 failures, 12 errors, 25 skips
```
> Rails 6: Database limit method deprecations

- test/cases/fully_qualified_identifier_test_sqlserver.rb
This PR fixes the following tests:
- FullyQualifiedIdentifierTestSQLServer::remote server#test_0004_should not use fully qualified table name in order clause 
- FullyQualifiedIdentifierTestSQLServer::remote server#test_0005_should use fully qualified table name in insert statement
**Before**
https://travis-ci.org/github/rails-sqlserver/activerecord-sqlserver-adapter/jobs/674956935
```
6728 runs, 18681 assertions, 39 failures, 12 errors, 25 skips
```
**After**
https://travis-ci.org/github/rails-sqlserver/activerecord-sqlserver-adapter/jobs/675213049
```
6728 runs, 18695 assertions, 38 failures, 10 errors, 25 skips
```
> Rails 6: Fix fully qualified identifier tests

- test/cases/coerced_tests.rb
Moved tests that were extracted from `persistence_test.rb` into `update_all_test.rb`. Coerced tests that involved updating identity column, which SQL Server cannot do.
**Before**
https://travis-ci.org/github/rails-sqlserver/activerecord-sqlserver-adapter/jobs/675244061
```
6732 runs, 18719 assertions, 33 failures, 10 errors, 25 skips
```
**After**
https://travis-ci.org/github/rails-sqlserver/activerecord-sqlserver-adapter/jobs/675297322
```
6731 runs, 18705 assertions, 31 failures, 10 errors, 25 skips
```
> Rails 6: Fix persistence and update all tests

- test/cases/showplan_test_sqlserver.rb
Fixes the `activerecord-sqlserver-adapter/test/cases/showplan_test_sqlserver.rb:22` test. 
**Before**
https://travis-ci.org/github/rails-sqlserver/activerecord-sqlserver-adapter/jobs/675244061
```
6732 runs, 18719 assertions, 33 failures, 10 errors, 25 skips
```
**After**
https://travis-ci.org/github/rails-sqlserver/activerecord-sqlserver-adapter/jobs/675306721
```
6732 runs, 18717 assertions, 32 failures, 10 errors, 25 skips
```
> Rails 6: Fix showplan test

- test/cases/coerced_tests.rb
Skip the `UniquenessValidationTest#test_validate_case_sensitive_uniqueness_by_default` test if the database is case-insensitive as test wouldn't make any sense in that scenario.
**Before**
https://travis-ci.org/github/rails-sqlserver/activerecord-sqlserver-adapter/jobs/675315237
```
6731 runs, 18715 assertions, 30 failures, 10 errors, 25 skips
```
**After**
https://travis-ci.org/github/rails-sqlserver/activerecord-sqlserver-adapter/jobs/677282218
```
6731 runs, 18711 assertions, 29 failures, 10 errors, 26 skips
```
> Rails 6: Skip case sensitive test if database case insensitive

- test/cases/coerced_tests.rb
The SQL generated by the SQL Server adapter doesn't match the regex used in the original Rails tests. Coerced the tests so that the tests pass.
**Before**
https://travis-ci.org/github/rails-sqlserver/activerecord-sqlserver-adapter/jobs/677292651
```
6731 runs, 18715 assertions, 29 failures, 10 errors, 26 skips
```
**After**
https://travis-ci.org/github/rails-sqlserver/activerecord-sqlserver-adapter/jobs/677618512
```
6731 runs, 18705 assertions, 26 failures, 10 errors, 26 skips
```
> Rails 6: Fix asserted SQL to get one row

- test/cases/coerced_tests.rb
- test/support/coerceable_test_sqlserver.rb
SQL Server differs from PostgreSQL/MySQL/SQLite in how it handles `NULL` values in unique indexes. 
For example, if you had a table with first and last names and created a unique index on both columns then the following 2 records would violate the unique index on SQL Server. 
| First Name  | Last Name |
| ------------- | ------------- |
| Bob  | NULL  |
| Bob  | NULL  |
However, in PostgreSQL/MySQL/SQLite unique indexes do not consider the NULL values equal and so the 2 records can be inserted successfully. 
This meant that some Rails tests were failing because the records required for the tests could not be inserted using SQL Server. The tests themselves were not testing unique indexes and assumed the records could be inserted.
In this PR the unique indexes are removed before the Rails …
> Rails 6: Fix tests that fail because of unique NULL indexes

- test/cases/coerced_tests.rb
SQL Server adapter does not use a statement cache. This PR coerces the `ActiveRecord::BindParameterTest#test_statement_cache_with_find` test added in Rails 6.
References:
- https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/pull/744
> Rails 6: Adapter does not use prepared statement cache

- lib/active_record/connection_adapters/sqlserver/schema_creation.rb
in connection to pull request: https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/pull/775
used @aidanharan  suggested workaround  -  https://lonewolfonline.net/sql-server-create-table-if-not-exists/
and implemented an `:if_not_exists` option to `create_table`. ([ActiveRecord Pull Request](https://github.com/rails/rails/pull/31382))
fixing MigrationTest#test_create_table_with_if_not_exists_true test.
> Rails 6: Add an `:if_not_exists` option to `create_table`

- Gemfile
https://travis-ci.org/github/rails-sqlserver/activerecord-sqlserver-adapter/jobs/675297322
```
ActiveRecord::ConnectionAdapters::ConnectionHandlersMultiDbTest#test_switching_connections_with_database_url:
LoadError: Error loading the 'postgresql' Active Record adapter. Missing a gem it depends on? pg is not part of the bundle. Add it to your Gemfile.
```
> Rails 6: Install PostgreSQL gem

- test/cases/coerced_tests.rb
Rails 6 deprecated update_attributes/! aliases for update/!  https://github.com/rails/rails/pull/31998.
Remove `coerced_tests.rb` update_attributes usage.
> Rails 6: fix deprecated update_attributes method usage

- test/cases/coerced_tests.rb
Updated the coerced test `QueryCacheTest#test_cache_does_not_wrap_results_in_arrays_coerced` to match what is in the Rails test https://github.com/rails/rails/blob/v6.0.0/activerecord/test/cases/query_cache_test.rb#L339
> Rails 6: Update query cache test

- test/cases/coerced_tests.rb
Fixes test_default_decimal_number to assert `record.decimal_number_before_type_cast` against number from string.
Like `test_default_positive_integer_coerced` and `test_default_negative_integer`.
> Rails 6: coerce test_default_decimal_number to assert against number

- lib/active_record/connection_adapters/sqlserver/core_ext/preloader.rb
- lib/active_record/connection_adapters/sqlserver_adapter.rb
Since https://github.com/rails/rails/pull/36074, `in_clause_length` will
no longer help the adapter to avoid complex query limitation, and will
be removed from Rails code base (https://github.com/rails/rails/pull/39057).
> Fix `EagerLoadingTooManyIdsTest#test_preloading_too_many_ids`

- lib/active_record/connection_adapters/sqlserver_adapter.rb
This PR fixes the `ActiveRecord::AdapterForeignKeyTest#test_foreign_key_violations_on_delete_are_translated_to_specific_exception` test. Needed to convert SQL Server error message into `ActiveRecord::InvalidForeignKey` exception.
Also, updated the SQL Server exceptions to pass SQL and binds when created. This follows how the rest of the adapters work.
**Before**
https://travis-ci.org/github/rails-sqlserver/activerecord-sqlserver-adapter/jobs/680001607
```
6730 runs, 18712 assertions, 25 failures, 1 errors, 26 skips
```
**After**
https://travis-ci.org/github/rails-sqlserver/activerecord-sqlserver-adapter/jobs/680112852
```
6730 runs, 18717 assertions, 24 failures, 1 errors, 26 skips
```
> Rails 6: Raise exception for foreign key constraint violation

- test/cases/coerced_tests.rb
I run the tests suite without the `coerced tests.rb` file and found old coerced tests that been fix in active record.
I removed old tests and tried to update tests to match the original tests.
I added comments to tests.
> Rails 6: Clean coerced tests

- test/cases/coerced_tests.rb
Like Mysql2 and PostgreSQL, SQL Server doesn't return a string value for updated_at. In the Rails tests these tests are skipped if adapter is Mysql2 or PostgreSQL.
See Rails tests at:
- https://github.com/rails/rails/blob/v6.0.0/activerecord/test/cases/cache_key_test.rb#L53
- https://github.com/rails/rails/blob/v6.0.0/activerecord/test/cases/cache_key_test.rb#L65
- https://github.com/rails/rails/blob/v6.0.0/activerecord/test/cases/cache_key_test.rb#L86
Related to Rails PR https://github.com/rails/rails/pull/33835
> Rails 6: Coerce tests as SQL Server does not return string value for updated_at

- lib/active_record/connection_adapters/sqlserver/schema_statements.rb
- test/cases/coerced_tests.rb
Coerce the `TimePrecisionTest#test_no_time_precision_isnt_truncated_on_assignment` test as its not applicable for SQL Server. 
Test checks that time value isn't truncated if the time column has no precision. However, SQL Server uses default time precision of 7, so value is truncated. The `test_time_precision_is_truncated_on_assignment_coerced` already tests that the values in columns with precision are truncated correctly.
> Rails 6: Coerce time no precision test

- test/cases/coerced_tests.rb
This PR coerces and fixes the `RelationTest#test_reorder_with_take` and `RelationTest#test_reorder_with_first` tests. The SQL Server adapter uses implicit ordering on the identifier column and so the original Rails tests didn't make sense.
> Rails 6: Take and first use implicit ordering on identifier column

- lib/active_record/connection_adapters/sqlserver/database_statements.rb
- lib/active_record/connection_adapters/sqlserver_adapter.rb
- test/cases/migration_test_sqlserver.rb
Lazy transactions changes required by https://github.com/rails/rails/pull/32647/
**Before**
https://travis-ci.org/github/rails-sqlserver/activerecord-sqlserver-adapter/jobs/680126303
```
6730 runs, 18723 assertions, 24 failures, 1 errors, 26 skips
```
**After**
https://travis-ci.org/github/rails-sqlserver/activerecord-sqlserver-adapter/jobs/680176451
```
6730 runs, 18725 assertions, 8 failures, 1 errors, 26 skips
```
> Rails 6: Support lazy transactions

- test/cases/coerced_tests.rb
Because tests automatically wrapped in transaction the transaction in the test become SavepointTransaction and SQL Server does not have `release_savepoint` query so the assert should be corrected to 1.
> Rails 6: Coerce test "an empty transaction does not raise if preventing writes"

- lib/active_record/connection_adapters/sqlserver/database_statements.rb
- lib/active_record/connection_adapters/sqlserver_adapter.rb
- test/cases/coerced_tests.rb
Bulk inserts akin to the bulk updates provided by `update_all` and bulk deletes by `delete_all` was added to Rails in https://github.com/rails/rails/pull/35077. 
Other adapters support skipping or upserting duplicates through the `ON CONFLICT` syntax for Postgres (9.5+) and Sqlite (3.24+) and `ON DUPLICATE KEY UPDATE` syntax for MySQL.
SQL Server, however, does not support skipping or upserting duplicates. There are some workarounds in https://michaeljswart.com/2017/07/sql-server-upsert-patterns-and-antipatterns/ but they will require more work to implement and test.
This PR implements the functionality to support insert returning. This will run the previous skipped tests such as https://github.com/rails/rails/blob/master/activerecord/test/cases/insert_all_test.rb#L75
I have coerced the …
> Rails 6: Updates for bulk insert/upsert

- lib/active_record/connection_adapters/sqlserver_adapter.rb
Similar to https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/pull/601
Adding in SQL Server 2017 support for the Rails 4.0 branch
>  Added 2017 to supported list for Rails 4.0

- test/cases/coerced_tests.rb
Original Rails test fails with SQL Server error message "The query processor ran out of internal resources and could not produce a query plan". This error goes away if you change database compatibility level to 110 (SQL 2012). However, you cannot change the compatibility level during a test. The purpose of the test is to ensure that the bind params are not used if they exceed the `bind_params_length` of the adapter. The coerced test still does this as there will be 32,768 remaining citation records in the database (65,536 - 32,768) and the `bind_params_length` of the SQL Server adapter is 2,098.
Rails PR: https://github.com/rails/rails/pull/33844
> Rails 6: Coerce eagerload too many IDs test

- test/cases/coerced_tests.rb
Workaround to fix the failing `LogSubscriberTest#test_vebose_query_logs` test on the CI by calling the original test from the coerced test.
The issue seems to be caused by the adapter installing Rails as a gem and the `ActiveSupport::BacktraceCleaner`, which cleans up backtraces and is used by `ActiveRecord::LogSubscriber`. It seems to be silencing calls from installed gems. 
References:
https://github.com/rails/rails/pull/33455
> Rails 6: Log subscriber workaround

- test/cases/coerced_tests.rb
Coerced the `ActiveRecord::PredicateBuilderTest` tests to include the `N` prefix that indicates unicode strings in SQL Server. 
Fixes the failing `ActiveRecord::PredicateBuilderTest#test_registering_new_handlers_for_association` test in https://travis-ci.org/github/rails-sqlserver/activerecord-sqlserver-adapter/jobs/684262341
> Rails 6: Fix coerced predicate builder tests

- test/cases/coerced_tests.rb
The test `ActiveRecordSchemaTest#test_has_primary_key` is randomly failing (see https://travis-ci.org/github/rails-sqlserver/activerecord-sqlserver-adapter/jobs/683462468). To recreate the issue checkout commit 66db048 and run test with command `SEED=7965 bundle exec rake test`.
The column information for the table must be already set from previous test sometimes.
> Rails 6: Workaround for randomly failing schema test

- test/cases/coerced_tests.rb
After Rails 6.0.3 the `ActiveRecord::ConnectionAdapters::ReaperTest#test_connection_pool_starts_reaper_in_fork` test is wrapped in `if Process.respond_to?(:fork)` so no need to coerce the test after that.
https://github.com/rails/rails/pull/37789
> Rails 6: Coerce reaper test using fork

- test/cases/coerced_tests.rb
There are tests randomly failing because table schema are being loaded during some tests. Changing `load_schema` calls to to `load_schema!` to see if that fixes them.
https://travis-ci.org/github/rails-sqlserver/activerecord-sqlserver-adapter/jobs/685740315
> Rails 6: Fix randomly failing tests due to schema load

- test/cases/coerced_tests.rb
Many of the tests in `test/cases/tasks/database_tasks_test.rb` are for PostgreSQL/SQLite/MySQL only. Coerced those tests and added equivalent tests for SQL Server.
See https://github.com/rails/rails/blob/v6.0.3/activerecord/test/cases/tasks/database_tasks_test.rb#L141
> Rails 6: Fix database tasks tests for SQL Server

- test/cases/coerced_tests.rb
The `FixturesTest#test_binary_in_fixtures` test fails on Windows because the binary file is not being read in binary format.
Opened Rails PR https://github.com/rails/rails/pull/39234 to fix the issue on Rails. Coercing the test on Windows until the issue is fixed.
> Rails 6: Skip binary fixtures test on Windows

- test/cases/coerced_tests.rb
The `ReloadModelsTest#test_has_one_with_reload` test fails on Windows because too many arguments are being passed to create the new subprocess (https://github.com/rails/rails/blob/v6.0.3/activesupport/lib/active_support/testing/isolation.rb#L93).
On the AppVeyor CI, when all tests are being run the test is calling `IO.popen` with 442 arguments (see https://ci.appveyor.com/project/wpolicarpo/activerecord-sqlserver-adapter/builds/32821521/job/e47ljgrcbpmmiuyf). Because of the number of arguments or the total length of the arguments a `Arg list too long - C:/Ruby25-x64/bin/ruby.exe (Errno::E2BIG)` exception is being thrown.
| Variable  | Number of arguments|
| ------------- | ------------- |
| load_path_args | 166  |
| $0 | 1  |
| ORIG_ARGV | 274 |
| test_opts | 1  |
If just the …
> Rails 6: Coerce ReloadModelsTest test on Windows

- lib/active_record/connection_adapters/sqlserver/schema_statements.rb
- lib/active_record/connection_adapters/sqlserver/table_definition.rb
- lib/active_record/connection_adapters/sqlserver/transaction.rb
- lib/active_record/connection_adapters/sqlserver/type/money.rb
- lib/active_record/connection_adapters/sqlserver/type/small_money.rb
- lib/active_record/connection_adapters/sqlserver/type/unicode_varchar.rb
- lib/active_record/connection_adapters/sqlserver/type/unicode_varchar_max.rb
- lib/active_record/connection_adapters/sqlserver/type/varbinary.rb
- lib/active_record/connection_adapters/sqlserver/type/varbinary_max.rb
- lib/active_record/connection_adapters/sqlserver/type/varchar.rb
- lib/active_record/connection_adapters/sqlserver/type/varchar_max.rb
Fix all ruby 2.7 kwargs warnings.
> Fix Ruby 2.7 kwargs warnings

- CHANGELOG.md
- lib/active_record/connection_adapters/sqlserver/database_limits.rb
- lib/active_record/connection_adapters/sqlserver/database_statements.rb
- lib/active_record/connection_adapters/sqlserver/database_tasks.rb
- lib/active_record/connection_adapters/sqlserver/errors.rb
- lib/active_record/connection_adapters/sqlserver/quoting.rb
- lib/active_record/connection_adapters/sqlserver/schema_creation.rb
- lib/active_record/connection_adapters/sqlserver/schema_dumper.rb
- lib/active_record/connection_adapters/sqlserver/schema_statements.rb
- lib/active_record/connection_adapters/sqlserver/showplan.rb
- lib/active_record/connection_adapters/sqlserver/sql_type_metadata.rb
- lib/active_record/connection_adapters/sqlserver/table_definition.rb
- lib/active_record/connection_adapters/sqlserver/transaction.rb
- lib/active_record/connection_adapters/sqlserver/type.rb
- lib/active_record/connection_adapters/sqlserver/utils.rb
- lib/active_record/connection_adapters/sqlserver/version.rb
- lib/active_record/connection_adapters/sqlserver_adapter.rb
- lib/active_record/connection_adapters/sqlserver_column.rb
- lib/active_record/sqlserver_base.rb
- lib/active_record/tasks/sqlserver_database_tasks.rb
- lib/activerecord-sqlserver-adapter.rb
- lib/arel/visitors/sqlserver.rb
- lib/arel_sqlserver.rb
This PR is enabling frozen strings in some areas of the code. I decided to break this task into smaller PRs to mitigate issues and to make it easier to find any breaking changes.
> Enable frozen strings - final

- lib/active_record/connection_adapters/sqlserver_adapter.rb
Hi there,  
We have connection issues in our production environment.  
It is supposed to be an easy fix but we cannot safely rescue the exception because it is billed as an `ActiveRecord::StatementInvalid` exception.
I add my exception translation where it is supposed to be. It is not feasible to emulate the same issue in tests so I simply don't add any test.
Hopes you guys could release a quick fix version soon.
> Translate the connection timed out error

- appveyor.yml
- lib/active_record/connection_adapters/sqlserver/database_statements.rb
Ruby 25 (https://ci.appveyor.com/project/wpolicarpo/activerecord-sqlserver-adapter/builds/32855936/job/6lxy5y73pv8d4h6y) and 26 (https://ci.appveyor.com/project/rails-sqlserver/activerecord-sqlserver-adapter/builds/32856253/job/aymtvlvjfb3c9qon) both fail with `File does not exist: tiny_tds/tiny_tds` error. Allow these CIs to fail. They can be added as issues to be fixed later.
Allowing Ruby 27 and 27-x64 to fail as they are not installed on the AppVeyor Windows instance. See https://ci.appveyor.com/project/wpolicarpo/activerecord-sqlserver-adapter/builds/32868782/job/vx7gopv5benhf8in
TinyTDS returns `false` instead of results if the database fails. Updated adapter to throw a `TinyTds::Error` if `false` returned by TinyTDS. This has resolved the `NoMethodError: undefined method do for …
> WIP: Rails 6: Handle false return by TinyTDS if connection fails and fixed CI

- lib/active_record/connection_adapters/sqlserver/schema_statements.rb
- lib/active_record/connection_adapters/sqlserver_adapter.rb
This is a change that is needed for the jdbc driver to work with this code so that the result has 2 columns in it. I have been working on the activerecord-jdbcmssql-adapter gem so that the jruby/jdbc specific differences can be maintained by that gem. I will cross link trackers as they are created. This will be needed in all the stable branches unless its already been fixed in future ones. I'm just starting with Rails 5.0 support so that's why I pointed the change at the 5-0-stable branch.
> Change to name the columns when querying for table info

- CHANGELOG.md
- lib/active_record/connection_adapters/sqlserver/database_statements.rb
TinyTDS returns false instead of raising an exception if connection fails while
executing a query.
Getting around this by raising an exception ourselves while this PR
https://github.com/rails-sqlserver/tiny_tds/pull/469 is not released.
The solution came from #717 and #818, I am just adjusting the error
message to make it the same as that TinyTDS PR.
> Adjust error message when connection is dead

- lib/active_record/connection_adapters/sqlserver/core_ext/attribute_methods.rb
- lib/active_record/connection_adapters/sqlserver/database_statements.rb
- lib/active_record/connection_adapters/sqlserver/errors.rb
- lib/active_record/tasks/sqlserver_database_tasks.rb
- lib/arel/visitors/sqlserver.rb
- test/cases/coerced_tests.rb
- test/cases/connection_test_sqlserver.rb
- test/cases/fetch_test_sqlserver.rb
- test/cases/schema_dumper_test_sqlserver.rb
- test/cases/showplan_test_sqlserver.rb
- test/cases/transaction_test_sqlserver.rb
Following #826, this PR enables `Layout/EmptyLines` cop and fixes all existing offenses.
> Rubocop: Enable Layout/EmptyLines cop

- lib/active_record/connection_adapters/sqlserver/schema_statements.rb
- lib/active_record/connection_adapters/sqlserver/type/datetime.rb
- lib/active_record/connection_adapters/sqlserver/type/time.rb
- test/cases/json_test_sqlserver.rb
- test/cases/migration_test_sqlserver.rb
- test/cases/pessimistic_locking_test_sqlserver.rb
- test/cases/schema_dumper_test_sqlserver.rb
Following #826, this PR enables `Layout/IndentationWidth` and `Layout/TrailingWhitespace` cops and fixes all existing offenses.
> Rubocop: Enable Layout/IndentationWidth and Layout/TrailingWhitespace cops

- Gemfile
- lib/active_record/connection_adapters/sqlserver/core_ext/calculations.rb
- lib/active_record/connection_adapters/sqlserver/database_statements.rb
- lib/active_record/connection_adapters/sqlserver/database_tasks.rb
- lib/active_record/connection_adapters/sqlserver/schema_statements.rb
- lib/active_record/connection_adapters/sqlserver/type/time_value_fractional.rb
- lib/active_record/connection_adapters/sqlserver/utils.rb
- lib/active_record/connection_adapters/sqlserver_adapter.rb
- lib/arel/visitors/sqlserver.rb
- test/cases/adapter_test_sqlserver.rb
- test/cases/coerced_tests.rb
- test/cases/column_test_sqlserver.rb
- test/cases/execute_procedure_test_sqlserver.rb
- test/cases/fetch_test_sqlserver.rb
- test/cases/migration_test_sqlserver.rb
- test/cases/schema_dumper_test_sqlserver.rb
- test/cases/schema_test_sqlserver.rb
- test/cases/specific_schema_test_sqlserver.rb
- test/cases/trigger_test_sqlserver.rb
- test/cases/utils_test_sqlserver.rb
- test/migrations/transaction_table/1_table_will_never_be_created.rb
- test/schema/sqlserver_specific_schema.rb
- test/support/rake_helpers.rb
Following #826, this PR enables the following cops and fixes all existing offenses:
- `Layout/ExtraSpacing`
- `Layout/SpaceBeforeFirstArg`
- `Layout/SpaceAfterComma`
- `Layout/SpaceBeforeSemicolon`
- `Layout/SpaceInsideBlockBraces`
- `Layout/SpaceBeforeBlockBraces`
- `Layout/SpaceAroundOperators`
- `Layout/SpaceAroundEqualsInParameterDefault`
- `Layout/SpaceBeforeComma`
- `Layout/SpaceInsideArrayLiteralBrackets`
- `Layout/SpaceAfterColon`
- `Layout/SpaceAroundBlockParameters`
- `Layout/SpaceInLambdaLiteral`
> Rubocop: Enable Spacing cops

- .rubocop.yml
- CHANGELOG.md
- Gemfile
Following #826, this PR enables the following cops and fixes all existing offenses:
- `Bundler/DuplicatedGem`
- `Bundler/OrderedGems`
> Rubocop: Enable Bundler cops

- activerecord-sqlserver-adapter.gemspec
- lib/active_record/connection_adapters/sqlserver/database_statements.rb
- lib/active_record/connection_adapters/sqlserver/database_tasks.rb
- lib/active_record/connection_adapters/sqlserver/quoting.rb
- lib/active_record/connection_adapters/sqlserver/schema_dumper.rb
- lib/active_record/connection_adapters/sqlserver/schema_statements.rb
- lib/active_record/connection_adapters/sqlserver/transaction.rb
- lib/active_record/connection_adapters/sqlserver/type/char.rb
- lib/active_record/connection_adapters/sqlserver/type/date.rb
- lib/active_record/connection_adapters/sqlserver/type/time.rb
- lib/active_record/connection_adapters/sqlserver/type/time_value_fractional.rb
- lib/active_record/connection_adapters/sqlserver/type/uuid.rb
- lib/active_record/connection_adapters/sqlserver/utils.rb
- lib/active_record/connection_adapters/sqlserver_adapter.rb
- lib/active_record/tasks/sqlserver_database_tasks.rb
- lib/arel/visitors/sqlserver.rb
- test/cases/adapter_test_sqlserver.rb
- test/cases/coerced_tests.rb
- test/cases/column_test_sqlserver.rb
- test/cases/fetch_test_sqlserver.rb
- test/cases/pessimistic_locking_test_sqlserver.rb
- test/cases/schema_dumper_test_sqlserver.rb
- test/cases/schema_test_sqlserver.rb
- test/cases/utils_test_sqlserver.rb
- test/schema/sqlserver_specific_schema.rb
- test/support/coerceable_test_sqlserver.rb
- test/support/connection_reflection.rb
- test/support/rake_helpers.rb
Following #826, this PR enables all `Layout/*` cops and fixes all existing offenses.
> Rubocop: Enable Layout/* cops

- CHANGELOG.md
- Gemfile
- lib/active_record/connection_adapters/sqlserver_adapter.rb
- lib/arel/visitors/sqlserver.rb
- test/cases/coerced_tests.rb
- test/cases/specific_schema_test_sqlserver.rb
- test/cases/transaction_test_sqlserver.rb
Following #826, this PR enables `Lint/UselessAssignment` cop and fixes all existing offenses.
> Rubocop: Enable Lint/UselessAssignment cop

- .rubocop.yml
- CHANGELOG.md
- lib/active_record/connection_adapters/sqlserver/utils.rb
- lib/active_record/tasks/sqlserver_database_tasks.rb
- test/cases/column_test_sqlserver.rb
Following #826, this PR configures `Naming/*` cops and fixes all existing offenses.
- `Naming/MethodParameterName`
- `Naming/MethodName`
- `Naming/AccessorMethodName`
- `Naming/PredicateName`
- `Naming/BinaryOperatorParameterName`
- `Naming/FileName`
- `Naming/RescuedExceptionsVariableName`
- `Naming/VariableNumber`
> Rubocop: Configure Naming cops

- lib/active_record/connection_adapters/sqlserver/schema_statements.rb
I faced with errors while "rake db:schema:dump" on existing database.
This caused code do not match column object by name. Then null caused silent exceptions.
And schema had no dump for tables where primary keys where mixed case.
> Primary key should be lowercase if schema forced to lowercase

- lib/active_record/connection_adapters/sqlserver/schema_statements.rb
- test/cases/schema_dumper_test_sqlserver.rb
- test/schema/sqlserver_specific_schema.rb
Fixes #850 
Upon investigation into this query, I discovered that the new query is looking at the table `sys.key_constraints` which includes both primary keys as well as unique constraints, which is not what we want. 
Originally, I tried adding this check to the `where` clause, but my schema dump was missing any table without a primary key. After adding this to the join, I was able to successfully dump my schema, build a test database, and run my specs successfully against the new test database. 
CC @wpolicarpo
> Updated 'column_definitions_sql' to ensure that only primary key key constraints are queried for

- CHANGELOG.md
- README.md
- lib/active_record/connection_adapters/sqlserver/schema_statements.rb
- test/cases/migration_test_sqlserver.rb
The native PostgreSQLAdapter from rails implement the following functions:
[create_schema](https://apidock.com/rails/ActiveRecord/ConnectionAdapters/PostgreSQLAdapter/SchemaStatements/create_schema)
[drop_schema](https://apidock.com/rails/v4.1.8/ActiveRecord/ConnectionAdapters/PostgreSQLAdapter/SchemaStatements/drop_schema)
So this PR aims to provide a similar interface to work with MSSQL schemas. Besides these two functions, I also created another one:
`alter_schema`
It can be useful to transfer a table from a schema to another. Read [more](https://docs.microsoft.com/en-us/sql/t-sql/statements/alter-schema-transact-sql?view=sql-server-ver15)
> feat: add helpers to create/alter/drop a schema

- CHANGELOG.md
- lib/active_record/connection_adapters/sqlserver/quoting.rb
- test/cases/coerced_tests.rb
Updated the column name matchers to accept database and owner names. If you are working with multiple databases on the same SQL Server DBMS then you could have fully expanded column names that look like `[TestDB].[dbo].[Planets].[name]`. Currently this column name would not be accepted as the `[TestDB].[dbo]` section of the column name is not handled by the current regex.
> Updated the column name matchers to accept database and owner names

- CHANGELOG.md
- lib/active_record/connection_adapters/sqlserver/schema_statements.rb
- test/cases/adapter_test_sqlserver.rb
If a database connection can access multiple database schemas then it should be able to check for table existence across those schemas.
> Allow table existence to be tested across database schemas

- CHANGELOG.md
- lib/active_record/connection_adapters/sqlserver_adapter.rb
- lib/arel/visitors/sqlserver.rb
- test/cases/coerced_tests.rb
- test/cases/optimizer_hints_test_sqlserver.rb
This PR resolves #856. As the issue suggests, optimizer_hints just deals with [query hints](https://docs.microsoft.com/en-us/sql/t-sql/queries/hints-transact-sql-query?view=sql-server-ver15)
Inspired by the Mysql & Postgres adapters, the following are equivalent: 
```
Model.optimizer_hints("OPTION (MAXDOP 2, FAST 1)")
Model.optimizer_hints("MAXDOP 2, FAST 1")
Model.optimizer_hints("MAXDOP 2", "FAST 1")
```
> Implement optimizer_hints using OPTION clause

- CHANGELOG.md
- lib/active_record/connection_adapters/sqlserver/type.rb
- lib/active_record/connection_adapters/sqlserver/type/decimal_without_scale.rb
- lib/active_record/connection_adapters/sqlserver_adapter.rb
- test/cases/coerced_tests.rb
- test/cases/column_test_sqlserver.rb
- test/cases/schema_dumper_test_sqlserver.rb
Added the DecimalWithoutScale data type so that `MigrationTest#test_add_table_with_decimals` no longer needs to be coerced. This matches how the `ActiveRecord::ConnectionAdapters::AbstractAdapter` works (see https://github.com/rails/rails/blob/3dd0af563b5ebdccf1e3c1993f8a64f4ab5fce48/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb#L664). 
Without this change it would be necessary to run different tests based on whether you were running Ruby 3+ (see https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/pull/868).
> Added DecimalWithoutScale type

- lib/active_record/connection_adapters/sqlserver/core_ext/calculations.rb
- lib/active_record/connection_adapters/sqlserver/schema_creation.rb
- lib/active_record/connection_adapters/sqlserver/transaction.rb
Adds Rails 6.1 support.
Changes:
- use `ActiveRecord::ConnectionAdapters::SchemaCreation` instead of `ActiveRecord::ConnectionAdapters::AbstractAdapter::SchemaCreation`
- accept 2 arguments in `SQLServerRealTransaction#initialize` instead of 3
I don't know if that's all, but basic testing didn't reveal other issues.
> Rails 6.1 support

- lib/active_record/connection_adapters/sqlserver/database_statements.rb
- lib/active_record/connection_adapters/sqlserver/schema_creation.rb
- lib/active_record/connection_adapters/sqlserver/schema_statements.rb
- lib/active_record/connection_adapters/sqlserver/transaction.rb
- test/support/sql_counter_sqlserver.rb
PR contains various fixes to get the tests running for Rails 6.1
Changes were:
- SQL Server doesn't support USING for schema creation (similar to SQLite3). See https://github.com/rails/rails/pull/39203/files#diff-414d80c69e0a30eb66d50bc71af4e80ceee02b666003e7a99a65f1c79a778c98R94
- The `ActiveRecord::SQLCounter` class used during testing no longer contains the `ignore` instance variable. Instead transaction SQL statements are ignored by labelling them as "TRANSACTION". See https://github.com/rails/rails/commit/6a32e8aa72ebcbd587d7845cf354724bf2fffd7b
- Fixed the constructor for `SQLServerRealTransaction`. Fix was taken from https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/pull/854/files#diff-d69f853a7b57d86a23028bef9f0a175de5c134adfb6c389f83782b3f29a82211R35
- Fixed the …
> Various fixes to get the tests running for Rails 6.1

- lib/active_record/connection_adapters/sqlserver/quoting.rb
- lib/active_record/connection_adapters/sqlserver/sql_type_metadata.rb
Updated `ActiveRecord::ConnectionAdapters::SQLServer::SqlTypeMetadata` to handle the schema cache deduplicateion introduced in https://github.com/rails/rails/pull/35891
The changes follow the same format used for the MySQL and PostgreSQL adapters.
**CI on Ruby 3.0.1 before PR**
https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/runs/2337409595
7133 runs, 7930 assertions, 47 failures, 3697 errors, 33 skips
**CI on Ruby 3.0.1 after PR**
https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/runs/2337409595
7133 runs, 9936 assertions, 41 failures, 2955 errors, 33 skips
> Deduplicate schema cache structures

- CHANGELOG.md
Updated the changelog to include:
- https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/pull/873
- https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/pull/874
> Added missing changelogs

- CHANGELOG.md
- lib/active_record/connection_adapters/sqlserver/schema_statements.rb
Use native `String#end_with`. 
https://pipelines.actions.githubusercontent.com/OGQvFf2eDbGUprKdJ5qsq3TsAFLfKWDWAJCyTHn8ess0fbvp0X/_apis/pipelines/1/runs/53/signedlogcontent/5?urlExpires=2021-04-14T12%3A49%3A18.6442657Z&urlSigningMethod=HMACV1&urlSignature=Nj9xc83Vha%2BjgCoMNWk1PA2oxHAYlZxKZ6XEZZ%2FmdlI%3D
```
2021-04-14T11:16:33.3266361Z ActiveRecord::Migration::ReferencesForeignKeyTest#test_0006_foreign key column can be removed:
2021-04-14T11:16:33.3268084Z NoMethodError: undefined method `ends_with?' for "testing_parent_id":String
2021-04-14T11:16:33.3268734Z Did you mean?  end_with?
```
> Use native String#end_with

- CHANGELOG.md
- lib/active_record/connection_adapters/sqlserver_column.rb
Fixed the "bit" type column error `NoMethodError: undefined method '-@' for true:TrueClass`.
Issue was that the default value for a column in the SQL Server adapter can be true/false. However, the true/false classes do not implement the '-@' method to return a frozen version of the value. However, since true/false are already frozen there is no need to call the `-@` method anyway. 
```
irb(main):0> 'test'.frozen?
=> false
irb(main):0> (-'test').frozen?
=> true
irb(main):0> -false
NoMethodError (undefined method `-@' for false:FalseClass)
irb(main):0> -true
NoMethodError (undefined method `-@' for true:TrueClass)
irb(main):0> false.frozen?
=> true
irb(main):0> true.frozen?
=> true
```
**Tests Before**
https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/runs/2342106156
7133 …
> Handle default boolean column values when deduplicating

- CHANGELOG.md
- lib/arel/visitors/sqlserver.rb
Added visit method for the new Arel node type `HomogenousIn` used when the values are all homogenous (see https://github.com/rails/rails/pull/39009).
This change means we don't need to fallback to an old version of `ArrayHandler` as proposed in https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/pull/861
Also, cleaned up some method signatures.
**Before**
https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/runs/2343775735
7133 runs, 16254 assertions, 37 failures, 805 errors, 37 skips
**After**
https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/pull/879/checks?check_run_id=2351710950
7133 runs, 18457 assertions, 25 failures, 145 errors, 37 skips
> Added visit method for HomogeneousIn Arel type

- CHANGELOG.md
- lib/active_record/connection_adapters/sqlserver_column.rb
Previously in https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/pull/875 the column deduplication method was updated to handle default boolean values. The change did not handle other non-string classes such as Time/Date/Integer/etc. This is the cause of the `NoMethodError: undefined method '-@'` errors in the main CI build:
https://pipelines.actions.githubusercontent.com/OGQvFf2eDbGUprKdJ5qsq3TsAFLfKWDWAJCyTHn8ess0fbvp0X/_apis/pipelines/1/runs/67/signedlogcontent/6?urlExpires=2021-04-15T12%3A48%3A19.5876504Z&urlSigningMethod=HMACV1&urlSignature=BboOo2lvNJlxvLAzbOHeep1jlPH%2FtSuW75%2BiBiJvq1s%3D
Updated the `ActiveRecord::ConnectionAdapters::SQLServerColumn#deduplicated` method to create a frozen copy of any object that is not a String.
**Before** …
> Handle any default column class when deduplicating

- lib/active_record/tasks/sqlserver_database_tasks.rb
This PR expands on #854.
In addition to #854, it fixes a problem with `rake db:create` failing to run, as well as fixes queries on arrays throwing.
As a happy accident, this also fixes #841
> Fix Rails 6.1 database config

- test/cases/coerced_tests.rb
- test/cases/rake_test_sqlserver.rb
This PR contains two fixes:
1. ARTest.connfiguration_config was renamed (see https://github.com/rails/rails/pull/38007)
2. Rewrite `UnsafeRawSqlTest` coerced tests because unsafe raw SQL support was removed (see https://github.com/rails/rails/commit/317465a4a8f8c0ebaf9534921350c4540584c03c)
> Rails 6.1 fixes: Use renamed connection_config method and rewrite coerced tests using unsafe raw SQL

- lib/active_record/connection_adapters/sqlserver/schema_statements.rb
- test/cases/adapter_test_sqlserver.rb
- test/cases/coerced_tests.rb
This PR deals with 4 deprecation warnings by looking at the deprecation commit and applying a similar update.
1. `allowed_index_name_length is deprecated and will be removed from Rails 6.2` (source https://github.com/rails/rails/commit/ab2d859e6c5430326a22a1328cc296c8cbae8727)
2. `[] is deprecated and will be removed from Rails 6.2 (Use configs_for)` (source https://github.com/rails/rails/commit/2a53fe638de2c485c2655b6b7236ec1ab7dca5ad)
3. `Passing an Active Record object to directly is deprecated and will be no longer quoted as id value in Rails 6.2` (source https://github.com/rails/rails/commit/87886c93dc22d528d8529d8b63873f699beaf695)
4. `.reorder(nil) with .first / .first! no longer takes non-deterministic result in Rails 6.2. To continue taking non-deterministic result, use / …
> Rails 6.1: remove deprecation warnings

- CHANGELOG.md
- lib/active_record/connection_adapters/sqlserver/quoting.rb
PR fixes the `TypeError: can't quote ActiveRecord::Relation::QueryAttribute` errors in the tests. 
This is an alternative fix to https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/pull/883
> Rails 6.1: Fix the quoting of ActiveModel attributes

- CHANGELOG.md
- lib/active_record/connection_adapters/sqlserver/schema_creation.rb
- lib/active_record/connection_adapters/sqlserver/schema_dumper.rb
- lib/active_record/connection_adapters/sqlserver/schema_statements.rb
- test/cases/change_column_collation_test_sqlserver.rb
- test/cases/migration_test_sqlserver.rb
- test/cases/schema_dumper_test_sqlserver.rb
- test/migrations/create_clients_and_change_column_collation.rb
- test/models/sqlserver/sst_string_collation.rb
- test/schema/sqlserver_specific_schema.rb
This PR address https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/issues/848. 
It also adds support to change collation `change_column :customers, :name, collation: :xxx`. Before this change, collation changes were skipped/ignored.
> Dump column collation to schema.rb and allow collation changes using column_change

- test/cases/adapter_test_sqlserver.rb
- test/cases/coerced_tests.rb
This PR contains two fixes:
1. use `db_config` to access connection_pool database configuration. Pool is not instantiated with ConnectionSpecification anymore (see https://github.com/rails/rails/commit/48c716bbfa971668cedd0fffa874459044459ea1#diff-642b90553b888bd2c724c093a1a685a5408a7d8293f3751366c25dc548936eb7)
2. coerce some bind_params tests. We include 'EXEC sp_executesql' on prepared statements
> Rails 6.1 fixes: coerce bind param test and fix pool spec access

- test/cases/coerced_tests.rb
Coerced some failing `FinderTest` tests that were checking for `LIMIT` in the generated SQL. The SQL Server adapter uses `FETCH NEXT x ROWS ONLY` instead of `LIMIT`.
**Before**
https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/runs/2382157889
7130 runs, 20222 assertions, 28 failures, 33 errors, 36 skips
**After**
https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/pull/886/checks?check_run_id=2381988705
7125 runs, 20207 assertions, 22 failures, 36 errors, 37 skips
> Rails 6.1: Coerce tests that check for LIMIT in SQL

- test/cases/coerced_tests.rb
Removed tests that no longer need to be coerced.
> Rails 6.1: Removed tests that no longer need to be coerced

- CHANGELOG.md
- lib/active_record/connection_adapters/sqlserver/quoting.rb
Reverting https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/pull/885 in favour of https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/pull/883
> Revert "Rails 6.1: Fix the quoting of ActiveModel attributes"

- CHANGELOG.md
- lib/active_record/connection_adapters/sqlserver/schema_statements.rb
See
https://github.com/rails/rails/commit/95ed7e7809a9f5939ffb8dc9232e7739c39d9778
> Rails 6.1: Add support for `if_exists` on `remove_column`

- test/cases/coerced_tests.rb
Remove the coercing of the `ActiveRecord::AdapterTest#test_insert_update_delete_with_legacy_binds` test that is no longer in the Rails test suite.
This was missed in https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/pull/887
> Rails 6.1: Remove coerced test no longer in Rails test suite

- test/cases/coerced_tests.rb
Need to coerce the Rails annotation tests as they assume the generated SQL starts with `SELECT` but the SQL Server adapter queries start with `EXEC sp_executesql N'SELECT`.
Example:
```sql
EXEC sp_executesql N'SELECT [posts].[id] FROM [posts] /* foo */ ORDER BY [posts].[id] ASC OFFSET 0 ROWS FETCH NEXT @0 ROWS ONLY', N'@0 int', @0 = 1
```
> Rails 6.1: Coerce annotation tests

- lib/active_record/connection_adapters/sqlserver/database_statements.rb
- test/cases/execute_procedure_test_sqlserver.rb
Fixed the `Expected a deprecation warning within the block but received none` errors in the following tests:
- ConcurrentTransactionTest#test_deprecation_on_ruby_timeout
- ConcurrentTransactionTest#test_successful_with_return 
- TransactionTest#test_deprecation_on_ruby_timeout
- TransactionTest#test_successful_with_return
The tests were failing because of the changes made in https://github.com/rails/rails/pull/39453
> Rails 6.1: Mark transaction as written if non-read SQL performed

- CHANGELOG.md
- lib/active_record/connection_adapters/sqlserver/core_ext/explain.rb
- lib/arel/visitors/sqlserver.rb
There are some test failing due to `TypeError: can't quote ActiveRecord::Relation::QueryAttribute`.
I found two places where this was happening:
1. `visit_Arel_Nodes_HomogeneousIn` is binding `ActiveRecord::Relation::QueryAttribute` even for unprepared statements (.i.e `Post.where(author: [1, 2]).to_sql`). Unprepared statement uses [`Arel::Collectors::SubstituteBinds`](https://github.com/rails/rails/blob/v6.1.0/activerecord/lib/arel/collectors/substitute_binds.rb) which quote the binded value (see [abstract_adapter](https://github.com/rails/rails/blob/v6.1.0/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb#L729) to confirm what I'm saying)
2. explain receives instances of `::ActiveModel::Attribute` (not only by `visit_Arel_Nodes_HomogeneousIn` hack).
> Rails 6.1: Fix 'TypeError: can't quote ActiveRecord::Relation::QueryAttribute'

- test/cases/adapter_test_sqlserver.rb
- test/cases/coerced_tests.rb
In Rails 6.1 while_preventing_writes moved to be called on Base since we no longer have multiple connection_handlers. See https://github.com/rails/rails/pull/40489
**Before**
https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/runs/2384484016?check_suite_focus=true
7137 runs, 20305 assertions, 18 failures, 18 errors, 36 skips
**After**
https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/runs/2384587422?check_suite_focus=true
7137 runs, 20302 assertions, 15 failures, 16 errors, 36 skips
> Rails 6.1: Fixes related to `while_preventing_writes`

- lib/active_record/connection_adapters/sqlserver/database_limits.rb
Remove deprecated `in_clause_length` method, which fixes:
https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/runs/2391966961#step:4:830
```
ActiveRecord::AdapterTest#test_in_clause_length_is_deprecated [/usr/local/bundle/bundler/gems/rails-8b63ea762239/activerecord/test/cases/adapter_test.rb:341]:
Expected a deprecation warning within the block but received none
```
**Before**
https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/runs/2391966961
7138 runs, 20328 assertions, 10 failures, 10 errors, 36 skips
**After**
https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/pull/900/checks?check_run_id=2392463332
7138 runs, 20350 assertions, 8 failures, 10 errors, 36 skips
> Rails 6.1: Removed deprecated in_clause_length method

- lib/active_record/tasks/sqlserver_database_tasks.rb
- test/cases/rake_test_sqlserver.rb
Two changes:
1. `configuration_hash` keys are symbols, not strings.
2. `ActiveRecord::Tasks::DatabaseTasks.load_schema` requires a `ActiveRecord::DatabaseConfigurations::HashConfig` instance
> Rails 6.1: fix rake task

- test/cases/coerced_tests.rb
PR fixes the following failures:
```
BasePreventWritesTest::BasePreventWritesLegacyTest#test_0006_an empty transaction does not raise if preventing writes [/usr/local/bundle/bundler/gems/rails-8b63ea762239/activerecord/test/cases/base_prevent_writes_test.rb:164]:
1 instead of 2 queries were executed.
```
```
BasePreventWritesTest#test_0006_an empty transaction does not raise if preventing writes [/usr/local/bundle/bundler/gems/rails-8b63ea762239/activerecord/test/cases/base_prevent_writes_test.rb:61]:
1 instead of 2 queries were executed.
```
```
ActiveRecord::AdapterPreventWritesLegacyTest#test_errors_when_an_insert_query_is_called_while_preventing_writes [/usr/local/bundle/bundler/gems/rails-8b63ea762239/activerecord/test/cases/adapter_prevent_writes_test.rb:181]:
6 instead of 0 queries …
```
> Rails 6.1: coerce tests when we produce more or less queries

- test/cases/coerced_tests.rb
Coercing the `FinderTest#test_include_on_unloaded_relation_with_having_referencing_aliased_select` test as SQL Server does not support the SQL.
There is no point re-implementing the coerced test as its purpose is to test the HAVING clause referencing an aliased SELECT.
**SQL Server**
```ruby
Author.select("COUNT(*) as total_posts", "authors.*").joins(:posts).group(:id).having("total_posts > 2").include?(bob)
```
SQL generated:
```sql
SELECT COUNT(*) as total_posts, authors.*
FROM [authors] 
INNER JOIN [posts] ON [posts].[author_id] = [authors].[id] 
GROUP BY [authors].[id] 
HAVING (total_posts > 2)
```
This SQL is invalid in SQL Server and throws the error `Invalid column name 'total_posts'`. There are 2 reasons why the SQL is invalid:
- Cannot use SELECT alias `total_posts` in HAVING …
> Rails 6.1: Coerce test as SQL is invalid for MSSQL

- test/cases/coerced_tests.rb
Added comments to remove some coerced tests after Rails 7 released.
See https://github.com/rails/rails/pull/42027
> Remove annotate coerced tests after Rails 7

- test/cases/coerced_tests.rb
Split https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/pull/902 into two separate PR.
PR fixes:
```
RelationMergingTest#test_merge_doesnt_duplicate_same_clauses [/usr/local/bundle/bundler/gems/rails-8b63ea762239/activerecord/test/cases/relation/merging_test.rb:202]:
Query pattern(s) /WHERE \[authors\]\.\[id\] NOT IN \((\?|\W?\w?\d), \g<1>\)\z/ not found.
```
> Rails 6.1: coerce test to match binding syntax

- test/cases/coerced_tests.rb
The CI has failing test `EagerLoadingTooManyIdsTest#test_eager_loading_too_many_ids`. 
This test was originally called `test_eager_loading_too_may_ids`, which contains a typo. The typo was fixed in https://github.com/rails/rails/commit/60ff119487cab05e2cbcd6656a0106481975f23e
Instead of removing `test_eager_loading_too_may_ids` in https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/pull/887/files#diff-3f00d8ac91cdd36f48a1f18eb12bf3dc8d3cb7e48f7d21fc891ea63dfb6fd9ecL1460 the test should have been renamed. 
This PR just adds back in the coerce and renames the test.
> Rails 6.1: Added coerced test was removed by mistake

- test/cases/coerced_tests.rb
Noticed that the `BasePreventWritesTest::BasePreventWritesLegacyTest#test_0006_an empty transaction does not raise if preventing writes` test is still failing (see https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/runs/2409001850) even though it was being coerced in https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/pull/901
The issue is that the coerce is for the `BasePreventWritesLegacyTest` class not the `BasePreventWritesTest::BasePreventWritesLegacyTest` class (https://github.com/rails/rails/blob/738ca3595fb88580a84072b31ce8a999af4762d6/activerecord/test/cases/base_prevent_writes_test.rb#L98).
This PR just moves the class into the correct namespace.
> Rails 6.1: Fixed the namespace of the BasePreventWritesLegacyTest class

- test/cases/coerced_tests.rb
This PR fixes the following failing CI tests:
- CalculationsTest#test_select_avg_with_group_by_as_virtual_attribute_with_ar
- CalculationsTest#test_select_avg_with_joins_and_group_by_as_virtual_attribute_with_ar
- CalculationsTest#test_select_avg_with_group_by_as_virtual_attribute_with_sql
- CalculationsTest#test_select_avg_with_joins_and_group_by_as_virtual_attribute_with_sql
The tests needed to be coerced and re-implemented for the following reasons:
**AVG() function**
In SQL Server the `AVG()` function for a list of integers returns an integer. For other databases it would return a decimal. To get SQL Server to return a decimal result the values need to be casted before averaging.  so need to cast values as decimals before averaging. So instead of `AVG(credit_limit) AS …
> Rails 6.1: Fix failing calculation tests

- test/cases/coerced_tests.rb
The `UniquenessValidationTest#test_validate_uniqueness_by_default_database_collation` test only assumed case insensitive collation for MySQL (see https://github.com/rails/rails/blob/0beae875eea321143ec4208df93e43fa3ebf39be/activerecord/test/cases/validations/uniqueness_validation_test.rb#L349). By default, the SQL Server tests also use a case-insensitive collation. In this MR I have coerced the Rails suite test and added a slightly different test for SQL Server.
Previously this test was called `test_validate_case_sensitive_uniqueness_by_default` and was renamed to `test_validate_uniqueness_by_default_database_collation` in https://github.com/rails/rails/commit/3daf2c7b2df8014c928f5640376550191ab712b7. We used to coerce `test_validate_case_sensitive_uniqueness_by_default` but that coercion …
> Rails 6.1: Coerce test to handle default case-insensitive collation

- test/cases/coerced_tests.rb
The legacy binding tests, which we used to coerced, were renamed in the Rails test suite in https://github.com/rails/rails/commit/92360e9ea3674c153adf2fa4c2cdcb6d9afd730b
Legacy binds are not supported by the SQL Server adapter and since Rails are deprecating them there will be no need to support them in future.
Instead of renaming the coerced tests we removed the coercions in the following PRs:
- https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/pull/887
- https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/pull/895
This PR just coerces the tests with their new names.
> Rails 6.1: Legacy binds are not supported

- test/cases/coerced_tests.rb
Fix some randomly failing tests. The tests fail because the table schema is sometimes queried for if the schema is not already loaded. The tests rely on the number of queries being performed and so the schema loading queries throw off the tests.
Example of `ActiveRecord::AdapterPreventWritesLegacyTest#test_errors_when_an_insert_query_prefixed_by_a_double_dash_comment_is_called_while_preventing_writes` failing:
https://pipelines.actions.githubusercontent.com/OGQvFf2eDbGUprKdJ5qsq3TsAFLfKWDWAJCyTHn8ess0fbvp0X/_apis/pipelines/1/runs/172/signedlogcontent/6?urlExpires=2021-04-22T14%3A43%3A54.2983268Z&urlSigningMethod=HMACV1&urlSignature=1puWUyN%2Fxlx7jqGDOQjHpgDOQG9SfPBtfCS4J4WdB6I%3D
Example of `ActiveRecord::AdapterPreventWritesTest#test_errors_when_an_insert_query_prefixed_by_a_double_dash_c …
> Rails 6.1: Fix randomly failing prevent writes test

- test/cases/coerced_tests.rb
This PR fixes: 
```
ActiveRecord::ConnectionAdapters::SchemaCacheTest#test_marshal_dump_and_load_via_disk:
ArgumentError: year too big to marshal: 1753 UTC
```
```
ActiveRecord::ConnectionAdapters::SchemaCacheTest#test_marshal_dump_and_load_with_gzip:
ArgumentError: year too big to marshal: 1753 UTC
```
Those errors only exists in [ruby 2.5](https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/runs/2411021223?check_suite_focus=true#step:4:187) and [2.6](https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/runs/2411021223?check_suite_focus=true#step:4:187) runs
**Context**
Rails 6.1 adds support for marshal as a schema cache serialization strategy (https://github.com/rails/rails/commit/9a356fcd4223c1b6bbd83445cc95c402ce49844a)
Ruby 2.5 and Ruby 2.6 have a bug that …
> Rails 6.1: Coerce schema cache test to handle Time marshal in ruby 2.5 and 2.6

- CHANGELOG.md
- lib/active_record/connection_adapters/sqlserver_adapter.rb
- lib/active_record/sqlserver_base.rb
Refactored the connection code to use `.new_client` as suggested in https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/pull/903#discussion_r617639344 This PR follows the same general patterns as used by the MySQL and PostgreSQL adapters.
References:
- MySQL: https://github.com/rails/rails/blob/0184a019353fa862c37ae61308e62e4e702c347f/activerecord/lib/active_record/connection_adapters/mysql2_adapter.rb#L23
- PostgreSQL: https://github.com/rails/rails/blob/0184a019353fa862c37ae61308e62e4e702c347f/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb#L37
> Rails 6.1: Refactored to use new_client connection pattern

- CHANGELOG.md
- lib/active_record/connection_adapters/sqlserver/database_limits.rb
- lib/active_record/connection_adapters/sqlserver/database_statements.rb
- lib/active_record/connection_adapters/sqlserver_adapter.rb
- test/cases/disconnected_test_sqlserver.rb
This PR fixes the failure:
```
TestDisconnectedAdapter#test_0001_can't execute statements while disconnected [/usr/local/bundle/bundler/gems/rails-8b63ea762239/activerecord/test/cases/disconnected_test.rb:25]:
[ActiveRecord::ConnectionNotEstablished] exception expected, not
Class: <ActiveRecord::StatementInvalid>
Message: <"NoMethodError: undefined method `execute' for nil:NilClass\nDid you mean?  expects">
```
Rails 6.1 expects that we raise an instance of `ActiveRecord::ConnectionNotEstablished` (see https://github.com/rails/rails/blob/v6.1.0/activerecord/test/cases/disconnected_test.rb).
Rails 6.0 was expecting `ActiveRecord::StatementInvalid`. In fact, 6-0-stable raises that exception with the message: 
```
"NoMethodError: undefined method `execute' for nil:NilClass\nDid you mean? …
```
> Rails 6.1: Raise `ActiveRecord::ConnectionNotEstablished` on calls to execute with a disconnected connection.

- test/cases/coerced_tests.rb
Prevent the `ActiveRecord::AdapterPreventWritesLegacyTest#test_errors_when_an_insert_query_is_called_while_preventing_writes` test from failing randomly. 
This test randomly failed today in CI run https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/runs/2456380041
> Rails 6: Prevent randomly failing test

- lib/active_record/connection_adapters/sqlserver/schema_dumper.rb
- lib/active_record/connection_adapters/sqlserver/schema_statements.rb
- lib/active_record/connection_adapters/sqlserver/table_definition.rb
- test/cases/coerced_tests.rb
- test/cases/primary_keys_test_sqlserver.rb
PR fixes:
```
PrimaryKeyAnyTypeTest#test_0001_schema dump primary key includes type and options [/usr/local/bundle/bundler/gems/rails-8b63ea762239/activerecord/test/cases/primary_keys_test.rb:315]:
Expected /create_table "barcodes", primary_key: "code", id: { type: :string, limit: 42 }/ to match "....ActiveRecord::Schema.define(version: 0) do\n\n  create_table \"barcodes\", primary_key: \"code\", id: { type: :string, limit: 42, default: nil }, force: :cascade do |t|\n  end\n\nend\n"
```
> Rails 6.1: change schema dumper condition to only dump explicit default for non identity integers

- test/cases/coerced_tests.rb
Coerced and re-implemented the `ActiveRecord::RelationTest#test_marshal_load_legacy_relation` test as the original Rails test was not reading the dump file in binary mode and so wasn't passing on Windows environments.
The coerce can be removed on Rails 7+ as the test was removed in https://github.com/rails/rails/commit/0e35e670b2aa7e704e4eac999d71be3cb1f914b3#diff-744b39fde5c3433ab31f1fe1721fde897ebde5c0abb5a09e6752a1479ac42668
> Rails 6.1: Read file in binary mode to support the Windows CI

- test/cases/coerced_tests.rb
Coercing tests on Windows that rely on `SchemaCache#dump_to`. The call in https://github.com/rails/rails/blob/e2781c2d93808031fbc4dbecaa7aac59aa90b4b8/activesupport/lib/active_support/core_ext/file/atomic.rb#L50 to rename the file fails on Windows. This is a Rails/Windows issue. 
**MacOS**
```
> tempfile = Tempfile.new('test.txt')
=> #<File:/var/folders/mp/_9w8583s18z93h_w2s7zxq24ks97j0/T/test.txt20210429-16257-39oo5i>
> File.atomic_write(tempfile.path) { |file| file.write('BLAH') }
=> 4
```
**Windows** 
```
> tempfile = Tempfile.new('test.txt')
=> #<Tempfile:C:/Users/user/AppData/Local/Temp/test.txt20210429-8740-1pwkymo>
> File.atomic_write(tempfile.path) { |file| file.write('BLAH') }
*** Errno::EACCES Exception: Permission denied @ rb_file_s_rename - …
```
> Rails 6.1: Skip tests on Windows because of atomic write issue

- test/cases/coerced_tests.rb
Coerce the following tests on Window AppVeyor CI:
- MigratorTest#test_migrator_db_has_no_schema_migrations_table
- MultiDbMigratorTest#test_migrator_db_has_no_schema_migrations_table
I have run the tests on a local Windows installation and the tests pass. So I think the issue is with the Windows AppVeyor VM.
> Rails 6.1: Coerce failing migrator tests on Window AppVeyor CI

- test/cases/coerced_tests.rb
Coerce and re-implement the Rails 6.1.4 `LogSubscriberTest#test_where_in_binds_logging_include_attribute_names` test so that the adapter now passes for Rails 6.1.4.
Also, some CI tests started failing because records created during the test prevented the index from being added back. This issue does not happen locally. To fix the issue I delete the records created during the original test before adding the index back. This change does not affect the purpose of the test.
> Fix tests for Rails 6.1.4

- CHANGELOG.md
- lib/active_record/connection_adapters/sqlserver/core_ext/attribute_methods.rb
- lib/active_record/connection_adapters/sqlserver/core_ext/calculations.rb
- lib/active_record/connection_adapters/sqlserver/core_ext/explain.rb
- lib/active_record/connection_adapters/sqlserver/core_ext/finder_methods.rb
- lib/active_record/connection_adapters/sqlserver/core_ext/preloader.rb
Recent versions of Rails support multiple database connections within the same app. It is possible for these connections to use different adapters. For example, one adapter may use SQL Server, and another uses PostgreSQL.
This gem applies some monkey patches to ActiveRecord for SQL Server compatibility. These patches could break other adapters, though, in a multiple-database scenario.
This PR modifies the patches so that they are applied only if the connection is SQL Server. If not, the original ActiveRecord implementation (`super`) is used instead.
Fixes #929
@aidanharan @wpolicarpo what do you think of this approach? Any suggestions on how to test?
> Apply monkey patches for SQL Server connections only

- lib/active_record/connection_adapters/sqlserver/core_ext/calculations.rb
Another gem (groupdate: https://github.com/ankane/groupdate by @ankane) also patches the `ActiveRecord::Relation#calculate` method and breaks when used with this library. Prepending this `Calculations` module prevents any other libraries from patching this method, and it looks like an `include` will have the same desired effect to patch existing out-of-the-box ActiveRecord code. I'm not sure if this is prepended to ensure nothing else is patching `#calculate`, and how important that may be.
I see the reasoning for patching `#calculate` by this library is helpfully defined in the patched method:
`# Same as original except we don't perform PostgreSQL hack that removes ordering.`
Comparing to the original activerecord `#calculate` implementation, the following lines are removed for `count` …
> Include Calculations module instead of prepending

- CHANGELOG.md
- lib/active_record/connection_adapters/sqlserver/quoting.rb
- lib/active_record/connection_adapters/sqlserver/schema_statements.rb
- lib/active_record/connection_adapters/sqlserver/sql_type_metadata.rb
- lib/active_record/connection_adapters/sqlserver_column.rb
- test/cases/adapter_test_sqlserver.rb
- test/cases/rake_test_sqlserver.rb
This PR refactors `SQLServer::Column` (former `SQLServerColumn`) and `SQLServer::TypeMetadata` so it includes the SQL Server's specific attributes.
Instead of having a Hash with all SQL Server attributes, the logic was changed to handle named attributes the same way the Postgres adapter does. This is to make sure all attributes are dumped into the schema cache once necessary and to make it more compliant with what Rails does internally.
**Important**
**This is a breaking change comparing to older versions and if you have a `schema_cache.{yml,dump}`, a fresh dump will be necessary.**
Fix #696.
> Fix schema cache generation

- CHANGELOG.md
- lib/arel/visitors/sqlserver.rb
- test/cases/fetch_test_sqlserver.rb
- test/models/sqlserver/composite_pk.rb
- test/schema/sqlserver_specific_schema.rb
Even though Rails does not support tables with primary keys, it still allows
those tables to be defined without any problems.
The SQL Server adapter will always try to retrieve records in a deterministic
way but it currently fails if the table has a composite primary key, which
shouldn't happen.
This PR fixes how the adapter determines which column (generally the PK) is
used as the default order when multiple primary keys are detected.
It first checks if one of the primary keys is also an identity column. If
there's an identity column, it will choose it as the "main primary key",
otherwise it will just fallback to the first of the primary keys.
Fix #719.
> Fix deteministic fetch when table has a composite primary key

- CHANGELOG.md
- lib/active_record/connection_adapters/sqlserver/type/date.rb
- test/cases/column_test_sqlserver.rb
Fix a bug where filtered `date` columns couldn't be serialized if value was date range. See #937 for more information.
Fixes #937.
> Fix date columns serialization for range values

- CHANGELOG.md
- lib/active_record/connection_adapters/sqlserver_adapter.rb
- test/cases/adapter_test_sqlserver.rb
Creating a record that violates a primary key constraint should throw an `ActiveRecord::RecordNotUnique` error rather than the generic `ActiveRecord::StatementInvalid` error.
The issue was caused by how the adapter was translating MSSQL errors into ActiveRecord errors. We were handling unique key violations but not primary key violations.
Fixes https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/issues/939
> Primary key violation should result in RecordNotUnique error

- CHANGELOG.md
- README.md
- lib/active_record/connection_adapters/sqlserver_adapter.rb
Fixes the application name so that the Rails application name can be used for the database connection created by TinyTDS. 
During the refactoring in https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/pull/917 the method `configure_application_name` should have been moved from an instance to a class method. This resulted in the application name never getting set to the Rails application name as the call to `configure_application_name` would throw a `NameError` exception, which resulted in the application name being set to `nil`. The TinyTds client would ignore the `nil` and use 'TinyTds' as the application name instead (https://github.com/rails-sqlserver/tiny_tds/blob/e3e79a030271891b11b6e7676382fe31f389b099/lib/tiny_tds/client.rb#L50).
> Fix application name sent to TinyTDS

- CHANGELOG.md
- lib/active_record/connection_adapters/sqlserver_adapter.rb
The adapter can be used outside a Rails context so TinyTDS appname config should
be able to be resolved if a Rails application was not detected.
Fix #942.
> Fix appname resolution when outside Rails context

- lib/active_record/connection_adapters/sqlserver/type/data.rb
Fixes for the Rails 7 CI `quoted_time` errors.
```
NoMethodError: undefined method `sub' for "01-01-2000 07:17:04.0":ActiveRecord::ConnectionAdapters::SQLServer::Type::Data
Did you mean?  stub
rails (5850a6592ff1) activerecord/lib/active_record/connection_adapters/abstract/quoting.rb:141:in `quoted_time'
rails (5850a6592ff1) activerecord/lib/active_record/connection_adapters/abstract/quoting.rb:22:in `quote'
activerecord-sqlserver-adapter/lib/active_record/connection_adapters/sqlserver/quoting.rb:121:in `quote'
```
The PR reduces the CI errors from (https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/runs/4617260332?check_suite_focus=true):
```
7743 runs, 11683 assertions, 77 failures, 3396 errors, 39 skips
```
to (https://github.com/rails-sqlserver/activerecord-sqlserver-ada …
> [Rails 7] Added support for quoted_time

- test/cases/coerced_tests.rb
Cleanup the coerced tests that can no longer be found in the Rails test suite. 
The tests are listed in the CI output with a 🐳. [Example](https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/runs/4619098779?check_suite_focus=true#step:4:61):
```
🐳  Unfound coerced test: ActiveRecord::ConnectionAdapters::QuoteARBaseTest#test_quote_ar_object
```
> [Rails 7] Cleanup unfound coerced tests

- test/cases/coerced_tests.rb
Coerce and reimplement the [ActiveRecord::Migration::ForeignKeyTest#test_add_foreign_key_with_if_not_exists_not_set](https://github.com/rails/rails/blob/v7.0.0/activerecord/test/cases/migration/foreign_key_test.rb#L679) test which depends on the database adapters error message.
> [Rails 7] Coerce foreign key test for SQL Server error message

- lib/active_record/connection_adapters/sqlserver/database_statements.rb
Fix the following error: 
```
ArgumentError: unknown keyword: :async
activerecord-sqlserver-adapter/lib/active_record/connection_adapters/sqlserver/database_statements.rb:29:in `exec_query'
rails (5850a6592ff1) activerecord/lib/active_record/future_result.rb:127:in `exec_query'
rails (5850a6592ff1) activerecord/lib/active_record/future_result.rb:133:in `exec_query'
rails (5850a6592ff1) activerecord/lib/active_record/future_result.rb:119:in `execute_query'
```
Async queries were introduced in [this commit](https://github.com/rails/rails/commit/7fc174aadaefc2c0a8a6b7c8a7599dd9ca04811f).
The PR reduces the CI errors from (https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/runs/4617260332?check_suite_focus=true):
7743 runs, 13869 assertions, 85 failures, 2636 errors, 39 skips …
> [Rails 7] Add missing keyword `async` to `exec_query` method

- lib/active_record/connection_adapters/sqlserver_adapter.rb
Fixes:
```
SQLServerRakeDropTest#test_0002_prints error message when database does
not exist:
ArgumentError: unknown keywords: :sql, :binds
```
`NoDatabaseError` extends `InvalidStatement` which supports `:sql` and `:binds` keywords but [this commit](https://github.com/rails/rails/commit/b28711ffa015217e2c24c87152a2f37d8aca1c83) declares initialize method without them.
The PR reduces the CI errors from (https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/runs/4617260332?check_suite_focus=true):
7743 runs, 13869 assertions, 85 failures, 2636 errors, 39 skips
to (https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/runs/4621836570?check_suite_focus=true)
7743 runs, 11418 assertions, 76 failures, 3405 errors, 40 skips
> [Rails 7] Remove sql and bindings params from NoDatabaseError initialization

- lib/active_record/connection_adapters/sqlserver/type/time.rb
```
DEPRECATION WARNING: Time#to_s(:_sqlserver_time) is deprecated. Please
use Time#to_formatted_s(:_sqlserver_time) instead. (called from
serialize at
/activerecord-sqlserver-adapter/lib/active_record/connection_adapters/sqlserver/type/time.rb:14)
/usr/local/lib/ruby/2.7.0/delegate.rb:83:in `method_missing'
/activerecord-sqlserver-adapter/lib/active_record/connection_adapters/sqlserver/type/time.rb:14:in
`serialize'
/activerecord-sqlserver-adapter/lib/active_record/connection_adapters/sqlserver/type/time.rb:24:in
`type_cast_for_schema'
```
> [Rails 7] Remove Time#to_s(:_sqlserver_time) is deprecated warning

- test/cases/coerced_tests.rb
Rails have made changes that make the coercion unnecessary
Before (https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/runs/4650448486?check_suite_focus=true):
```
7739 runs, 21027 assertions, 95 failures, 63 errors, 43 skips
```
After (https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/runs/4658531275?check_suite_focus=true)
```
7739 runs, 21027 assertions, 95 failures, 63 errors, 43 skips
```
> [Rails 7] Remove annotate tests coercion

- test/migrations/transaction_table/1_table_will_never_be_created.rb
Fixes:
```
Failure:
MigrationTestSQLServer::For transactions#test_0001_not create a tables if error in migrations [/activerecord-sqlserver-adapter/test/cases/migration_test_sqlserver.rb:25]:
Expected /this and all later migrations canceled/ to match "Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Active Record release the migration was written for:\n\n  class TableWillNeverBeCreated < ActiveRecord::Migration[7.0]".
```
Before (https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/runs/4650448486?check_suite_focus=true):
```
7739 runs, 21027 assertions, 95 failures, 63 errors, 43 skips
```
After (https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/runs/4671594128?check_suite_focus=true)
```
7739 runs, 21035 assertions, 94 …
```
> [Rails 7] Add missing release version to migration

- test/cases/coerced_tests.rb
Fixes
````
LogSubscriberTest#test_verbose_query_logs_coerced:
NameError: undefined local variable or method `original_test_vebose_query_logs' for #<LogSubscriberTest:0x00007f7d7b2850c8 @NAME="test_verbose_query_logs_coerced"
````
Before (https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/runs/4650448486?check_suite_focus=true):
```
7739 runs, 21027 assertions, 95 failures, 63 errors, 43 skips
```
After (https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/runs/4671248057?check_suite_focus=true)
```
7739 runs, 21034 assertions, 95 failures, 62 errors, 43 skips
```
> [Rails 7] Typo on coerced test original call

- test/cases/coerced_tests.rb
Fixes:
```
Error:
EnumTest#test_0084_serializable? with large number label:
ActiveRecord::RecordNotUnique: TinyTds::Error: Cannot insert duplicate key row in object 'dbo.books' with unique index 'index_books_on_author_id_and_name'. The duplicate key value is (<NULL>, <NULL>).
```
> [Rails 7] Coerce test to deal with unique index

- CHANGELOG.md
- lib/active_record/connection_adapters/sqlserver/database_statements.rb
- test/cases/coerced_tests.rb
Add support to `ActiveRecord::QueryLogs`
`ActiveRecord::QueryLogs` was introduced [here](https://github.com/rails/rails/commit/2408615154d039264810edbe628f4fc06d8cdc45). Then Rails decided to delegate query transformation responsibility to
each adapter [here](https://github.com/rails/rails/commit/12cc24a733190693c9e703c3edbd024a445d52db)
```
```
After (https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/runs/4675651408?check_suite_focus=true)
```
7739 runs, 21031 assertions, 83 failures, 60 errors, 43 skips
```
> [Rails 7] Transform queries to add comments

- test/cases/coerced_tests.rb
SQL Server does not support upsert yet. There are 7 tests that do not check if the driver support it. This PR coerce these tests.
```
```
After (https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/runs/4675657652?check_suite_focus=true)
```
7739 runs, 21044 assertions, 94 failures, 53 errors, 43 skips
```
> [Rails 7] Coerce tests that use upsert

- test/cases/coerced_tests.rb
Fixes: 
```
RelationTest#test_reorder_with_first_coerced [/activerecord-sqlserver-adapter/test/cases/coerced_tests.rb:1189]:
Expected a deprecation warning within the block but received none
```
Original test changed [here](https://github.com/rails/rails/commit/773eeec6ab2397894fb66b7dca2b84bd0d182d7e)
```
```
After (https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/runs/4675670619?check_suite_focus=true)
```
7739 runs, 21039 assertions, 93 failures, 60 errors, 43 skips
```
> [Rails 7] Update test fo Model.reorder(nil).first usage

- test/cases/coerced_tests.rb
Error introduced in #978
Fixes:
````
EnumTest#test_0093_serializable? with large number label coerced:
NoMethodError: undefined method `original_serializable? with large number label ...
Did you mean?  original_serializable\? with large number label
````
```
```
After (https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/runs/4675689174?check_suite_focus=true)
```
7739 runs, 21044 assertions, 94 failures, 59 errors, 43 skips
```
> [Rails 7] Fix original method call

- CHANGELOG.md
- lib/arel/visitors/sqlserver.rb
Due to our Arel monkey patch for [IN with prepared statements](https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/blob/main/lib/arel/visitors/sqlserver.rb#L82), encrypted attributes values were encrypted twice.
Take the following example
```
ActiveRecord::Encryption.config.support_unencrypted_data = true
EncryptedBook.find_by(name: "Dune")
```
Before:
```
EXEC sp_executesql N'SELECT [encrypted_books].* FROM [encrypted_books]
WHERE [encrypted_books].[name] IN (@0, @1) ORDER BY [encrypted_books].[id] ASC
OFFSET 0 ROWS FETCH NEXT @2 ROWS ONLY', N'@0 nvarchar(max), @1 nvarchar(max), @2 int',
@0 =
N'{"p":"BbyqDSWICbMEBTtrN4iv0paan00brX1ly6wT92lFrgOQZomP5jBjhPlalbTvucTFX249bJHp7j6usa7SBpAuQFzN+sZFa3dMnlTcaei5","h":{"iv":"2esXR4qnvSteG+o7","at":"pXZzi+SpMNxpAvA8eQYVqA=="}}',
@1 = …
```
> [Rails 7] Support find_by an encrypted attribute

- CHANGELOG.md
- lib/active_record/connection_adapters/sqlserver/schema_statements.rb
Rails introduced an optimization to remove_columns [here](https://github.com/rails/rails/commit/bff3523242d3fcdc7a069ff86863e08d01537674) to use a single SQL statement.
The produced SQL is
```sql
ALTER TABLE [my_table] DROP COLUMN [col_one], DROP COLUMN [col_two]
```
but SQL Server requires
```sql
ALTER TABLE [my_table] DROP COLUMN [col_one], [col_two]
```
This PR fixes: 
```
Error:
ActiveRecord::Migration::ColumnsTest#test_remove_columns_single_statement:
ActiveRecord::StatementInvalid: TinyTds::Error: Incorrect syntax near the keyword 'DROP'.
```
```
```
After …
> [Rails 7] Optimize remove columns

- test/cases/coerced_tests.rb
Fixes
````
HasOneThroughDisableJoinsAssociationsTest#test_disable_joins_through_with_enum_type [/usr/local/bundle/bundler/gems/rails-5850a6592ff1/activerecord/test/cases/associations/has_one_through_disable_joins_associations_test.rb:82]:
Expected /"memberships"."type"/ to match "EXEC sp_executesql N'SELECT [memberships].[club_id] FROM [memberships] WHERE [memberships].[member_id] = @0 AND [memberships].[type] = @1', N'@0 int, @1 int', @0 = 1, @1 = 1".
````
```
```
After (https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/runs/4675665721?check_suite_focus=true)
```
7739 runs, 21036 assertions, 94 …
```
> [Rails 7] Coerce test to match sql server table quoting

- CHANGELOG.md
- lib/active_record/connection_adapters/sqlserver/database_statements.rb
- test/cases/coerced_tests.rb
Following the same strategy as rails/rails@8cf09b7.
```
If the SQL encoding somehow is invalid, `Regexp#match?` raises
`ArgumentError`.
Best we can do is to copy the string and try to match the regexp in "binary" mode.
```
After this change ActiveRecord::StatementInvalid is raised. Quoting [Rails Postgresql
test](rails/rails@8cf09b7#diff-39aac151bf5772be2c6c4fec49bf5cdf5a21ca816fe181ef01466ecd941bef9bR56)
```
At least we can assert it fails in the client and not before when trying
to match the query.
```
This PR fixes
```
Error:
ActiveRecord::AdapterPreventWritesTest#test_doesnt_error_when_a_select_query_has_encoding_errors:
ArgumentError: invalid byte sequence in UTF-8
``` …
> [Rails 7] Better handle sql queries

- CHANGELOG.md
- lib/active_record/connection_adapters/sqlserver/database_statements.rb
- test/cases/coerced_tests.rb
[Rails added](https://github.com/rails/rails/commit/c7613dde539a8ffb710e432d131ccc7891520066) support to string returning clause for `insert_all`.
This PR port that behaviour.
We are not manipulating the string in any way, which means that clients need to use `INSERTED.column_name`
This PR fixes
```
Error:
InsertAllTest#test_insert_all_returns_requested_sql_fields:
NoMethodError: undefined method `map' for "UPPER(name) as name":Arel::Nodes::SqlLiteral
Did you mean?  tap
```
```
```
After (https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/runs/4702975837?check_suite_focus=true):
```
7739 runs, 21033 …
```
> [Rails 7] Support string returning clause for AR#insert_all

- lib/active_record/connection_adapters/sqlserver/core_ext/preloader.rb
- test/cases/eager_load_too_many_ids_test_sqlserver.rb
Fixes:
```
Error:
EagerLoadingTooManyIdsTest#test_preloading_too_many_ids:
ActiveRecord::StatementInvalid: TinyTds::Error: The query processor ran
out of internal resources and could not produce a query plan. This is a
rare event and only expected for extremely complex queries or queries
that reference a very large number of tables or partitions. Please
simplify the query. If you believe you have received this message in
error, contact Customer Support Services for more information.
```
The adapter monkey patch `Preloader::Association` to preload in slices
of 10.000 records (see
[here](https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/blob/main/lib/active_record/connection_adapters/sqlserver/core_ext/preloader.rb).
Rails moved the method the adapter was patching to …
> [Rails 7] Update preloader monkey patch

- CHANGELOG.md
- lib/active_record/connection_adapters/sqlserver/schema_statements.rb
mysql, sqlite3 and postgresql have consistent behaviour regarding non-existing table columns (see [this commit](https://github.com/rails/rails/commit/e323e68a750c8dbc3b7ef156c99c3924c38a84c0)).
SQL server was returning an empty array.
This is a breaking change but apps can recover by adding a rescue block.
Make more sense to behave like all other adapters.
Fixes:
```
Failure:
ActiveRecord::ConnectionAdapters::SchemaCacheTest#test_columns_for_non_existent_table [/home/matias/.rvm/gems/ruby-2.7.4/bundler/gems/rails-5850a6592ff1/activerecord/test/cases/connection_adapters/schema_cache_test.rb:139]:
ActiveRecord::StatementInvalid expected but nothing was raised.
Failure:
ActiveRecord::ConnectionAdapters::SchemaCacheTest#test_columns_hash_for_non_existent_table …
```
> [Rails 7] Raise error asking for non-existing table columns

- test/cases/coerced_tests.rb
SQL Server adapter doesn't support `:blob` data type. One test is using it. The original test has a conditional to use another data type for Postgresql, which doesn't support blob too.
The PR reimplements the test using `:binary` data type.
Fixes
````
```
```
```
After (https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/runs/4738774805?check_suite_focus=true):
```
7743 runs, 21048 assertions, 94 failures, 59 errors, 43 skips
```
> [Rails 7] Coerce test using blob

- test/cases/coerced_tests.rb
Fixes:
````
Failure:
ActiveRecord::Encryption::EncryptableRecordTest#test_0032_validate column sizes [/usr/local/bundle/bundler/gems/rails-5850a6592ff1/activerecord/test/cases/encryption/encryptable_record_test.rb:254]:
Expected true to be nil or false
rails test usr/local/bundle/bundler/gems/rails-5850a6592ff1/activerecord/test/cases/encryption/encryptable_record_test.rb:252
````
SQL Server string column limit is 4000. Other adapters use 255. Reimplement test to produce an invalid string considering SQL Server limit
> [Rails 7] Coerce encrypted with limit test

- test/support/rake_helpers.rb
Encryption performance is a flaky test (failing in [this run](https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/runs/4803186154?check_suite_focus=true#step:4:304) but the [next one](https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/runs/4803192585?check_suite_focus=true) is not failing)
Rails is not running encryption performance test on builds.
Commit https://github.com/rails/rails/commit/1fff866dd1239ff861574ed186e76bdbb166cff1) claims they were meant to be excluded from builds.
The commit also includes the same flaky test failure we have now.
Update `ar_cases` to exclude encryption performance tests
> [Rails 7] exclude encryption performance from builds

- test/cases/column_test_sqlserver.rb
Replace the octal values in the `ColumnTestSQLServer` tests with integers. Mixing octal and integer values together in the tests can lead to confusion.
> Replace octal values with integers

- test/cases/coerced_tests.rb
The ordering of results is not guaranteed by SQL Server if not specified. This results in the `ActiveRecord::RelationTest#test_select_quotes_when_using_from_clause` test randomly failing.
See https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/runs/4805711536?check_suite_focus=true
```
Failure:
ActiveRecord::RelationTest#test_select_quotes_when_using_from_clause [/usr/local/bundle/bundler/gems/rails-595a37d477be/activerecord/test/cases/relation_test.rb:296]:
--- expected
+++ actual
@@ -1 +1 @@
-[3, 1, 2, 4, 5, 6, 7, 9, 11, 8, 10]
+[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
rails test usr/local/bundle/bundler/gems/rails-595a37d477be/activerecord/test/cases/relation_test.rb:292
```
> [Rails 7] Fix randomly failing Rails relations test

- CHANGELOG.md
- test/cases/schema_dumper_test_sqlserver.rb
The CI is failing following the release of Rails 7.0.2, see https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/runs/5123050136?check_suite_focus=true:
```
SchemaDumperTestSQLServer#test_0002_sst_datatypes_migration [/activerecord-sqlserver-adapter/test/cases/schema_dumper_test_sqlserver.rb:82]:
Precision of 6 not found in:
t.datetime "datetime_col".
Expected: 6
Actual: nil
```
The test is failing following https://github.com/rails/rails/pull/44358. When dumping a datetime column that uses the default precision of 6, the column will now be dumped with precision `nil` rather than `6`.
> Dump the precision for datetime columns following the new defaults

- CHANGELOG.md
- lib/active_record/connection_adapters/sqlserver/schema_creation.rb
- test/cases/active_schema_test_sqlserver.rb
Fix support for different index types. 
Index types were working in Rails 6.0 but were broken in Rails 6.1 by https://github.com/rails/rails/pull/39203. The issue was identified in https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/issues/999 for Rails 6.1.
This PR is for Rails 7.0. The fix will be backported to the `6-1-stable` branch after it is merged into `main`.
> [Rails 7.0] Fix support for different index types

- CHANGELOG.md
- lib/active_record/connection_adapters/sqlserver/schema_creation.rb
- test/cases/active_schema_test_sqlserver.rb
Back-port of https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/pull/1002 into the `6-1-stable` branch.
Fixes the https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/issues/999 issue that was initially reported for Rails 6.1
> [Rails 6.1] Fix support for different index types

- lib/active_record/connection_adapters/sqlserver/core_ext/explain_subscriber.rb
The module containing `silence_warnings` needs to be required before use. This fixes an issue when you require the 'activerecord-sqlserver-adapter' gem on it's own.
Fixes issue [!1016](https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/issues/1016)
The issue was introduced between Rails v7.0.2 and v7.0.3.
> Require reporting module containing silence_warnings

- CHANGELOG.md
- lib/active_record/connection_adapters/sqlserver/database_statements.rb
This PR fixes the failing `QueryCacheTest#test_query_cache_does_not_allow_sql_key_mutation` test.
```
QueryCacheTest#test_query_cache_does_not_allow_sql_key_mutation [/usr/local/bundle/bundler/gems/rails-926d00643fb7/activerecord/test/cases/query_cache_test.rb:493]:
FrozenError expected but nothing was raised.
```
The issue is that the SQL sent to instrumentation is expected to be frozen. In other adapters, the SQL string used for the query cache and instrumentation are the same frozen string. The freezing of the SQL is done by https://github.com/rails/rails/blob/487282cb40b013b9f2a86e1dbd5affa38955fab1/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb#L39
In the SQL Server adapter we wrap the SQL using `EXEC sp_executesql`. …
> Freeze the SQL sent to instrumentation

- lib/active_record/connection_adapters/sqlserver_adapter.rb
- lib/active_record/sqlserver_base.rb
- test/cases/dbconsole.rb
Related to https://github.com/rails/rails/pull/46093
Adds dbconsole method to be used when invoking bin/rails dbconsole.
Moves dbconsole logic related to SQL Server in Rails to the adapter. This connection code and corresponding test was in the dbconsole command in railties.
cc @paarthmadan
> Add dbconsole support to adapter

- lib/active_record/sqlserver_base.rb
The connection class API was renamed in https://github.com/rails/rails/pull/46166.
This is a followup on the changes made in https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/pull/1024 for https://github.com/rails/rails/pull/46093.
> Rename sqlserver_connection_class to sqlserver_adapter_class

- test/cases/coerced_tests.rb
Fixes:
https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/actions/runs/3282242551/jobs/5405374502
```
FieldOrderedValuesTest#test_in_order_of_with_string_column:
ActiveRecord::RecordNotUnique: TinyTds::Error: Cannot insert duplicate key row in object 'dbo.books' with unique index 'index_books_on_author_id_and_name'. The duplicate key value is (<NULL>, <NULL>).
activerecord-sqlserver-adapter/lib/active_record/connection_adapters/sqlserver/database_statements.rb:456:in `each'
activerecord-sqlserver-adapter/lib/active_record/connection_adapters/sqlserver/database_statements.rb:456:in `handle_to_names_and_values_dblib'
activerecord-sqlserver-adapter/lib/active_record/connection_adapters/sqlserver/database_statements.rb:447:in `handle_to_names_and_values' …
```
> [Rails 7] Coerced field order with strings test

- CHANGELOG.md
- lib/active_record/connection_adapters/sqlserver/quoting.rb
- test/cases/uuid_test_sqlserver.rb
Fixes https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/issues/1032
```
NoMethodError: undefined method `=~' for #<Proc:..
```
As [the issue](https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/issues/1032) explains `=~` [was removed](https://bugs.ruby-lang.org/issues/15231) from Proc.
`Proc` are handled by [this line of code](https://github.com/rails/rails/blob/v7.0.4.2/activerecord/lib/active_record/connection_adapters/abstract/quoting.rb#L96)
The solution is to add a check and call `~=` only when `value` is a `String`.
I took the oportunity to follow rubocop performance suggestions
```
Performance/StringInclude: Use String#include? instead of a regex match
with literal-only pattern.
```
Got the idea from postgresql adapter …
> Support proc default values in ruby 3.2 

- .github/workflows/ci.yml
- Gemfile
- appveyor.yml
- test/cases/coerced_tests.rb
- test/cases/rake_test_sqlserver.rb
Fix CI tests for Rails 6.1.7.2
Also, updated the CI Ruby matrix to match https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/pull/997
> Fix CI tests for Rails 6.1.7.2

- CHANGELOG.md
- README.md
- lib/active_record/connection_adapters/sqlserver_adapter.rb
The method `configure_connection` was meant to be a hook method to allow custom connection configuration. However, the method was implemented in the adapter to perform the default connection configuration. I have extracted the default connection configuration to it's own method so that the hook method is available again for custom configuration.
This allows users to implement `configure_connection` without having to re-implement the default configuration or call super to call the adapter's implementation of the method.
This fixes issue https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/issues/950
Note: The fix will later be backported to the `6-1-stable` branch.
> Fix hook method that allows custom connection configuration

- .github/workflows/ci.yml
- Dockerfile.ci
Updated the CI to use the latest rubies:
- v2.7.7
- v3.1.3
- v3.2.1
Using Github container registry instead of DockerHub for the docker images. See https://github.com/rails-sqlserver/docker-images/pull/4
This fixes https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/issues/1034
> Updated CI rubies

- docker-compose.ci.yml
Use Github container registry for the CI rather than combination of Github and Docker Hub.
> Use Github container registry instead of Docker Hub

- CHANGELOG.md
- lib/active_record/connection_adapters/sqlserver/database_statements.rb
- test/cases/adapter_test_sqlserver.rb
- test/cases/schema_test_sqlserver.rb
- test/models/sqlserver/alien.rb
- test/schema/sqlserver_specific_schema.rb
Fix issue with inserting records into non-dbo schema as reported in https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/issues/1043
>  Fix for inserting records into non-dbo schema table

- CHANGELOG.md
- lib/active_record/connection_adapters/sqlserver/database_statements.rb
- test/cases/adapter_test_sqlserver.rb
When inserting records using `exec_insert` the casing of the `VALUES` clause is irrelevant. Updated the regex to be case-insensitive.
> Ignore casing of VALUES clause when inserting records using SQL

- CHANGELOG.md
- lib/active_record/connection_adapters/sqlserver/database_statements.rb
- lib/active_record/connection_adapters/sqlserver/utils.rb
- test/cases/adapter_test_sqlserver.rb
- test/cases/schema_test_sqlserver.rb
- test/cases/utils_test_sqlserver.rb
- test/schema/sqlserver_specific_schema.rb
Fix the insertion of records to non-default schema table that has identity column using raw SQL. This fixes https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/issues/1050
If you tried to insert records into a table that has an identity column (`id` in this case) using `exec_insert`:
`connection.exec_insert("insert into [test].[aliens] (id, name) VALUES(1, 'Trisolarans'), (2, 'Xenomorph')"`
Then the adapter would first need to turn on `IDENTITY_INSERT` for the table first. However, instead of running:
```
SET IDENTITY_INSERT [test].[aliens] ON;
```
The adapter was ignoring the table schema and trying to turn on `IDENTITY_INSERT` for the table in the default schema.
```
SET IDENTITY_INSERT [aliens] ON;
```
If a table of the same name did not exist in the default schema then …
> Fix insertion of records to non-default schema table using raw SQL

- .github/workflows/ci.yml
- Gemfile
- appveyor.yml
- test/cases/coerced_tests.rb
Fix CI tests on the Rails 6.0 branch.
Most of the changes have been backported from https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/pull/1037
Note: The Rails 6.0 tests do not support Ruby 3.1.
> Fix CI tests for Rails 6.0

- CHANGELOG.md
- lib/active_record/connection_adapters/sqlserver/core_ext/attribute_methods.rb
- lib/active_record/connection_adapters/sqlserver/core_ext/calculations.rb
- lib/active_record/connection_adapters/sqlserver/core_ext/explain.rb
- lib/active_record/connection_adapters/sqlserver/core_ext/finder_methods.rb
- lib/active_record/connection_adapters/sqlserver/core_ext/preloader.rb
This is a cherry-picked fix that I'm kindly asking you to release for the 6.0+ version. 
**The original message**
Recent versions of Rails support multiple database connections within the same app. It is possible for these connections to use different adapters. For example, one adapter may use SQL Server, and another uses PostgreSQL.
This gem applies some monkey patches to ActiveRecord for SQL Server compatibility. These patches could break other adapters, though, in a multiple-database scenario.
This commit modifies the patches so that they are applied only if the connection is SQL Server. If not, the original ActiveRecord implementation (`super`) is used instead.
Fixes #929
> Apply monkey patches for SQL Server connections only (#933)

- test/cases/coerced_tests.rb
Fix the following tests to accommodate the `companies.status` column that was added to the tests in Rails 7.0.5.
See https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/actions/runs/5122100848/jobs/9210694895?pr=1057
```
CalculationsTest#test_select_avg_with_joins_and_group_by_as_virtual_attribute_with_ar_coerced:
ActiveRecord::StatementInvalid: TinyTds::Error: Column 'companies.status' is invalid in the select list because it is not contained in either an aggregate function or the GROUP BY clause.
CalculationsTest#test_select_avg_with_joins_and_group_by_as_virtual_attribute_with_sql_coerced:
ActiveRecord::StatementInvalid: TinyTds::Error: Column 'companies.status' is invalid in the select list because it is not contained in either an aggregate function or the GROUP BY …
```
> Fix tests to handle companies status column

- CHANGELOG.md
- lib/active_record/connection_adapters/sqlserver/schema_statements.rb
- lib/active_record/connection_adapters/sqlserver/table_definition.rb
- test/cases/coerced_tests.rb
- test/cases/schema_dumper_test_sqlserver.rb
- test/schema/sqlserver_specific_schema.rb
`Timestamp` columns should use precision 6 by default. This change was included in Rails 7.0.5 by https://github.com/rails/rails/pull/46110
The previous change to default `datetime` columns to use precision 6 was implemented in the adapter by https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/pull/990
This fixes https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/issues/1056
> Set precision 6 by default for timestamps

- MIT-LICENSE
- README.md
Updated the license to remove copyright. It now uses the same license as Ruby on Rails (see https://github.com/rails/rails/blob/5694f1ec0305e1946f6505257c596d4d6be9c4e4/README.md#L97).
This is in response to https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/issues/1063
@metaskills Could you review as copyright probably resides with you?
> Updated license to remove copyright

- test/cases/execute_procedure_test_sqlserver.rb
https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/issues/1067
Fix warning message:
```
DEPRECATION WARNING: assert_deprecated without a deprecator is deprecated (called from block in <class:ExecuteProcedureTestSQLServer> at /vagrant/activerecord-sqlserver-adapter/test/cases/execute_procedure_test_sqlserver.rb:46)
```
> Fix deprecated warning message

- lib/active_record/connection_adapters/sqlserver/schema_statements.rb
> Improve performance of view default function lookup

- lib/active_record/connection_adapters/sqlserver/database_statements.rb
- lib/active_record/connection_adapters/sqlserver_column.rb
Fix issue with auto-population of ActiveRecord object ID after creation by insert.
Example of fixed test is following from https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/actions/runs/5868251547/job/15910651869
```
InheritanceTest#test_class_with_blank_sti_name:
ActiveRecord::RecordNotFound: Couldn't find Company without an ID
rails (3779b5069dd1) activerecord/lib/active_record/relation/finder_methods.rb:474:in `find_with_ids'
rails (3779b5069dd1) activerecord/lib/active_record/relation/finder_methods.rb:69:in `find'
rails (3779b5069dd1) activerecord/lib/active_record/querying.rb:23:in `find'
rails (3779b5069dd1) activerecord/lib/active_record/core.rb:250:in `find'
rails (3779b5069dd1) activerecord/test/cases/inheritance_test.rb:50:in `test_class_with_blank_sti_name'
``` …
> Fix auto populated ID after insert

- lib/active_record/connection_adapters/sqlserver/database_statements.rb
Translation of exceptions has changed in Rails since https://github.com/rails/rails/commit/da52b0d954a356421ccc064df3b1285f2ba10eb5
PR translates exceptions if they happen during `sp_executesql`.
This fixes the following error from https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/actions/runs/5877896924/job/15938914187
```
2023-08-16T11:00:18.3284577Z UniquenessValidationTest#test_validate_uniqueness_with_limit_and_utf8_coerced [/activerecord-sqlserver-adapter/test/cases/coerced_tests.rb:21]:
2023-08-16T11:00:18.3285619Z [ActiveRecord::ValueTooLong] exception expected, not
2023-08-16T11:00:18.3286456Z Class: <TinyTds::Error>
2023-08-16T11:00:18.3287205Z Message: <"String or binary data would be truncated.">
2023-08-16T11:00:18.3287740Z ---Backtrace--- …
```
> Translate exceptions

- test/cases/coerced_tests.rb
Coerce the `SanitizeTest#test_named_bind_with_literal_colons` test to handle nvarchar string `N''`.
https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/actions/runs/5877896924/job/15938914187#step:4:408
```
2023-08-16T11:00:18.7978921Z Failure:
2023-08-16T11:00:18.7980364Z SanitizeTest#test_named_bind_with_literal_colons [/usr/local/bundle/bundler/gems/rails-6db58ed7b6b3/activerecord/test/cases/sanitize_test.rb:228]:
2023-08-16T11:00:18.7980914Z --- expected
2023-08-16T11:00:18.7981144Z +++ actual
2023-08-16T11:00:18.7981408Z @@ -1 +1 @@
2023-08-16T11:00:18.7981816Z -"TO_TIMESTAMP('2017/08/02 10:59:00', 'YYYY/MM/DD HH12:MI:SS')"
2023-08-16T11:00:18.7982290Z +"TO_TIMESTAMP(N'2017/08/02 10:59:00', 'YYYY/MM/DD HH12:MI:SS')"
```
> Coerce sanitize test

- lib/active_record/connection_adapters/sqlserver/quoting.rb
- test/cases/coerced_tests.rb
Fix to accept nested functions in Dangerous Query Methods (see https://github.com/rails/rails/pull/44010). 
Tests needed to be coerced as SQL Server uses `len()` instead of `length()`.
> Accept nested functions in Dangerous Query Methods

- lib/active_record/connection_adapters/sqlserver/quoting.rb
- test/cases/coerced_tests.rb
Collation name cannot be quoted in SQL Server. Rails test uses hardcoded values per adapter.
See https://github.com/rails/rails/pull/44384
> Allow column name with COLLATE as safe SQL string

- test/cases/coerced_tests.rb
Coerced test that uses different format of SQL.
```
Failure:
RelationTest#test_0024_relations don't load all records in #pretty_print [/usr/local/bundle/bundler/gems/rails-bd4996bdfddb/activerecord/test/cases/relations_test.rb:2148]:
Query pattern(s) /LIMIT|ROWNUM <=|FETCH FIRST/ not found.
Queries:
EXEC sp_executesql N'SELECT [posts].* FROM [posts] /* loading for pp */ ORDER BY [posts].[id] ASC OFFSET 0 ROWS FETCH NEXT @0 ROWS ONLY', N'@0 int', @0 = 11
bin/rails test /usr/local/bundle/bundler/gems/rails-bd4996bdfddb/activerecord/test/cases/relations_test.rb:2147
```
> Coerced pretty print test

- lib/active_record/connection_adapters/sqlserver/database_statements.rb
- test/cases/coerced_tests.rb
Fixed the adapter for the Rails `activerecord/test/cases/query_logs_test.rb` tests. SQL was being incorrectly transformed twice. Updated coerced tests.
> Fix query logs tests

- lib/active_record/connection_adapters/sqlserver/schema_statements.rb
- test/cases/coerced_tests.rb
In SQL Server only the first column added should have the `ADD` keyword.
Incorrect SQL:
```sql
ALTER TABLE [my_table] ADD [created_at] datetime2(6) NOT NULL, ADD [updated_at] datetime2(6) NOT NULL
```
Correct SQL:
```sql
ALTER TABLE [my_table] ADD [created_at] datetime2(6) NOT NULL, [updated_at] datetime2(6) NOT NULL
```
Fixes test:
```
ActiveRecord::Migration::ColumnsTest#test_add_timestamps_single_statement:
ActiveRecord::StatementInvalid: TinyTds::Error: Incorrect syntax near the keyword 'ADD'.
activerecord-sqlserver-adapter/lib/active_record/connection_adapters/sqlserver/database_statements.rb:28:in `do'
...
bin/rails test /usr/local/bundle/bundler/gems/rails-7b670848e136/activerecord/test/cases/migration/columns_test.rb:399
```
> Fix for adding timestamps to table

- CHANGELOG.md
- lib/active_record/connection_adapters/sqlserver/database_statements.rb
- test/cases/migration_test_sqlserver.rb
When creating a stored procedure that contained an insert statements, the SQL was being incorrectly flagged as a insert statement. We should check the start of the string to find if an SQL statement is an insert, rather than each line of the string. Issue introduced in Rails 7.0 branch by https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/pull/988
Fixes https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/issues/1087
> Fix creation of stored procedures that contain insert statements

- lib/active_record/connection_adapters/sqlserver/schema_statements.rb
When changing columns set date-time columns to `datetime(6)` by default.
Fixes failing test:
https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/actions/runs/6234806413/job/16922729893?pr=1088
```
Error:
CompatibilityTest7_0#test_datetime_sets_precision_6_on_change_table:
ActiveRecord::StatementInvalid: TinyTds::Error: Conversion failed when converting date and/or time from character string.
activerecord-sqlserver-adapter/lib/active_record/connection_adapters/sqlserver/database_statements.rb:454:in `each'
activerecord-sqlserver-adapter/lib/active_record/connection_adapters/sqlserver/database_statements.rb:454:in `handle_to_names_and_values_dblib'
```
> When changing columns set date-time columns to datetime(6) by default

- lib/active_record/connection_adapters/sqlserver/core_ext/calculations.rb
- lib/active_record/connection_adapters/sqlserver/core_ext/finder_methods.rb
Fixes the failing `activerecord/test/cases/null_relation_test.rb` tests. Needed to copy over the changes made to the `ActiveRecord::Calculations.calculate` method that we monkey-patch.
Cleaned up the `construct_relation_for_exists` monky-patch too.
> Update calculate monkey-patch

- lib/active_record/connection_adapters/sqlserver/database_statements.rb
- lib/active_record/connection_adapters/sqlserver/schema_statements.rb
Fixes for the `USE` clause.
- `USE` queries should not be regarded as write queries. 
- `USE` queries should be marked as schema type queries. 
Changes reduced the number of failing `bundle exec rake test TEST_FILES_AR="test/cases/query_cache_test.rb"` tests.
Before
```
55 runs, 169 assertions, 6 failures, 2 errors, 2 skips
```
After
```
55 runs, 173 assertions, 5 failures, 0 errors, 2 skips
```
> Fixes for USE clause

- test/cases/coerced_tests.rb
Escape the regular expressions in the coerced tests. They were causing the following warnings:
https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/actions/runs/6249682885/job/16966903222?pr=1092
```
(none):1340: warning: character class has duplicated range: /order by [posts].[title]/
(none):1352: warning: character class has duplicated range: /order by [posts].[title]/
```
> Escape regexs

- test/cases/coerced_tests.rb
Coerce `FinderTest` tests that use `FETCH NEXT` in their SQL rather than `LIMIT`.
https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/actions/runs/6247329444/job/16959692562?pr=1091
> Coerce tests that require FETCH NEXT sql

- test/cases/coerced_tests.rb
Coerce tests that rely on upsert. The SQL Server adapter does not support upsert and so Rails tests that rely on it (those using insert/insert_all) need to be coerced.
> Coerce tests that rely on upsert

- test/cases/coerced_tests.rb
Fix the `test/cases/migration/invalid_options_test.rb` tests.
https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/actions/runs/6300135339/job/17102280466?pr=1094
```
ActiveRecord::Migration::InvalidOptionsTest#test_add_reference_with_invalid_options [/usr/local/bundle/bundler/gems/rails-6797c7382e37/activerecord/test/cases/migration/invalid_options_test.rb:46]:
--- expected
+++ actual
@@ -1 +1 @@
-"Unknown key: :boring_key. Valid keys are: :limit, :precision, :scale, :default, :null, :collation, :comment, :primary_key, :if_exists, :if_not_exists"
+"Unknown key: :boring_key. Valid keys are: :limit, :precision, :scale, :default, :null, :collation, :comment, :primary_key, :if_exists, :if_not_exists, :is_identity"
bin/rails test …
```
> Fix the invalid options migration tests

- lib/active_record/connection_adapters/sqlserver/schema_statements.rb
Queries to find table indexes should be marked as schema queries. This will fix a number of failing tests including:
https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/actions/runs/6300135339/job/17102280466?pr=1094
```
UniquenessValidationWithIndexTest#test_changing_non_unique_attribute [/usr/local/bundle/bundler/gems/rails-6797c7382e37/activerecord/test/cases/validations/uniqueness_validation_test.rb:668]:
2 instead of 0 queries were executed.
Queries:
SELECT [filter_definition] FROM sys.indexes WHERE name = N'index_topics_on_author_name_and_title'
SELECT [filter_definition] FROM sys.indexes WHERE name = N'topics_index'.
Expected: 0
Actual: 2
```
> Queries to find indexes are schema queries

- lib/active_record/connection_adapters/sqlserver/schema_statements.rb
- test/cases/coerced_tests.rb
Fixed schema statements so that the Rails `activerecord/test/cases/migration/foreign_key_test.rb` tests pass. Included adding support for composite foreign keys.
> Fix foreign key tests

- lib/active_record/connection_adapters/sqlserver/schema_statements.rb
The `unique` attribute of `IndexDefinition` should be a boolean.
Fixes `ActiveRecord::Migration::ReferencesStatementsTest#test_creates_named_unique_index` test.
https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/actions/runs/6328689792/job/17187421431
```
ActiveRecord::Migration::ReferencesStatementsTest#test_creates_named_unique_index [/usr/local/bundle/bundler/gems/rails-6797c7382e37/activerecord/test/cases/migration/references_statements_test.rb:82]:
Expected false to be truthy.
bin/rails test /usr/local/bundle/bundler/gems/rails-6797c7382e37/activerecord/test/cases/migration/references_statements_test.rb:80
```
> Unique attribute of IndexDefinition should be a boolean

- lib/active_record/connection_adapters/sqlserver/schema_statements.rb
Fix for following type of errors.
https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/actions/runs/6380010572/job/17313600140?pr=1102
```
ActiveRecord::Migration::SchemaDefinitionsTest#test_build_change_column_default_definition:
NotImplementedError: build_change_column_default_definition is not implemented
rails (ccb7be66ac20) activerecord/lib/active_record/connection_adapters/abstract/schema_statements.rb:723:in `build_change_column_default_definition'
rails (ccb7be66ac20) activerecord/test/cases/migration/schema_definitions_test.rb:98:in `test_build_change_column_default_definition'
```
Implementation copied from Rails Postgresql adapter.
> Added method to build change column default definition

- lib/active_record/connection_adapters/sqlserver/core_ext/preloader.rb
- test/cases/coerced_tests.rb
Fix the SQL to use IN sql instead of OR sql for query constraints. This fixes test `preloading belongs_to association SQL` in `activerecord/test/cases/associations/eager_test.rb`. 
Changes required after https://github.com/rails/rails/pull/48947
> Use IN sql instead of OR sql for query constraints

- lib/active_record/connection_adapters/sqlserver/database_statements.rb
- lib/active_record/connection_adapters/sqlserver/savepoints.rb
- lib/active_record/connection_adapters/sqlserver_adapter.rb
When executing queries for savepoints, use `internal_execute` instead of `execute`. The method `execute` causes the query cache to be cleared which was breaking the following ActiveRecord tests:
- QueryCacheExpiryTest#test_insert 
- QueryCacheExpiryTest#test_update
- QueryCacheExpiryTest#test_destroy
- QueryCacheExpiryTest#test_cache_is_expired_by_habtm_update
> Savepoint queries should be internally executed

- lib/active_record/connection_adapters/sqlserver/database_statements.rb
Use `internal_execute` when sending transaction control SQL.
Fixes test:
- TransactionInstrumentationTest#test_reconnecting_after_materialized_transaction_starts_new_event
https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/actions/runs/6454350937/job/17519696207
```
Error:
TransactionInstrumentationTest#test_reconnecting_after_materialized_transaction_starts_new_event:
RuntimeError: Wrapped undumpable exception for: ActiveRecord::StatementInvalid: TinyTds::Error: The COMMIT TRANSACTION request has no corresponding BEGIN TRANSACTION.
```
> Fix materialized transaction queries

- lib/active_record/connection_adapters/sqlserver/schema_statements.rb
Fix the `ActiveRecord::Migration::SchemaDefinitionsTest#test_build_change_column_definition` test.
https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/actions/runs/6457398530/job/17528801352
```
Error:
ActiveRecord::Migration::SchemaDefinitionsTest#test_build_change_column_definition:
NoMethodError: undefined method `build_change_column_definition' for #<ActiveRecord::ConnectionAdapters::SQLServerAdapter version: 7.1.0, azure: false>
rails (5f296f893892) activerecord/test/cases/migration/schema_definitions_test.rb:86:in `test_build_change_column_definition'
```
> Added method to build change column definition

- lib/active_record/connection_adapters/sqlserver/core_ext/abstract_adapter.rb
- lib/active_record/connection_adapters/sqlserver/transaction.rb
- lib/active_record/connection_adapters/sqlserver_adapter.rb
Hi,
I've been trying to use the `main` version of the adapter on our project and can't make it running yet.
Here are 2 issues I've found so far.
1. Small bug
`rails_application_name` is called on the instance level instead of class
2. Issue with `sqlserver?` declaration
```
3.2.0 :001 > User.where(id: 1).exists?
/Users/alexandreovertus/.rvm/gems/ruby-3.2.0/bundler/gems/activerecord-sqlserver-adapter-d1a3b1dd1977/lib/active_record/connection_adapters/sqlserver/core_ext/finder_methods.rb:14:in `construct_relation_for_exists’: undefined method `sqlserver?' for #<ActiveRecord::ConnectionAdapters::Mysql2Adapter:0x0000000117eaf020 @transaction_manager=#<ActiveRecord::ConnectionAdapters::TransactionManager:0x00000001162e0100 @stack=[], @connection=#
```
`sqlserver?` is unknown from the other …
> Fix Rails application name and SQL Server check 

- lib/active_record/connection_adapters/sqlserver/type/data.rb
- test/cases/coerced_tests.rb
Implement the MessgePack methods on the `ActiveRecord::ConnectionAdapters::SQLServer::Type::Data` class as it doesn't inherit from any of the other class that implement them. 
Fixes test:
https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/actions/runs/6494022569/job/17636125629
```
Error:
ActiveRecordMessagePackTest#test_0002_roundtrips record and cached associations:
ActiveSupport::MessagePack::UnserializableObjectError: Unsupported type ActiveRecord::ConnectionAdapters::SQLServer::Type::Data for object "10-12-2023 09:49:44.575472"
rails (319256ac4708) activesupport/lib/active_support/message_pack/extensions.rb:233:in `raise_unserializable'
```
> Implement MessagePack methods on the Data class

- test/cases/coerced_tests.rb
Since SQL Server does not have a native JSON column type, JSON columns are stored as `nvarchar(max)`. Need to explicitly mark a model's attribute as JSON since it cannot be inferred. 
This PR marks the `admin_users.json_options` column as JSON so that the `StoreTest#saved changes tracking for accessors with json column` test passes following https://github.com/rails/rails/pull/43386
> Need to set explicitly set JSON attribute as such

- lib/active_record/connection_adapters/sqlserver/database_statements.rb
- lib/active_record/connection_adapters/sqlserver/schema_statements.rb
- lib/active_record/connection_adapters/sqlserver/showplan.rb
- lib/active_record/connection_adapters/sqlserver_adapter.rb
Use `internal_exec_query` and `internal_raw_execute` to run queries instead of `raw_connection_do` and `raw_connection_run`. The new methods standardise connection handling.
> Removed legacy connection handling

- .gitignore
- test/cases/coerced_tests.rb
- test/cases/disconnected_test_sqlserver.rb
- test/cases/helper_sqlserver.rb
- test/cases/rake_test_sqlserver.rb
Fix the redefined method warnings when running the test suite.
Examples:
```
/vagrant/activerecord-sqlserver-adapter/test/cases/coerced_tests.rb:2564: warning: method redefined; discarding old invalid_add_column_option_exception_message
/vagrant/rails/activerecord/test/cases/migration/invalid_options_test.rb:10: warning: previous definition of invalid_add_column_option_exception_message was here
/vagrant/activerecord-sqlserver-adapter/test/cases/coerced_tests.rb:2576: warning: method redefined; discarding old thread_encrypting_and_decrypting
/vagrant/rails/activerecord/test/cases/encryption/concurrency_test.rb:15: warning: previous definition of thread_encrypting_and_decrypting was here
/vagrant/activerecord-sqlserver-adapter/test/cases/coerced_tests.rb:2593: warning: method redefined; …
```
> Fix redefined method warnings

- test/cases/coerced_tests.rb
- test/cases/helper_sqlserver.rb
Coerce tests that are not testing SQL Server but using SQLite to test non-specific adapter functionality.
This fixes an issue with SQLite databases from previous tests runs causing tests to fail. Issue seems to have been caused by https://github.com/rails/rails/pull/38620
Previous attempt to remove the SQLite databases before the test suite runs doesn't work as multiple tests use the same databases.
> Coerce tests that are not testing SQL Server

- .github/workflows/ci.yml
Ruby 2.7.8 has reached EOL (https://www.ruby-lang.org/en/downloads/branches/).
> Remove Ruby 2.7.8 from CI

- CHANGELOG.md
- lib/active_record/connection_adapters/sqlserver/schema_statements.rb
- test/cases/view_test_sqlserver.rb
Issue https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/issues/1114
This PR fixes an issue where the default value of a view column is not found when the view column name starts with the same characters as "SELECT". So this issue would affect view columns named "s", "se", "sel", etc
> Fix view issue with default column value not found

- test/cases/coerced_tests.rb
No need to coerce the `SerializedAttributeTest` tests.
> Do not coerce the SerializedAttributeTest tests

- docker-compose.ci.yml
- test/cases/transaction_test_sqlserver.rb
Reset database connections after `TransactionTestSQLServer#should use READ COMMITTED as an isolation level`. This test sometimes causes the following tests to fail with the "TinyTds::Error: DBPROCESS is dead or not enabled" error (see https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/actions/runs/6783660587/job/18438377982?pr=1130).
> Reset connections after READ COMMITTED isolation test

- CHANGELOG.md
- lib/active_record/connection_adapters/sqlserver/schema_statements.rb
- test/cases/view_test_sqlserver.rb
Fix for issue https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/issues/1131
The regex to match a view column to table column name was too vague, which could cause a similarly named view column to be matched.
The issue was found in v7.0.5.0 (containing https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/pull/1126) but the issue was actually present in previous releases (eg: v7.0.4.0). The order that the view columns were declared affected whether the issue appeared or not. 
For example if you had view declaration: 
```sql
CREATE VIEW bug_tests AS SELECT id AS id, dt_field as dt, dt_fieldX as dt_x FROM bug_test_tables
```
And performed regex of `CREATE\s+VIEW.*AS\s+SELECT.*\W([\w-]*)\s+AS\s+dt` on it then you would get match:
1. dt_fieldX
If you changed the …
> Fix matching view's real column name

- lib/active_record/tasks/sqlserver_database_tasks.rb
- lib/arel/visitors/sqlserver.rb
The `visit_Arel_Nodes_HomogeneousIn` method was incorrectly removed in https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/pull/1068. This PR adds the method back in while also fixing the method for Rails 7.1
This fixes the following failing test that started in Rails 7.1.2 (https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/actions/runs/6849256715/job/18621067933?pr=1136):
```
Failure:
ActiveRecord::BindParameterTest#test_bind_params_to_sql_with_prepared_statements_coerced [/activerecord-sqlserver-adapter/test/cases/coerced_tests.rb:298]:
Query pattern(s) "EXEC sp_executesql N'SELECT [authors].* FROM [authors] WHERE ([authors].[id] IN (@0, @1, @2) OR [authors].[id] IS NULL)', N'@0 bigint, @1 bigint, @2 bigint', @0 = 1, @1 = 2, @2 = 3" not found.
Queries:
EXEC …
```
> Reintroduce visit_Arel_Nodes_HomogeneousIn monkey-patch

- CHANGELOG.md
- lib/active_record/connection_adapters/sqlserver/schema_statements.rb
- lib/active_record/connection_adapters/sqlserver_adapter.rb
- test/cases/coerced_tests.rb
Back-port https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/pull/1141 to the `7-0-stable` branch.
> Added support for check constraints (#1141)

- lib/active_record/connection_adapters/sqlserver/core_ext/preloader.rb
Ported fix in https://github.com/rails/rails/pull/50325 to the adapter. This will fix the test suite for the Rails 7.1.3 release.
> Fix Preloader to not generate a query for already loaded association with query_constraints

- .devcontainer/Dockerfile
- .devcontainer/boot.sh
- .devcontainer/devcontainer.json
- .devcontainer/docker-compose.yml
- README.md
- RUNNING_UNIT_TESTS.md
The [activerecord-sqlserver-adapter-dev-box](https://github.com/rails-sqlserver/activerecord-sqlserver-adapter-dev-box) relies on [VirtualBox](https://www.virtualbox.org), which does not support Apple Silicon chips (see https://forums.virtualbox.org/viewtopic.php?t=98742). 
As an alternative to VirtualBox we can use Dev Container CLI to create a developer environment for the SQL Server adapter. This is the same option is available for Rails development (see https://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#using-dev-container-cli).
> Added Dev Container CLI to run the tests

- CHANGELOG.md
- lib/arel/visitors/sqlserver.rb
- test/cases/fetch_test_sqlserver.rb
The SQL Server adapter makes select queries deterministic by ordering by the primary key if an ordering is not provided. 
If the FROM clause is specified using:
```ruby 
Book.from("(SELECT [books].* FROM [books]) [books]")
```
Then this would require the adapter to parse the raw SQL string `(SELECT [books].* FROM [books]) [books]` to find the table being queried so that its primary key could then be determined. Parsing raw SQL is very difficult and outside the requirements of the adapter. I don't think the Rails project parses raw SQL either because of the difficulty. 
To fix the above query the ordering should be given so that the adapter does not have to try to find the primary key:
```ruby
Book.from("(SELECT [books].* FROM [books]) [books]").order(:id)
```
This does require a small fix …
> FROM subquery should work if order provided

- CHANGELOG.md
- lib/active_record/connection_adapters/sqlserver/database_statements.rb
- test/cases/trigger_test_sqlserver.rb
- test/models/sqlserver/trigger.rb
- test/schema/sqlserver_specific_schema.rb
This updates the `OUTPUT INSERTED` statement to handle the case of composite primary keys being properly returned when the table also has a trigger.
> Fix Composite Key Inserts with Triggers

- lib/active_record/connection_adapters/sqlserver/core_ext/attribute_methods.rb
- lib/active_record/connection_adapters/sqlserver/core_ext/calculations.rb
- lib/active_record/connection_adapters/sqlserver/core_ext/explain.rb
- lib/active_record/connection_adapters/sqlserver/core_ext/finder_methods.rb
- lib/active_record/connection_adapters/sqlserver/core_ext/preloader.rb
- lib/active_record/connection_adapters/sqlserver/database_statements.rb
- test/cases/adapter_test_sqlserver.rb
- test/cases/coerced_tests.rb
- Eliminate uses of `lease_connection`. See rails/rails#51353
- Update the `internal_exec_query` method signature. See https://github.com/rails/rails/pull/51336
> Eliminate uses of lease_connection

- test/cases/coerced_tests.rb
- test/cases/eager_load_too_many_ids_test_sqlserver.rb
Rename `assert_queries` to `assert_queries_count`. See rails/rails#50373
> Rename assert_queries test

- lib/active_record/connection_adapters/sqlserver/database_statements.rb
Previously when using place-holder conditions (`where("written_on < ?", time)`), the value was interpolated into the query (`WHERE written_on < "2024-01-01 12:00:00"`). Now the place-holder condition is a query parameter (`WHERE written_on < @1`).
Fixes the "undefined method 'value_for_database'" errors seen in https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/actions/runs/8910633467/job/24470268020
> Allow basic attribute types to be query parameters

- lib/active_record/connection_adapters/sqlserver/savepoints.rb
- test/cases/coerced_tests.rb
- test/cases/helper_sqlserver.rb
- test/support/query_assertions.rb
SQL Server does not support releasing save-points. They are automatically released when transitions are committed/rolled-back. 
When the number of queries performed is asserted in tests, it is assumed that release save-point is supported. To work around this a dummy placeholder query is inserted if a transaction is saved at the start of the queries.
> When asserting queries performed, insert placeholder query for release save-point

- lib/active_record/connection_adapters/sqlserver/database_statements.rb
- test/cases/coerced_tests.rb
Fix:
- `ActiveRecord::InstrumentationTest#test_payload_row_count_on_pluck`
- `ActiveRecord::InstrumentationTest#test_payload_row_count_on_raw_sql`
See https://github.com/rails/rails/pull/50887
> Add row_count field to sql.active_record notification

- test/cases/adapter_test_sqlserver.rb
Fixes:
https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/actions/runs/9033092031/job/24822623240
```
AdapterTestSQLServer#test_0010_test bad connection [/activerecord-sqlserver-adapter/test/cases/adapter_test_sqlserver.rb:102]:
[ActiveRecord::NoDatabaseError] exception expected, not
Class: <NoMethodError>
Message: <"undefined method `sqlserver_connection' for class ActiveRecord::Base">
---Backtrace---
/usr/local/bundle/bundler/gems/rails-2744b74216e5/activerecord/lib/active_record/dynamic_matchers.rb:22:in `method_missing'
/activerecord-sqlserver-adapter/test/cases/adapter_test_sqlserver.rb:106:in `block (2 levels) in <class:AdapterTestSQLServer>'
```
> Fix test bad connection test

- lib/active_record/connection_adapters/sqlserver/database_statements.rb
- test/cases/coerced_tests.rb
Fix:
https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/actions/runs/9061194112/job/24892482330
```
25) Error:
ActiveRecord::InstrumentationTest#test_payload_row_count_on_pluck:
ActiveRecord::RecordNotUnique: TinyTds::Error: Cannot insert duplicate key row in object 'dbo.books' with unique index 'index_books_on_author_id_and_name'. The duplicate key value is (<NULL>, row count book 2).
/activerecord-sqlserver-adapter/lib/active_record/connection_adapters/sqlserver/database_statements.rb:433:in `each'
/activerecord-sqlserver-adapter/lib/active_record/connection_adapters/sqlserver/database_statements.rb:433:in `handle_to_names_and_values'
/activerecord-sqlserver-adapter/lib/active_record/connection_adapters/sqlserver/database_statements.rb:60:in `internal_exec_sql_query' …
```
> Return row-count for pluck

- Dockerfile.ci
- Gemfile
- docker-compose.ci.yml
Rails has cut a `7-2-stable` branch from `main` before Rails 7.2 has been released. Rather than supporting just the `main` branch on CI, allow any branch to be supported.
> Support any Rails branch in CI

- test/cases/coerced_tests.rb
Removed tests that no longer need to be coerced.
> Removed tests that no longer need to be coerced

- lib/active_record/connection_adapters/sqlserver/database_statements.rb
Fix for text showplan, which returns 2 result sets for single query. The multiple column headers were causing the following bug.
https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/actions/runs/9085233159/job/24968052134?pr=1173
```
ShowplanTestSQLServer::With SHOWPLAN_TEXT option#test_0001_use simple table printer:
RuntimeError: Wrapped undumpable exception for: ActiveRecord::StatementInvalid: NoMethodError: undefined method `-@' for an instance of Array
/usr/local/bundle/bundler/gems/rails-1d681e341c01/activerecord/lib/active_record/result.rb:52:in `each'
/usr/local/bundle/bundler/gems/rails-1d681e341c01/activerecord/lib/active_record/result.rb:52:in `initialize'
/activerecord-sqlserver-adapter/lib/active_record/connection_adapters/sqlserver/database_statements.rb:437:in …
```
> Fix for text showplan

- lib/active_record/connection_adapters/sqlserver/schema_statements.rb
Implemented change made in https://github.com/rails/rails/pull/50837
Fixes the `ActiveRecord::Migration::CompatibilityTest#test_rename_table_errors_on_too_long_index_name_7_0` test.
https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/actions/runs/9109903293/job/25043759601?pr=1174
```
24) Failure:
ActiveRecord::Migration::CompatibilityTest#test_rename_table_errors_on_too_long_index_name_7_0 [/usr/local/bundle/bundler/gems/rails-f92c8a3539ee/activerecord/test/cases/migration/compatibility_test.rb:434]:
StandardError expected but nothing was raised.
```
> Ensure pre-7.1 migrations use legacy index names when using rename_table

- test/cases/coerced_tests.rb
Coerce `ActiveRecord::ConnectionAdapters::PoolConfig::ResolverTest#test_url_invalid_adapter ` test as sqlserver not included in error message.
https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/actions/runs/9094436581/job/24995515248
```
ActiveRecord::ConnectionAdapters::PoolConfig::ResolverTest#test_url_invalid_adapter [/usr/local/bundle/bundler/gems/rails-cb60cc0b1539/activerecord/test/cases/database_configurations/resolver_test.rb:19]:
Expected /Database\ configuration\ specifies\ nonexistent\ 'ridiculous'\ adapter\.\ Available\ adapters\ are:\ abstract,\ fake,\ mysql2,\ postgresql,\ sqlite3,\ trilogy\.\ Ensure\ that\ the\ adapter\ is\ spelled\ correctly\ in\ config\/database\.yml\ and\ that\ you've\ added\ the\ necessary\ adapter\ gem\ to\ your\ Gemfile\ if\ it's\ not\ …
```
> Updated error message in test to include sqlserver

- lib/active_record/connection_adapters/sqlserver/database_statements.rb
Fix `ActiveRecord::Encryption::EncryptableRecordTest#test_0049_serialized binary data can be encrypted`.
https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/actions/runs/9116557246/job/25065421824
```
13) Error:
ActiveRecord::Encryption::EncryptableRecordTest#test_0049_serialized binary data can be encrypted:
ActiveRecord::StatementInvalid: TinyTds::Error: Implicit conversion from data type nvarchar(max) to varbinary(max) is not allowed. Use the CONVERT function to run this query.
lib/active_record/connection_adapters/sqlserver/database_statements.rb:434:in `each'
```
Ref: https://github.com/rails/rails/pull/50920
> Support encrypting binary columns

- test/support/query_assertions.rb
Fix `DirtyTest#test_partial_update`:
https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/actions/runs/9127055748/job/25096554308
```
DirtyTest#test_partial_update [/usr/local/bundle/bundler/gems/rails-fb4300ce193c/activerecord/test/cases/dirty_test.rb:365]:
5 instead of 6 queries were executed. Queries: SAVE TRANSACTION active_record_1
EXEC sp_executesql N'INSERT INTO [pirates] ([catchphrase], [parrot_id], [non_validated_parrot_id], [created_on], [updated_on]) OUTPUT INSERTED.[id] VALUES (@0, @1, @2, @3, @4)', N'@0 nvarchar(4000), @1 int, @2 int, @3 datetime2(6), @4 datetime2(6)', @0 = N'foo', @1 = NULL, @2 = NULL, @3 = '05-17-2024 10:53:27.262222', @4 = '05-17-2024 10:53:27.262222'
SAVE TRANSACTION active_record_1
EXEC sp_executesql N'UPDATE [pirates] SET [catchphrase] = …
```
> Add savepoint placeholder for each savepoint created

- lib/active_record/connection_adapters/sqlserver/table_definition.rb
- test/cases/helper_sqlserver.rb
- test/support/table_definition_sqlserver.rb
Need work-around following this change to `rails/activerecord/test/schema/schema.rb` https://github.com/rails/rails/pull/51826/files#diff-2a57b61bbf9ee2c23938fc571d403799f68b4b530d65e2cde219a429bbf10af5L876
> Fix for the Rails test schema including decimal greater than 38 precision

- test/cases/coerced_tests.rb
- test/cases/helper_sqlserver.rb
Ref: https://github.com/rails/rails/commit/cd5fe84fbed7e7b749dc144fd16d2539bb8391e2
> Coerce tests to check for subclasses rather than actual classes

- test/cases/coerced_tests.rb
Fix following tests:
https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/actions/runs/9149232428/job/25152652558
```
4) Failure:
ExplainTest#test_relation_explain_with_first [/usr/local/bundle/bundler/gems/rails-f31b853267ba/activerecord/test/cases/explain_test.rb:98]:
Expected /EXEC\ sp_executesql\ N'SELECT\ \[cars\]\.\*\ FROM\ \[cars\]\ ORDER\ BY\ \[cars\]\.\[id\]\ ASC\ OFFSET\ 0\ ROWS\ FETCH\ NEXT\ @0\ ROWS\ ONLY',\ N'@0\ int',\ @0\ =\ 1/ to match EXPLAIN for: SELECT [cars].* FROM [cars] ORDER BY [cars].[id] ASC OFFSET 0 ROWS FETCH NEXT 1 ROWS ONLY [["LIMIT", 1]]
+----------------------------------------------------+--------+--------+--------+----------------------+----------------------+----------------------------------------------------+--------------------------------- …
```
> Coerced some explain tests

- test/cases/coerced_tests.rb
Coerce `ActiveRecord::Assertions::QueryAssertionsTest#test_assert_queries_match`.
https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/actions/runs/9149232428/job/25152652558
```
1) Failure:
ActiveRecord::Assertions::QueryAssertionsTest#test_assert_queries_match [/usr/local/bundle/bundler/gems/rails-f31b853267ba/activerecord/test/cases/assertions/query_assertions_test.rb:44]:
0 instead of 1 queries were executed.
Queries:
EXEC sp_executesql N'SELECT [posts].* FROM [posts] ORDER BY [posts].[id] ASC OFFSET 0 ROWS FETCH NEXT @0 ROWS ONLY', N'@0 int', @0 = 1.
Expected: 1
Actual: 0
```
> Coerce query assertion test

- test/cases/coerced_tests.rb
Updated `QueryCacheExpiryTest#test_insert_all_coerced` test to reflect changes made to Rails original version.
https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/actions/runs/9158512181/job/25177030073
```
5) Failure:
QueryCacheExpiryTest#test_insert_all_coerced [test/cases/coerced_tests.rb:2200]:
Expected clear_query_cache to be called 2 times, but was called 0 times.
Expected: 2
Actual: 0
```
> Updated coerced test

- lib/active_record/tasks/sqlserver_database_tasks.rb
- lib/arel/visitors/sqlserver.rb
Fix `ActiveRecord::ConnectionHandlingTest#test_0010_common APIs don't permanently hold a connection when permanent checkout is deprecated or disallowed`.
https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/actions/runs/9172172552/job/25218095721
```
5) Failure:
ActiveRecord::ConnectionHandlingTest#test_0010_common APIs don't permanently hold a connection when permanent checkout is deprecated or disallowed [/usr/local/bundle/bundler/gems/rails-cb977226eae5/activerecord/test/cases/connection_handling_test.rb:177]:
```
> Eliminate missed lease_connection calls

- .devcontainer/Dockerfile
- test/cases/rake_test_sqlserver.rb
Fix the following failing tests.
https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/actions/runs/9388881855/job/25855114274?pr=1190
```
3) Failure:
SQLServerRakeStructureDumpLoadTest#test_0001_dumps structure and accounts for defncopy oddities [test/cases/rake_test_sqlserver.rb:144]:
Expected /email\s+nvarchar\(4000\)/ to match "\t/* No foreign keys reference table 'dbo.users', or you do not have permissions on referencing tables. */\n\t/* No views with schema binding reference table 'dbo.users'. */\n\nCREATE TABLE [dbo].[users]\n\t( [id]          bigint          NOT NULL\n\t, [name]        nvarchar(4000)      NULL\n\t, [email]       nvarchar(4000)      NULL\n\t, [background1] nvarchar(max)       NULL\n\t, [background2] text                NULL\n\t, [created_at]  datetime2 …
```
> Update Freetds to match CI

- test/cases/adapter_test_sqlserver.rb
- test/cases/disconnected_test_sqlserver.rb
- test/cases/index_test_sqlserver.rb
- test/cases/scratchpad_test_sqlserver.rb
- test/cases/specific_schema_test_sqlserver.rb
Fix missing assertions warnings like:
https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/actions/runs/9430052163/job/25977137751?pr=1189
```
Test is missing assertions: `test_0001_records can be created successfully` /activerecord-sqlserver-adapter/test/cases/adapter_test_sqlserver.rb:551
```
> Add assertions to tests missing any assertions

- test/cases/execute_procedure_test_sqlserver.rb
Fix missing assertions message. Issue caused by `return` in block returning from the calling test.
https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/actions/runs/9437921639/job/25994350714
```
Test is missing assertions: `test_0006_test deprecation with transaction return when executing procedure` /activerecord-sqlserver-adapter/test/cases/execute_procedure_test_sqlserver.rb:45
```
> Fix missing assertion warning

- lib/active_record/connection_adapters/sqlserver_adapter.rb
- test/cases/adapter_test_sqlserver.rb
Fix `ActiveRecord::AdapterTest#test_0002_inspect does not show secrets`:
https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/actions/runs/9627344416/job/26554338325#step:4:274
```
1) Failure:
ActiveRecord::AdapterTest#test_0002_inspect does not show secrets [/usr/local/bundle/bundler/gems/rails-0b89a3393599/activerecord/test/cases/adapter_test.rb:330]:
Expected /ActiveRecord::ConnectionAdapters::\w+:0x[\da-f]+ env_name="\w+" role=:writing>/ to match "#<ActiveRecord::ConnectionAdapters::SQLServerAdapter version: 7.2.0.beta2, azure: false>".
```
See https://github.com/rails/rails/pull/50405
> Use default inspect for database adapter

- .github/workflows/ci.yml
- CHANGELOG.md
- lib/active_record/connection_adapters/sqlserver/core_ext/calculations.rb
Backport of https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/pull/1198
> Remove ActiveRecord::Relation#calculate patch

- test/cases/specific_schema_test_sqlserver.rb
- test/schema/sqlserver_specific_schema.rb
Rename test table that has a typo.
> Fix test table name typo

- CHANGELOG.md
- lib/active_record/connection_adapters/sqlserver/database_statements.rb
- lib/active_record/connection_adapters/sqlserver/schema_statements.rb
- test/cases/adapter_test_sqlserver.rb
- test/cases/schema_test_sqlserver.rb
- test/models/sqlserver/table_with_spaces.rb
- test/schema/sqlserver_specific_schema.rb
Added support for table names that contain spaces. This is related to https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/issues/1203
The regex to handle insert/update/select raw SQL was getting to complicated so I have broken it up for each case.
> Support table names containing spaces

- lib/active_record/connection_adapters/sqlserver/schema_statements.rb
- test/cases/schema_dumper_test_sqlserver.rb
This PR resolves the Issue #1207.
I added "guest" to the SQL query, and added a few extra lines of test code to check that the schema dumper does not add lines to create any of the MSSQL default schemas.
> Exclude "guest" schmea in schema dumper

- CHANGELOG.md
- lib/active_record/connection_adapters/sqlserver/schema_statements.rb
- test/cases/schema_test_sqlserver.rb
When parsing the table name from raw SQL, return `nil` if the raw SQL is blank. This fixes a issue caused by https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/pull/1206
The actual bug is described in a https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/issues/1209. The testing setup required to recreate the actual bug is complicated as you would need to create another database user who doesn't have the permissions to run `EXEC sp_help` on the affected view and you would need to create the ActiveRecord connection with that database user. Instead of recreating the actual bug, I just added check that the updated `get_raw_table_name` method checks for nil.
> Handle blank SQL when parsing table name

- CHANGELOG.md
- lib/active_record/connection_adapters/sqlserver_adapter.rb
- test/cases/adapter_test_sqlserver.rb
The constructor for `ActiveRecord::MismatchedForeignKey` was being incorrectly called and was failing. This PR fixes the constructor. Also added the connection pool as a parameter when errors are being translated.
CI passing against Rails SHA `0b3320bcd5e705302b5707bcf27a80537b812c1f`.
> Fix mismatched foreign key errors

- lib/active_record/connection_adapters/sqlserver/database_statements.rb
Fix the following tests:
- `ActiveRecord::Encryption::EncryptableRecordTest#test_0047_serialized binary data can be encrypted`
- `ActiveRecord::Encryption::EncryptableRecordTest#test_0050_encrypts normalized data`
See https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/actions/runs/10668688433/job/29568976002
> Fix serialized encrypted attributes

- .github/workflows/ci.yml
Temporary until https://github.com/microsoft/mssql-docker/issues/899 is resolved.
See https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/actions/runs/10987500629/job/30510421634 for example of CI not working.
> Switch Github runners to Ubuntu 20.04

- .github/workflows/ci.yml
- activerecord-sqlserver-adapter.gemspec
Rails 8 will require Ruby 3.2.0 or newer.
> Drop support to Ruby 3.1

- CHANGELOG.md
- lib/active_record/connection_adapters/sqlserver/database_statements.rb
- test/cases/view_test_sqlserver.rb
Enable identity insert on view's base table as it cannot be enabled on the view itself.
Fix for https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/issues/1224
> Enable identity insert on view's base table

- test/cases/coerced_tests.rb
To limit the results in SQL Server we use `FETCH NEXT @0 ROWS ONLY` instead of `LIMIT @0`. To use `FETCH NEXT` an order must be provided.
https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/actions/runs/11104499885/job/30848683699
```
1) Failure:
CalculationsTest#test_no_order_by_when_counting_all [/usr/local/bundle/bundler/gems/rails-ebd9beebebe9/activerecord/test/cases/calculations_test.rb:315]:
Expected /ORDER BY/ to not match "EXEC sp_executesql N'SELECT COUNT(*) FROM (SELECT 1 AS one FROM [accounts] ORDER BY [accounts].[id] ASC OFFSET 0 ROWS FETCH NEXT @0 ROWS ONLY) subquery_for_count', N'@0 int', @0 = 10".
```
> Coerce calculations test

- .github/workflows/ci.yml
- CHANGELOG.md
- lib/active_record/connection_adapters/sqlserver/database_statements.rb
- test/cases/view_test_sqlserver.rb
Backport of https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/pull/1228
Also, fixed CI.
> Enable identity insert on view's base table 

- test/cases/coerced_tests.rb
Backport coerced test from https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/pull/1167/files#diff-3f00d8ac91cdd36f48a1f18eb12bf3dc8d3cb7e48f7d21fc891ea63dfb6fd9ecR2478
> Coerce test

- test/cases/coerced_tests.rb
Fix for `PredicateBuilderTest`. Not sure why tests suddenly failing.
https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/actions/runs/11208481488/job/31152221363
```
1) Error:
ActiveRecord::PredicateBuilderTest#test_registering_new_handlers_for_association_coerced:
NameError: undefined local variable or method `topic_title' for an instance of ActiveRecord::PredicateBuilderTest
/usr/local/bundle/bundler/gems/rails-967c33d493e5/activerecord/lib/active_record/test_fixtures.rb:280:in `method_missing'
test/cases/coerced_tests.rb:1341:in `test_registering_new_handlers_for_association_coerced'
2) Error:
ActiveRecord::PredicateBuilderTest#test_registering_new_handlers_coerced:
NameError: undefined local variable or method `topic_title' for an instance of …
```
> Fix for PredicateBuilderTest

- CHANGELOG.md
- lib/active_record/connection_adapters/sqlserver/schema_statements.rb
- test/cases/schema_test_sqlserver.rb
> Allow INSERT statements with SELECT notation

- CHANGELOG.md
- lib/active_record/connection_adapters/sqlserver/database_statements.rb
- test/cases/adapter_test_sqlserver.rb
Fix queries with date and date-time placeholder conditions such as:
```ruby
where("written_on < ?", Date.today)
where("written_on < ?", DateTime.current) 
```
This should fix #1243.
> Fix queries with date and date-time placeholder conditions

- test/cases/coerced_tests.rb
See https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/actions/runs/11437592629/job/31817408337
Fix:
```
2) Failure:
ActiveRecord::PredicateBuilderTest#test_registering_new_handlers_for_joins [/usr/local/bundle/bundler/gems/rails-9a35e63d5203/activerecord/test/cases/relation/predicate_builder_test.rb:29]:
Expected /\[regexp_topic\]\.\[title\] ~ 'rails'/i to match "SELECT [topics].* FROM [topics] INNER JOIN [topics] [regexp_topic] ON [regexp_topic].[id] = [topics].[parent_id] AND [regexp_topic].[title] ~ N'rails' WHERE [topics].[type] IN (N'Reply', N'ReplyWithTitleObject', N'SpecialReply', N'WrongReply', N'UniqueReply', N'SillyUniqueReply')".
3) Error:
EnumTest#test_0100_declare multiple enums at a time coerced:
NoMethodError: undefined method `original_declare multiple …
```
> Fix tests for Rails 8.0.0.rc1

- CHANGELOG.md
- lib/active_record/connection_adapters/sqlserver/schema_statements.rb
- test/cases/schema_dumper_test_sqlserver.rb
- test/schema/sqlserver_specific_schema.rb
Binary basic columns should be limitable. So if you have a migration:
```ruby
create_table "test_table", id: false do |t|
t.binary_basic "test_col", limit: 16
end
```
The `test_col` column should be of type `binary_basic(16)`. Before it was being set to `binary_basic(1)`.
Fixes issue #1248
> Binary basic columns should be limitable

- CHANGELOG.md
- lib/arel/visitors/sqlserver.rb
- test/cases/optimizer_hints_test_sqlserver.rb
When optimization hints and ordering are used in the same query the ordering should come first in the generated SQL.
Fix for #1240.
> Fixed the ordering of optimizer hints in the generated SQL

- CHANGELOG.md
- lib/active_record/connection_adapters/sqlserver/schema_statements.rb
- test/cases/adapter_test_sqlserver.rb
Fix issue with the generated SQL for DISTINCT queries as reported in https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/issues/1256. The generated SQL:
- Unnecessarily added a ALIAS AS projection. 
- The column used of the ALIAS AS was being incorrectly quoted. This was caused by MySQL database also being used in multi database Rails application.
```ruby
Post.includes(:comments).joins(:comments).first
```
**Before:**
```sql
SELECT DISTINCT [posts].[id] AS alias_0, [posts].[id] FROM [posts] INNER JOIN [comments] ON [comments].[post_id] = [posts].[id] ORDER BY [posts].[id] ASC OFFSET 0 ROWS FETCH NEXT @0 ROWS ONLY
```
**After:**
```sql
SELECT DISTINCT [posts].[id] FROM [posts] INNER JOIN [comments] ON [comments].[post_id] = [posts].[id] ORDER BY [posts].[id] ASC OFFSET 0 ROWS …
```
> Fix distinct alias when multiple databases used

- lib/active_record/connection_adapters/sqlserver/database_statements.rb
- test/cases/coerced_tests.rb
Fix `ActiveRecord::InstrumentationTest#test_payload_affected_rows`.
https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/actions/runs/12275600971/job/34250983451
```
3) Failure:
ActiveRecord::InstrumentationTest#test_payload_affected_rows [/usr/local/bundle/bundler/gems/rails-7bb8fe2d4e98/activerecord/test/cases/instrumentation_test.rb:173]:
Expected: [4, 3, 2, 0]
Actual: [0, 0, 0, 0]
```
Ref: https://github.com/rails/rails/pull/53277
> Add affected_rows to sql.active_record

- CHANGELOG.md
- lib/active_record/connection_adapters/sqlserver/schema_statements.rb
- test/cases/schema_test_sqlserver.rb
Fixes https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/issues/1260
> Fix parsing of raw table name from SQL with extra parentheses

- CHANGELOG.md
- activerecord-sqlserver-adapter.gemspec
- lib/active_record/connection_adapters/sqlserver/database_statements.rb
`tiny_tds` now raises an error message in case it is unable to send a query, removing the need for the respective workaround in `activerecord-sql-adapter`.
https://github.com/rails-sqlserver/tiny_tds/pull/560
> TinyTDS v3+ is now required

- test/cases/column_test_sqlserver.rb
- test/cases/schema_dumper_test_sqlserver.rb
- test/support/connection_reflection.rb
`tiny_tds` v3 will raise an exception when using a TDS version older than v7.3 for the server connections. This is mostly to enforce that people do no longer use `tiny_tds` with ancient SQL servers (and report issues). But therefore, we can remove a couple of special cases in the `sqlserver-adapter` tests where they behaved differently if ran against older versions.
> Remove special handling for older TDS connections

- CHANGELOG.md
- activerecord-sqlserver-adapter.gemspec
Reverts rails-sqlserver/activerecord-sqlserver-adapter#1278
> Revert "Not compatible with TinyTDS v3+"

- lib/active_record/connection_adapters/sqlserver_adapter.rb
Remove unused `combine_bind_parameters` method.
> Remove unused method

- activerecord-sqlserver-adapter.gemspec
I am somewhat ashamed, but I only recently learned how the lazy operator (`~>`) resolves.
I think it would be good to restrict `tiny_tds` to the current major version. I have plans for v4, which would have breaking API changes, and the current `~> 3` would allow people to upgrade to v4, which we should prevent.
Sorry about that!
> Limit `tiny_tds` to v3

- lib/active_record/connection_adapters/sqlserver/schema_creation.rb
- lib/active_record/connection_adapters/sqlserver/schema_statements.rb
- test/cases/coerced_tests.rb
- test/cases/column_test_sqlserver.rb
Changes required following:
- https://github.com/rails/rails/pull/54333
- https://github.com/rails/rails/pull/54348
> Include cast type in column

- lib/arel/visitors/sqlserver.rb
- test/cases/coerced_tests.rb
Fix:
https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/actions/runs/13201053254/job/36852899208
```
1) Error:
UpdateAllTest#test_dynamic_update_all_with_one_joined_table:
NotImplementedError: NotImplementedError
/usr/local/bundle/bundler/gems/rails-cd4708bbcd0d/activerecord/test/cases/relation/update_all_test.rb:95:in `test_dynamic_update_all_with_one_joined_table'
2) Error:
UpdateAllTest#test_dynamic_update_all_with_two_joined_table:
NotImplementedError: NotImplementedError
/usr/local/bundle/bundler/gems/rails-cd4708bbcd0d/activerecord/test/cases/relation/update_all_test.rb:113:in `test_dynamic_update_all_with_two_joined_table'
```
Ref https://github.com/rails/rails/pull/53950
> Support joins in update_all

- lib/active_record/connection_adapters/sqlserver/core_ext/finder_methods.rb
- test/cases/coerced_tests.rb
Fix following tests:
https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/actions/runs/13201053254/job/36852898476
```
4) Failure:
ActiveRecord::AdapterConnectionTest#test_0015_idempotent SELECT queries allow retries [/usr/local/bundle/bundler/gems/rails-cd4708bbcd0d/activerecord/test/cases/adapter_test.rb:716]:
Expected false to be truthy.
Skipped:
ActiveRecord::AdapterConnectionTest#test_0015_idempotent SELECT queries allow retries [/usr/local/bundle/bundler/gems/rails-cd4708bbcd0d/activerecord/test/cases/adapter_test.rb:716]:
kill_connection_from_server unsupported
5) Failure:
ActiveRecord::AdapterConnectionTest#test_0016_query cacheable idempotent SELECT queries allow retries [/usr/local/bundle/bundler/gems/rails-cd4708bbcd0d/activerecord/test/cases/adapter_test.rb:735]: …
```
> Exist queries are retryable

- test/cases/coerced_tests.rb
Fix for checking if raw connection transaction open.
https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/actions/runs/13243848935/job/36965406558
```
2) Failure:
ActiveRecord::AdapterConnectionTest#test_0006_unmaterialized transaction state can be restored after a reconnect [/usr/local/bundle/bundler/gems/rails-50efa73e0a96/activerecord/test/cases/adapter_test.rb:604]:
Expected false to be truthy.
3) Failure:
ActiveRecord::AdapterConnectionTest#test_0003_materialized transaction state can be restored after a reconnect [/usr/local/bundle/bundler/gems/rails-50efa73e0a96/activerecord/test/cases/adapter_test.rb:570]:
Expected false to be truthy.
4) Failure:
ActiveRecord::AdapterConnectionTest#test_0002_materialized transaction state is reset after a reconnect …
```
> Fix for checking if raw connection transaction open

- test/cases/coerced_tests.rb
Fix `ActiveRecord::RelationTest#test_0011_runs queries when using pick with aggregate expression despite empty IN`. Test added by https://github.com/rails/rails/pull/53775
https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/actions/runs/13261486046/job/37018909018
```
2) Error:
ActiveRecord::RelationTest#test_0011_runs queries when using pick with aggregate expression despite empty IN:
ActiveRecord::StatementInvalid: TinyTds::Error: Column "posts.id" is invalid in the ORDER BY clause because it is not contained in either an aggregate function or the GROUP BY clause.
lib/active_record/connection_adapters/sqlserver/database_statements.rb:446:in `each'
lib/active_record/connection_adapters/sqlserver/database_statements.rb:446:in `handle_to_names_and_values' …
```
> Coerce relation test

- test/cases/coerced_tests.rb
Coerce test as cast type in SQL Server is varchar. 
Fixes:
https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/actions/runs/13285243589/job/37092391764
```
1) Failure:
ActiveRecord::ConnectionAdapters::SchemaCacheTest#test_yaml_load_8_0_dump_without_cast_type_still_get_the_right_one [/usr/local/bundle/bundler/gems/rails-d3e1fb41e9e2/activerecord/test/cases/connection_adapters/schema_cache_test.rb:195]:
Expected: :string
Actual: :varchar
```
> Coerce test as cast type in SQL Server is varchar

- test/cases/coerced_tests.rb
Remove workaround for Ruby 2.5/2.6, which are no longer supported.
> Remove workarounds for old Rubies

- CHANGELOG.md
- lib/active_record/connection_adapters/sqlserver/schema_creation.rb
- lib/active_record/connection_adapters/sqlserver/schema_statements.rb
- lib/active_record/connection_adapters/sqlserver_adapter.rb
Add support for index include as requested in https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/issues/473
Running the following:
```ruby
connection.add_index("testings", "last_name", include: :foo)
```
Before this PR generates:
```SQL
CREATE INDEX [index_testings_on_last_name] ON [testings] ([last_name])
```
After the PR it will generate:
```SQL
CREATE INDEX [index_testings_on_last_name] ON [testings] ([last_name]) INCLUDE ([foo])
```
Multiple include columns are supported using:
```ruby
connection.add_index("testings", "last_name", include: [:foo, :bar])
```
Ref: https://github.com/rails/rails/pull/44803
> Add support for `INDEX INCLUDE`

- lib/active_record/connection_adapters/sqlserver/schema_statements.rb
Fix warning message in Ruby 3.4.1 that symbols converted to strings will be frozen in future.
https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/actions/runs/13411232752/job/37461741457
```
/activerecord-sqlserver-adapter/lib/active_record/connection_adapters/sqlserver/schema_statements.rb:342: warning: string returned by :time.to_s will be frozen in the future
```
> Fix warning about symbol to string conversion being frozen in future

- lib/arel/visitors/sqlserver.rb
Include changes from https://github.com/rails/rails/pull/54561
Fixes following tests.
https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/actions/runs/13449856684/job/37582307288#step:4:528
```
1) Error:
UpdateAllTest#test_dynamic_update_all_with_two_joins_on_the_target:
ActiveRecord::StatementInvalid: TinyTds::Error: The multi-part identifier "developers.mentor_id" could not be bound.
lib/active_record/connection_adapters/sqlserver/database_statements.rb:445:in 'TinyTds::Result#each'
lib/active_record/connection_adapters/sqlserver/database_statements.rb:445:in 'ActiveRecord::ConnectionAdapters::SQLServer::DatabaseStatements#handle_to_names_and_values'
2) Error:
UpdateAllTest#test_dynamic_update_all_with_a_through_join:
ActiveRecord::StatementInvalid: TinyTds::Error: The …
```
> Update all subquery fixes

- CHANGELOG.md
- lib/active_record/connection_adapters/sqlserver/database_statements.rb
- test/cases/adapter_test_sqlserver.rb
The code to retrieve the rows affected from the results did not take into account that the column name `AffectedRows` could be in lowercase if `lowercase_schema_reflection` setting enabled.
Fixes https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/issues/1304
> Fix affected rows count when lowercase schema reflection enabled

- CHANGELOG.md
- lib/active_record/connection_adapters/sqlserver/database_statements.rb
- lib/active_record/connection_adapters/sqlserver/schema_statements.rb
- lib/active_record/connection_adapters/sqlserver/utils.rb
- test/cases/temporary_table_test_sqlserver.rb
This PR fixes an issue with inserting into temporary tables (https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/issues/1307). 
Temporary tables names start with the `#` character. The issue was happening because we were retrieving the temporary table's column information from the normal database rather than the `TEMPDB` database.
SQL Server does not store the temporary table name as it is given. For example, the `#temp_users` table might be stored in the `TEMPDB..objects` table's `name` column as `#temp_users_________________________________________________________________________________________________________00000000000B`. To get around this the `column_definitions_sql` query has been updated to use the `Object_ID` column instead. 
Ref:
- …
> Fix retrieval of temporary table's column information

- test/cases/coerced_tests.rb
Coerce tests that rely on `FETCH NEXT x ROWS` rather than `LIMIT`. Tests were added to Rails 8.1 in https://github.com/rails/rails/commit/c327b19b94a384b298d498fa19c93e68b3add7f9
> Coerce tests that use LIMIT in SQL

- lib/active_record/connection_adapters/sqlserver/database_statements.rb
Small refactor to reduce the size of the `build_insert_sql(insert)` method.
> Small refactor of Support insert_all and upsert_all using MERGE

- CHANGELOG.md
- README.md
- lib/active_record/connection_adapters/sqlserver/database_statements.rb
- lib/active_record/connection_adapters/sqlserver/schema_statements.rb
- lib/active_record/connection_adapters/sqlserver_adapter.rb
- test/cases/adapter_test_sqlserver.rb
- test/cases/coerced_tests.rb
- test/cases/schema_test_sqlserver.rb
This PR adds support for `insert_all` and `upsert_all` in the `activerecord-sqlserver-adapter`. As initially propsed on #859 / #869, it uses `MERGE` to achieve so.
The benefit of `ON DUPLICATE` clauses in other database systems is that you can pass it every data that you have in your Rails app without the need for de-duplication. With `MERGE`, it technically executes a join between the data we want to insert and the data in the target table. therefore, the values in the columns of our source data, which will be joined, need to be unique. Unique means unique across all primary keys and indexes with uniqueness. The following Rails test show-cases this well:
```ruby
def test_insert_all_with_skip_duplicates_and_autonumber_id_not_given
skip unless supports_insert_on_duplicate_skip? …
```
> Support `insert_all` and `upsert_all` using `MERGE`

- CHANGELOG.md
- lib/active_record/connection_adapters/sqlserver_adapter.rb
- test/cases/helper_sqlserver.rb
An exception was being silently thrown when getting the database version, and then defaulting to `2016`. 
In this PR:
- Fix the bug when retrieving the database version
- Stops the exception from being silently swallowed in future
- Outputs the database version after each test run to help debugging
> Correctly retrieve the SQL Server database version

- CHANGELOG.md
- lib/active_record/connection_adapters/sqlserver/database_statements.rb
I contributed [two tests to Rails](https://github.com/rails/rails/pull/54790) because I was not sure how `insert_all` and `upsert_all` should behave with duplicate identifiers, but with different values in other columns.
For `insert_all`, all DBMS only insert the first value. For `upsert_all`, PostgreSQL throws an error in this scenario, but with sqlite and MySQL, the last entry ends up in the database.
For now, I do not have a smarter idea than reversing the `inserts`, which ultimately provide the `values_list`. Adding `MAX` would be another idea, but I fear the SQL query would get much more complicated.
> Reverse order of values when upserting

- CHANGELOG.md
- lib/active_record/connection_adapters/sqlserver/database_statements.rb
- test/cases/insert_all_test_sqlserver.rb
- test/models/sqlserver/recurring_task.rb
- test/schema/sqlserver_specific_schema.rb
The previous `CASE` statement used `COALESCE` with `'NULL'` as a fallback value if either `source` or `target` were `NULL`. However, `'NULL'` as written in this statement, is a `varchar` and therefore does not work when comparing with other datatypes (e.g. `int`).
This commit changes the switch statement to check if either both values are equal, or both values are actually `NULL`.
> Fix SQL statement to calculate `updated_at` when upserting

- CHANGELOG.md
- lib/active_record/connection_adapters/sqlserver/database_statements.rb
- test/cases/insert_all_test_sqlserver.rb
- test/models/sqlserver/recurring_task.rb
- test/schema/sqlserver_specific_schema.rb
Backport of https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/pull/1320.
> Fix upserting with mixed data types

- lib/arel/visitors/sqlserver.rb
Port of https://github.com/rails/rails/pull/54722 for MSSQL
Fix following tests from CI run https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/actions/runs/14035778078/job/39293342462
- UpdateAllTest#test_update_all_with_left_joins_composite_primary_key_can_reference_joined_table:
- UpdateAllTest#test_update_all_with_self_left_joins_can_reference_joined_table:
- UpdateAllTest#test_update_all_with_string_joins_can_reference_joined_table:
- UpdateAllTest#test_update_all_with_left_outer_joins_can_reference_joined_table:
> Use a self-join for UPDATE with outer joins

- test/cases/coerced_tests.rb
Redefine isolation level method as MSSSQL resets isolation level after transaction unlike MySQL/PostgreSQL.
https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/actions/runs/14250370905/job/39941435835
```
1) Failure:
TransactionIsolationTest#test_0003_default_isolation_level [/usr/local/bundle/bundler/gems/rails-e0452e80137c/activerecord/test/cases/transaction_isolation_test.rb:80]:
Expected: 1
Actual: 2
```
> Redefine isolation level method as MSSSQL resets isolation after transaction

- .github/workflows/ci.yml
CI no longer working because of error message:
`
This is a scheduled Ubuntu 20.04 retirement. Ubuntu 20.04 LTS runner will be removed on 2025-04-15. For more details, see https://github.com/actions/runner-images/issues/11101
`
See https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/actions/runs/14555834333
> Use latest Ubuntu image on CI

- README.md
- lib/active_record/connection_adapters/sqlserver/schema_statements.rb
- lib/active_record/connection_adapters/sqlserver_adapter.rb
- test/cases/coerced_tests.rb
Refactor native database types for https://github.com/rails/rails/pull/54875
Fixes (https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/actions/runs/14670746703/job/41176483142?pr=1325):
```
1) Error:
ActiveRecord::AdapterTest#test_invalid_column:
NameError: undefined local variable or method 'native_database_types' for class ActiveRecord::ConnectionAdapters::SQLServerAdapter
/usr/local/bundle/bundler/gems/rails-99e27fa586af/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:894:in 'ActiveRecord::ConnectionAdapters::AbstractAdapter.valid_type?'
/usr/local/bundle/bundler/gems/rails-99e27fa586af/activerecord/test/cases/adapter_test.rb:57:in 'ActiveRecord::AdapterTest#test_invalid_column'
2) Error:
ActiveRecord::AdapterTest#test_valid_column:
NameError: …
```
> Move AbstractAdapter#valid_type? to a class method

- CHANGELOG.md
- lib/active_record/connection_adapters/sqlserver/database_statements.rb
Handle merge inserts that contain multiple `nil` identity columns. Eg:
```ruby
Book.upsert_all [
{ id: nil, name: "New edition 1" },
{ id: nil, name: "New edition 2" },
]
```
Previously the SQL generated would have been:
```sql
MERGE INTO [books] WITH (updlock, holdlock) AS target
using (SELECT *
FROM   (SELECT [id],
[name],
[created_at],
[updated_at],
[updated_on],
Row_number()
OVER (
partition BY [id]
ORDER BY [id] DESC ) AS rn_0
FROM   (VALUES 
(Ident_current(N'[books]') + Ident_incr(N'[books]'),
N'New edition 2',
CURRENT_TIMESTAMP,
CURRENT_TIMESTAMP,
CURRENT_TIMESTAMP),
(Ident_current(N'[books]') + Ident_incr(N'[books]'),
N'New edition 1',
CURRENT_TIMESTAMP,
CURRENT_TIMESTAMP,
CURRENT_TIMESTAMP)) AS t1 ([id], [name], [created_at],
[updated_at],
[updated_on])) AS ranked_source
WHERE …
```
> Fix multiple nil identity columns for merge insert

- .github/workflows/ci.yml
- CHANGELOG.md
- lib/active_record/connection_adapters/sqlserver/database_statements.rb
- test/cases/view_test_sqlserver.rb
- test/fixtures/sst_customers_view.yml
Fix issue with identity inserts through a view not working for fixtures. 
Fixes https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/issues/1224
> Enable identity insert on view's base table for fixtures

- lib/active_record/connection_adapters/sqlserver/database_statements.rb
Add affected_rows to ActiveRecord::Result. See https://github.com/rails/rails/pull/55060
Also, removed logic from `cast_result(result)` as the results have already been converted to `ActiveRecord::Result` by `perform_query`.
Fixes https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/actions/runs/15134938986/job/42544441561
```
1) Failure:
ActiveRecord::AdapterTest#test_0003_#exec_query queries return an ActiveRecord::Result with affected rows [/usr/local/bundle/bundler/gems/rails-d1baada0da5a/activerecord/test/cases/adapter_test.rb:158]:
Expected: 2
Actual: nil
```
> Add affected_rows to ActiveRecord::Result

- CHANGELOG.md
- lib/active_record/connection_adapters/sqlserver/database_statements.rb
…UAGE.
Hey Team,
Proposing this change to expand the support across other Azure SQL solutions, including Azure Synapse.
According to https://learn.microsoft.com/en-us/sql/t-sql/functions/langid-transact-sql?view=sql-server-ver17&viewFallbackFrom=azure-sqldw-latest < `@@LANGID` is supported by SQL Server, Azure SQL Database and Azure SQL Managed Instance, whereas https://learn.microsoft.com/en-us/sql/t-sql/functions/language-transact-sql?view=sql-server-ver17 adds Azure Synapse Analytics and Analytics Platform System.
> Support more Azure services by changing language source

- test/cases/helper_sqlserver.rb
- test/support/core_ext/backtrace_cleaner.rb
Treat ActiveRecord backtraces lines as if they are from the source code rather than from the Rails gem. 
Fixes the following tests. 
https://github.com/aidanharan/rails/pull/4/files#diff-895b194d1cd076295b52cf047d3452420d42f082f4208f4e97e1a9eb87caf0ee
```
1) Failure:
AssociationDeprecationTest::WarnModeTest#test_0001_report warns in :warn mode [/usr/local/bundle/bundler/gems/rails-4621f7131d2a/activerecord/test/cases/associations/deprecation_test.rb:127]:
Expected /The association DATS::Car#deprecated_tyres is deprecated, the method deprecated_tyres was invoked \(\/usr\/local\/bundle\/bundler\/gems\/rails-4621f7131d2a\/activerecord\/test\/cases\/associations\/deprecation_test.rb:126:in/ to match "W, [2025-07-07T09:38:38.097702 #30]  WARN -- : The association DATS::Car#deprecated_tyres is …
```
> Clean ActiveRecord backtraces as if they are in the source

- .github/workflows/ci.yml
- CHANGELOG.md
- lib/active_record/connection_adapters/sqlserver/schema_statements.rb
- test/cases/adapter_test_sqlserver.rb
- test/cases/temp_test_sqlserver.rb
Related to https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/issues/1355
When finding the column information of a table, include the database when calculating the table's `object_id`. Otherwise the database is assumed to be the connection's default database.
Ref: https://learn.microsoft.com/en-us/sql/t-sql/functions/object-id-transact-sql?view=sql-server-ver17
> Support cross database inserts
