rails-sqlserver/activerecord-sqlserver-adapter

lib/active_record/connection_adapters/sqlserver_adapter.rb
Fixes https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/issues/454
=> Switch primary key column look up order

lib/active_record/connection_adapters/sqlserver/quoting.rb
=> Overwrite _type_cast method

lib/active_record/connection_adapters/sqlserver/database_statements.rb
In some cases the values are returned as an array, and not as a hash.
=> fix: enhance user_options' parsing (#535)

CHANGELOG.md, lib/active_record/connection_adapters/sqlserver/database_statements.rb, lib/active_record/connection_adapters/sqlserver/schema_statements.rb, test/cases/scratchpad_test_sqlserver.rb
=> Perf w/inserts. Check binds & use schema cache.

lib/active_record/connection_adapters/sqlserver/schema_statements.rb, test/bin/setup.sh, test/cases/specific_schema_test_sqlserver.rb, test/models/sqlserver/dot_table_name.rb, test/schema/sqlserver_specific_schema.rb
SQL Server 2017 Community Technology Preview 2.0 now available
https://blogs.technet.microsoft.com/dataplatforminsider/2017/04/19/sql-server-2017-community-technology-preview-2-0-now-available/
=> Test against CTP v2.0 http://bit.ly/2oPlP7E

lib/active_record/connection_adapters/sqlserver_adapter.rb
I just added 2017 to the Supported versions constant
=> Added 2017 to supported list

.travis.yml, appveyor.yml, circle.yml, lib/active_record/tasks/sqlserver_database_tasks.rb
Update the rails adapter to test against TinyTDS-v2.1.0.pre2
=> Use tiny-tds 2.1.0.pre2 with defncopy wrapper

lib/active_record/connection_adapters/sqlserver/schema_statements.rb
=> added with (nolock) hint to information_schema.views

.travis.yml, circle.yml, lib/active_record/connection_adapters/sqlserver/core_ext/calculations.rb, lib/active_record/connection_adapters/sqlserver/database_limits.rb, lib/active_record/connection_adapters/sqlserver/database_statements.rb, lib/active_record/connection_adapters/sqlserver/schema_statements.rb, lib/active_record/connection_adapters/sqlserver/transaction.rb, lib/active_record/connection_adapters/sqlserver/type/time_value_fractional.rb, lib/active_record/connection_adapters/sqlserver_adapter.rb, test/cases/coerced_tests.rb, test/cases/helper_sqlserver.rb, test/cases/migration_test_sqlserver.rb, test/support/core_ext/query_cache.rb
This PR aims to fix `master` tests so we can release a version compatible with [Rails 5.2](https://github.com/rails/rails/blob/v5.2.2/activerecord/CHANGELOG.md).
=> [Rails 5.2] Fix failing tests

lib/active_record/connection_adapters/sqlserver/core_ext/explain.rb, test/cases/showplan_test_sqlserver.rb
=> Fix explain with array conditions

lib/active_record/connection_adapters/sqlserver/database_statements.rb
This follows up to the changes in the rails master branch https://github.com/rails/rails/commit/eb5fef554fde84d36b45191182ed98bd344dc967 and https://github.com/rails/rails/commit/5f9e0f848e83688a7f7b5c0b2285144563d84f36.
=> Remove unused args to follow up to rails master branch

.travis.yml, lib/active_record/connection_adapters/sqlserver/database_statements.rb
=> #sql_for_insert set table name in case when pk is not nil

lib/active_record/connection_adapters/sqlserver/database_statements.rb, test/cases/adapter_test_sqlserver.rb
Add ability to block writes to a database. This PR fixes the `ActiveRecord::ReadOnlyError expected but nothing was raised` errors.
References:
- https://github.com/rails/rails/pull/34505
- https://github.com/rails/rails/commit/bde898c1df17722a83e5e8866b2009273c5190c6
**Before**
https://travis-ci.org/github/rails-sqlserver/activerecord-sqlserver-adapter/jobs/675219724
```
6728 runs, 18687 assertions, 38 failures, 10 errors, 25 skips
```
**After**
https://travis-ci.org/github/rails-sqlserver/activerecord-sqlserver-adapter/jobs/675235092
```
6732 runs, 18723 assertions, 33 failures, 10 errors, 25 skips
```
=> Rails 6: Add ability to block writes to a database

.travis.yml, Dockerfile.ci, docker-compose.ci.yml
Update rubies from test matrix and add latest 2.7 ruby. Also create a separate org to keep all Docker images.
=> Update test matrix

lib/active_record/connection_adapters/sqlserver_adapter.rb, lib/active_record/sqlserver_base.rb, test/cases/adapter_test_sqlserver.rb
add database_exists? method. rails/rails#36471
=> Rails 6: add database_exists?

test/cases/coerced_tests.rb
Fixed randomly failing tests caused by models' schemas not already been loaded before tests were run. If the schema is not loaded then the loading of the schema causes the tests to fail as they cause unexpected queries to the database.
The use of `.send(:load_schema)` for this purpose is already used in the Rails tests https://github.com/rails/rails/blob/v6.0.2.2/activerecord/test/cases/null_relation_test.rb#L20
=> Rails 6: Fix randomly failing tests by loading models schema

lib/arel/visitors/sqlserver.rb
Fixes the failing `RelationTest#test_finding_with_subquery_with_eager_loading_in_from` test. The test only started failing as ordering was added to the test to fix random CI failure due to non-deterministic sorting order (https://github.com/rails/rails/commit/e679a4beb60565e60f6c9eca5e560de4baba6a1d).
SQL that was causing the issue:
```sql
SELECT * FROM (SELECT [comments].* FROM [comments] LEFT OUTER JOIN [posts] ON [posts].[id] = [comments].[post_id] WHERE [posts].[type] = @0 ORDER BY [comments].[id] ASC) subquery
```
=> Rails 6: Remove invalid order from FROM subquery

CHANGELOG.md, Rakefile, lib/active_record/connection_adapters/sqlserver/core_ext/active_record.rb, lib/active_record/connection_adapters/sqlserver/core_ext/attribute_methods.rb, lib/active_record/connection_adapters/sqlserver/core_ext/calculations.rb, lib/active_record/connection_adapters/sqlserver/core_ext/explain.rb, lib/active_record/connection_adapters/sqlserver/core_ext/explain_subscriber.rb, lib/active_record/connection_adapters/sqlserver/core_ext/finder_methods.rb, lib/active_record/connection_adapters/sqlserver/core_ext/preloader.rb, lib/active_record/connection_adapters/sqlserver/core_ext/query_methods.rb, lib/active_record/connection_adapters/sqlserver/showplan/printer_table.rb, lib/active_record/connection_adapters/sqlserver/showplan/printer_xml.rb, test/cases/column_test_sqlserver.rb, test/cases/transaction_test_sqlserver.rb, test/cases/trigger_test_sqlserver.rb, test/cases/uuid_test_sqlserver.rb
This PR is enabling frozen strings in some areas of the code. I decided to break this task into smaller PRs to mitigate issues and to make it easier to find any breaking changes.
=> Enable frozen strings - part 1

CHANGELOG.md, lib/active_record/connection_adapters/sqlserver/database_statements.rb
Small change to add `WAITFOR` as a read query type as it doesn't write to the database.
=> Added WAITFOR as read query

CHANGELOG.md, lib/arel/visitors/sqlserver.rb, test/cases/lateral_test_sqlserver.rb
Implement lateral using CROSS/OUTER APPLY
I added tests for both variants, both testing the generated sql and producing the expected result when executing the generated queries.
The tests pass, and I've also tested my use case for using lateral and that also works as expected.
Fixes #738 
Note however that this is my first significant contribution, so if I missed something/done something in a non-optimal way then please do let me know.
=> Lateral apply

test/cases/coerced_tests.rb
These tests were removed from Rails test suite and should not be coerced anymore.
=> Remove coerced tests that were removed from Rails test suite

test/cases/coerced_tests.rb
Reimplemented https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/pull/987 to select required grouped columns rather than using subquery.
=> [Rails 7] Coerce update all and delete all tests

MIT-LICENSE, README.md
=> Updated the copyright years

lib/active_record/connection_adapters/sqlserver/type/data.rb, lib/active_record/connection_adapters/sqlserver_adapter.rb, test/support/coerceable_test_sqlserver.rb
Fix the `Style/RedundantSelf` offences.
=> Rubocop: Style/RedundantSelf

test/cases/coerced_tests.rb
PR fixes the failing `SchemaDumperDefaultsTest#test_schema_dump_with_text_column` test.
SQL Server uses the `newid()` method to generate UUIDs. The Rails test uses `uuid()` (https://github.com/rails/rails/blob/24189390074049ca16da003dc796f1f64622173a/activerecord/test/cases/schema_dumper_test.rb#L857).
=> Use "newid()" SQL Server method to generate UUID

CHANGELOG.md
Added missing fix #1020 to the changelog.
=> Added #1020 to the changelog

lib/active_record/connection_adapters/sqlserver/database_limits.rb
https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/issues/1067
=> Remove deprecated methods

lib/active_record/connection_adapters/sqlserver/database_statements.rb
When generating the insert SQL take the `returning` columns into account.
Fixes the follow ActiveRecord tests:
- EagerAssociationTest#test_0038_preloading has_one with cpk
- EagerAssociationTest#test_0036_preloading belongs_to with cpk
=> Fix insert SQL with returning columns

test/cases/coerced_tests.rb
Remove tests that no longer need to be coerced when testing against Rails 7.1.1
=> Remove tests that no longer need to be coerced

test/cases/coerced_tests.rb
Remove commented out coerced test.
=> Remove commented out coerced test

lib/active_record/connection_adapters/sqlserver/database_statements.rb, lib/active_record/connection_adapters/sqlserver_adapter.rb
Refactor and cleanup the `internal_exec_query` code.
=> Refactor and cleanup the internal_exec_query code

lib/active_record/connection_adapters/sqlserver/quoting.rb, lib/active_record/connection_adapters/sqlserver/utils.rb
Cache the quoted table and column names.
Similar to Rails PR https://github.com/rails/rails/pull/48773.
=> Cache quoted names

lib/active_record/connection_adapters/sqlserver/database_statements.rb, lib/active_record/connection_adapters/sqlserver/quoting.rb
See https://github.com/rails/rails/pull/51174
=> Don't require an active connection for table and column quoting

lib/active_record/connection_adapters/sqlserver/database_statements.rb
Fixes `CascadedEagerLoadingTest#test_eager_association_loading_grafts_stashed_associations_to_correct_parent`.
=> Allow place-holder condition to be a query parameter

lib/active_record/connection_adapters/sqlserver/database_statements.rb
Fixes `EachTest#test_in_batches_executes_range_queries_when_constrained_and_opted_in_into_ranges`.
=> Allow integer place-holder condition to be a query parameter

Gemfile
Unpin minitest version to 5.21. 
See https://github.com/rails/rails/pull/51011
=> Unpin minitest version to 5.21

.github/workflows/ci.yml, Gemfile
Update CI to latest Ruby versions.
=> Update CI to latest Ruby versions

CHANGELOG.md, lib/active_record/connection_adapters/sqlserver/core_ext/calculations.rb
Backport of https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/pull/1198
=> Remove ActiveRecord::Relation#calculate patch

.github/workflows/ci.yml
CI was failing sometimes. Suggestion in https://github.com/orgs/community/discussions/116610 is to change `docker-compose` to `docker compose`.
=> Update docker compose command

CHANGELOG.md, lib/active_record/connection_adapters/sqlserver/database_statements.rb, lib/active_record/connection_adapters/sqlserver/showplan.rb, test/cases/coerced_tests.rb
Refactored the adapter to match the new abstract interface introduced by https://github.com/rails/rails/pull/52428
=> Refactor adapter interface to match abstract adapter

lib/active_record/connection_adapters/sqlserver/schema_statements.rb
Support dropping multiple tables. See https://github.com/rails/rails/pull/52773
=> Allow drop_table to accept an array of table names

lib/arel/visitors/sqlserver.rb
Backport https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/pull/1189
=> Fix update-all for composite key

.devcontainer/Dockerfile, Dockerfile.ci, activerecord-sqlserver-adapter.gemspec, docker-compose.ci.yml
Still need to fix failing tests.
=> Fix CI for Rails 8.0.0.rc1

activerecord-sqlserver-adapter.gemspec
=> Rails v8.0.0

CHANGELOG.md, lib/active_record/connection_adapters/sqlserver/schema_statements.rb, test/cases/schema_test_sqlserver.rb
Backport of https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/pull/1270
=> Fix parsing of raw table name from SQL with extra parentheses

CHANGELOG.md, activerecord-sqlserver-adapter.gemspec
Due to https://github.com/rails-sqlserver/tiny_tds/pull/560 in TinyTDS v3
=> Not compatible with TinyTDS v3+

lib/active_record/connection_adapters/sqlserver/database_statements.rb
Fix following https://github.com/rails/rails/pull/53955
=> Migrate ActiveRecord::Normalization to Active Model

lib/active_record/connection_adapters/sqlserver/database_statements.rb, test/cases/view_test_sqlserver.rb, test/fixtures/sst_customers_view.yml
Port of https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/pull/1333
=> Enable identity insert on view's base table for fixtures
